# version 0.0.1

# Run before each script
before_script:
#  - docker info

types:
  - build

#build_image:
#  type: build
#  script:
#    - docker build -t ubuntu:14:04
#    - docker run ubuntu:14:04 apt-get install git
    
job_ubuntu:
  type: build
  image: ubuntu_teonet
  script:
    - sh/build-ubuntu.sh
    - ./autogen.sh
    - make
    - app/teovpn -?
  only:
    - master
    
job_centos:
  type: build
  image: centos_teonet
  script:
    - sh/build-centos.sh
    - ./autogen.sh
    - make
    - app/teovpn -?
  only:
    - master    
    