# version 0.0.1

# Run before each script
before_script:
#  - docker info

types:
  - build

#build_image:
#  type: build
#  script:
#    - docker build -t ubuntu:14:04
#    - docker run ubuntu:14:04 apt-get install git
    
job1:
  type: build
  script:
    - sudo apt-get -y install autoconf intltool libtool libglib2.0-dev doxygen make gcc
    - ./autogen.sh
    - make
  only:
    - master