# version 0.0.1

# Run before each script
before_script:
  - export PATH=$HOME/bin:/usr/local/bin:/usr/bin:/bin
  - apt-get install -y git

types:
  - build

job1:
  type: build
  script:
    - autogen.sh
  only:
    - master