# version 0.0.2

# Run before each script
before_script:
#  - docker info

types:
  - build
  - deploy

#build_image:
#  type: build
#  script:
#    - docker build -t ubuntu:14:04
#    - docker run ubuntu:14:04 apt-get install git

# Image host voulume definition:
# /path/to/bind/from/host:/path/to/bind/in/container:rw
    
# Build    
job_ubuntu:
  type: build
  image: ubuntu_teonet
  #volumes (defined in /etc/gitlab-runner/config.toml): /home/kirill/_repo_:/builds/ksnet/repo:rw
  script:
    # Test volumes
    #- cp ./autogen.sh ../repo
    #- printenv
    # Make  
    #- sh/build-ubuntu.sh
    #- pwd
    - ./autogen.sh
    - make
    - app/teovpn -?
    # Test
    - make test
    # Build DEB package and upload it to repository
    - sh/make_package deb
  only:
    - master
    
job_centos:
  type: build
  image: centos_teonet
  script:
    # Make
    #- sh/build-centos.sh
    - ./autogen.sh
    - make
    - app/teovpn -?
    # Test
    - make test
    # Build RPM package and upload it to repository
    - sh/make_package yum
  only:
    - master    

job_fedora:
  type: build
  image: fedora_teonet
  script:
    # Make
    #- sh/build-centos.sh
    - ./autogen.sh
    - make
    - app/teovpn -?
    # Test
    - make test
  only:
    - master
    
job_opensuse:
  type: build
  image: opensuse_teonet
  script:
    # Make
    #- sh/build-opensuse.sh
    - ./autogen.sh
    - make
    - app/teovpn -?
    # Test
    - make test
    # Build RPM package and upload it to repository
    - sh/make_package zyp
  only:
    - master     
    
# Test

# Deploy
#job_ubuntu_deploy:
#  type: deploy
#  image: ubuntu_teonet
#  script:
#    # Build DEB package and upload it to repository
#    - ./autogen.sh
#    - cd sh; make; cd ..
#    - sh/make_package deb
#  only:
#    - master
    
#job_centos_deploy:
#  type: deploy
#  image: centos_teonet
#  script:
#    # Build RPM package and upload it to repository
#    - ./autogen.sh
#    - cd sh; make; cd ..
#    - sh/make_package yum
#  only:
#    - master

# Build teonet docker image and upload it to Docker HUB
build_teonet_image:
  type: deploy
  #image: ubuntu_host
  tags:
      - build_teonet_image
  script:
    - cd sh  
    #- ls -all
    - docker build -t kscherba/teonet .
    - docker login --username=kscherba --password=$CI_TEONET_DOCKER_PWD --email=kirill@scherba.ru
    - docker push kscherba/teonet
  only:
    - master
    