# version 0.0.1

# Run before each script
before_script:
  - docker info

build_image:
  script:
    - docker build -t ubuntu:14:04
    - docker run ubuntu:14:04 /script/to/run/tests
    
types:
  - build

job1:
  type: build
  script:
    - autogen.sh
  only:
    - master
    