types:
  - build
  - test
  - deploy

job1:
  type: build
  script:
    - autogen.sh
  only:
    - master
    
# Parallel deploy jobs
on_success:
  - “cap deploy production”
  - “cap deploy staging”
  