Teonet library: async_calls.h File Reference
async_calls.h File Reference
#include "subscribe.h"
Data Structures
struct teoAsyncClass
Teonet Async class data definition.
Typedefs
typedef struct teoAsyncClass teoAsyncClass
Teonet Async class data definition.
Functions
teoAsyncClass * teoAsyncInit (void *ke)
Async module initialize.
void teoAsyncDestroy (teoAsyncClass *ta)
Async module destroy and free allocated memory.
void ksnCoreSendCmdtoA (void *ke, const char *peer, uint8_t cmd, void *data, size_t data_length)
void teoSScrSendA (void *ke, uint16_t event, void *data, size_t data_length, uint8_t cmd)
void sendCmdAnswerToBinaryA (void *ke, void *rd, uint8_t cmd, void *data, size_t data_length)
void teoSScrSubscribeA (teoSScrClass *sscr, char *peer_name, uint16_t ev)
Send command to subscribe this host to event at remote peer.
Typedef Documentation
typedef struct teoAsyncClass teoAsyncClass
Teonet Async class data definition.
Function Documentation
void ksnCoreSendCmdtoA (void * ke, const char * peer, uint8_t cmd, void * data, size_t data_length)
References DEBUG, kev, KSN_CORE_SEND_CMD_TO, ksn_printf, ksnCoreSendCmdto(), malloc(), MODULE, and SEND_ASYNC.
Referenced by teo::Teonet::sendToA(), and teoAsyncTest().
void sendCmdAnswerToBinaryA (void * ke, void * rd, uint8_t cmd, void * data, size_t data_length)
References ksnCorePacketData::addr, DEBUG, ksnCorePacketData::from, ksnCorePacketData::from_len, kev, ksn_printf, ksnCoreSendto(), ksnLNullSendToL0(), ksnCorePacketData::l0_f, malloc(), MODULE, ksnCorePacketData::port, rd, SEND_ASYNC, and SEND_CMD_ANSWER_TO.
Referenced by ksnLNullSendEchoToL0A(), teo::Teonet::sendAnswerToA(), teo::Teonet::sendToL0A(), and teoAsyncTest().
void teoAsyncDestroy (teoAsyncClass * ta)
Async module destroy and free allocated memory.
Parameters
ls Pointer to teoAsyncClass
References teoAsyncClass::async_func_mutex, teoAsyncClass::cv_mutex, teoAsyncClass::cv_threshold, DEBUG_VV, teoAsyncClass::event_cb, ksnetEvMgrClass::event_cb, free(), teoAsyncClass::ke, ksn_puts, MODULE, and ksnetEvMgrClass::ta.
Referenced by modules_destroy().
teoAsyncClass* teoAsyncInit (void * ke)
Async module initialize.
Parameters
ke Pointer to ksnetEvMgrClass
Returns
Pointer to teoAsyncClass
References teoAsyncClass::async_func_mutex, teoAsyncClass::cv_mutex, teoAsyncClass::cv_threshold, DEBUG_VV, teoAsyncClass::event_cb, event_cb(), teoAsyncClass::f_multi_thread, teoAsyncClass::ke, ke, kev, ksn_puts, malloc(), MODULE, NOT_DEFINED_MULTITHREAD, teoAsyncClass::t_id, and teoAsyncClass::test.
Referenced by modules_init().
void teoSScrSendA (void * ke, uint16_t event, void * data, size_t data_length, uint8_t cmd)
References DEBUG, kev, ksn_printf, malloc(), MODULE, SEND_ASYNC, TEO_SSCR_SEND, and teoSScrSend().
Referenced by teo::Teonet::sendToSscrA(), and teoAsyncTest().
void teoSScrSubscribeA (teoSScrClass * sscr, char * peer_name, uint16_t ev)
Send command to subscribe this host to event at remote peer.
Parameters
sscr Pointer to teoSScrClass
peer_name Remote host name
ev Event
References DEBUG, teoSScrClass::ke, kev, ksn_printf, malloc(), MODULE, SEND_ASYNC, TEO_SSCR_SUBSCRIBE, and teoSScrSubscribe().
Referenced by teo::Teonet::subscribeA(), and teoAsyncTest().