Teonet library: teo::Teonet::LogReader Class Reference
teo::Teonet::LogReader Class Reference
#include <teonet.hpp>
Data Structures
struct PUserData
Public Types
using Watcher = teoLogReaderWatcher
using Flags = teoLogReaderFlag
Public Member Functions
LogReader (Teonet &teo)
LogReader (Teonet *teo)
template<typename AnyCallback >
Watcher * open (const char *name, const char *file_name, Flags flags=READ_FROM_BEGIN, const AnyCallback &cb=nullptr) const
int close (Watcher *wd) const
Member Typedef Documentation
using teo::Teonet::LogReader::Flags = teoLogReaderFlag
using teo::Teonet::LogReader::Watcher = teoLogReaderWatcher
Constructor & Destructor Documentation
teo::Teonet::LogReader::LogReader (Teonet & teo) inline
teo::Teonet::LogReader::LogReader (Teonet * teo) inline
Member Function Documentation
int teo::Teonet::LogReader::close (Watcher * wd) const inline
References teoLogReaderClose(), and teoLogReaderWatcher::user_data.
template<typename AnyCallback > Watcher* teo::Teonet::LogReader::open (const char * name, const char * file_name, Flags flags = READ_FROM_BEGIN, const AnyCallback & cb = nullptr) const inline
References data, teo::Teonet::getKe(), ksnetEvMgrClass::lr, and teoLogReaderOpenCbPP().
The documentation for this class was generated from the following file:
teonet.hpp