Teonet library: teo::Teonet::TeoDB Class Reference
teo::Teonet::TeoDB Class Reference
#include <teonet.hpp>
Data Structures
struct teoDbCQueData
Public Types
typedef teo_db_data teoDbData
typedef teo_db_data_range teoDbDataRange
typedef struct teo::Teonet::TeoDB::teoDbCQueData teoDbCQueData
Public Member Functions
TeoDB (Teonet *t, const std::string &peer, teoDbData **tdd)
TeoDB (const TeoDB &obj)
virtual ~TeoDB ()
Teonet * getTeonet () const
Get pointer to teonet class object.
ksnetEvMgrClass * getKe () const
CQue * getCQue ()
const char * getPeer () const
bool checkPeer (const char *peer_name)
std::unique_ptr< teoDbData > prepareRequest (const void *key, size_t key_len, const void *data, size_t data_len, uint32_t id, size_t *tdd_len)
ksnet_arp_data * send (uint8_t cmd, const void *key, size_t key_len, const void *data=NULL, size_t data_len=0)
template<typename Callback >
ksnet_arp_data * send (uint8_t cmd, const void *key, size_t key_len, Callback cb, double timeout, uint8_t cb_type, teo::teoPacket *rd=NULL, teoDbData **tdd=NULL, void *user_data=NULL)
ksnet_arp_data * send (uint8_t cmd, const void *key, size_t key_len, cqueCallback cb, double timeout, uint8_t cb_type, teo::teoPacket *rd=NULL, teoDbData **tdd=NULL, void *user_data=NULL)
int exec (uint32_t id)
bool process (teoEvents event, void *data)
Static Public Member Functions
static teoDbData * getData (teo::teoPacket *rd)
Member Typedef Documentation
teoDbCQueData
typedef struct teo::Teonet::TeoDB::teoDbCQueData teo::Teonet::TeoDB::teoDbCQueData
teoDbData
typedef teo_db_data teo::Teonet::TeoDB::teoDbData
teoDbDataRange
typedef teo_db_data_range teo::Teonet::TeoDB::teoDbDataRange
Constructor & Destructor Documentation
TeoDB() [1/2]
teo::Teonet::TeoDB::TeoDB (Teonet * t, const std::string & peer, teoDbData ** tdd) inline
TeoDB() [2/2]
teo::Teonet::TeoDB::TeoDB (const TeoDB & obj) inline
~TeoDB()
virtual teo::Teonet::TeoDB::~TeoDB () inline virtual
Member Function Documentation
checkPeer()
bool teo::Teonet::TeoDB::checkPeer (const char * peer_name) inline
Referenced by process().
exec()
int teo::Teonet::TeoDB::exec (uint32_t id) inline
References teo::Teonet::CQue::exec().
Referenced by process().
getCQue()
CQue* teo::Teonet::TeoDB::getCQue () inline
getData()
static teoDbData* teo::Teonet::TeoDB::getData (teo::teoPacket * rd) inline static
References rd.
Referenced by process().
getKe()
ksnetEvMgrClass* teo::Teonet::TeoDB::getKe () const inline
References teo::Teonet::getKe(), and getTeonet().
getPeer()
const char* teo::Teonet::TeoDB::getPeer () const inline
getTeonet()
Teonet* teo::Teonet::TeoDB::getTeonet () const inline
Get pointer to teonet class object.
Returns
Pointer to teonet class object
Referenced by getKe().
prepareRequest()
std::unique_ptr<teoDbData> teo::Teonet::TeoDB::prepareRequest (const void * key, size_t key_len, const void * data, size_t data_len, uint32_t id, size_t * tdd_len) inline
References data, and prepare_request_data().
process()
bool teo::Teonet::TeoDB::process (teoEvents event, void * data) inline
References checkPeer(), CMD_D_GET_ANSWER, CMD_D_LIST_ANSWER, CMD_D_LIST_LENGTH_ANSWER, CMD_D_LIST_RANGE_ANSWER, data, EV_K_RECEIVED, exec(), getData(), and rd.
send() [1/3]
template<typename Callback > ksnet_arp_data* teo::Teonet::TeoDB::send (uint8_t cmd, const void * key, size_t key_len, Callback cb, double timeout, uint8_t cb_type, teo::teoPacket * rd = NULL, teoDbData ** tdd = NULL, void * user_data = NULL) inline
References teo::Teonet::CQue::add(), cq, data, DEBUG, rd, teo::Teonet::TeoDB::teoDbCQueData::setl0Cli(), and teo_printf.
send() [2/3]
ksnet_arp_data* teo::Teonet::TeoDB::send (uint8_t cmd, const void * key, size_t key_len, const void * data = NULL, size_t data_len = 0) inline
References data.
send() [3/3]
ksnet_arp_data* teo::Teonet::TeoDB::send (uint8_t cmd, const void * key, size_t key_len, cqueCallback cb, double timeout, uint8_t cb_type, teo::teoPacket * rd = NULL, teoDbData ** tdd = NULL, void * user_data = NULL) inline
References teo::Teonet::CQue::add(), cq, DEBUG, rd, teo::Teonet::TeoDB::teoDbCQueData::setl0Cli(), and teo_printf.
The documentation for this class was generated from the following file:
teonet.hpp