Teonet library: teo::StringArray Class Reference
teo::StringArray Class Reference
Teonet string array class.
#include <teonet.hpp>
Data Structures
class iterator
Public Member Functions
StringArray ()
StringArray (const char *str, const char *separators=",", bool with_empty=true, int max_parts=0)
StringArray (const std::string &str, const std::string &separators=",", bool with_empty=true, int max_parts=0)
StringArray (const std::vector< const char * > &vstr, const char *separators=",")
StringArray & operator= (const StringArray &ar)
virtual ~StringArray ()
const char * operator[] (int i) const
int size () const
StringArray & add (const char *str)
StringArray & add (const std::string &str)
std::string to_string (const char *separator=NULL) const
std::string to_string (const std::string &separator) const
bool move (unsigned int fromIdx, unsigned int toIdx)
iterator begin ()
iterator end ()
Detailed Description
Teonet string array class.
Constructor & Destructor Documentation
teo::StringArray::StringArray () inline
teo::StringArray::StringArray (const char * str, const char * separators = ",", bool with_empty = true, int max_parts = 0) inline
teo::StringArray::StringArray (const std::string & str, const std::string & separators = ",", bool with_empty = true, int max_parts = 0) inline
teo::StringArray::StringArray (const std::vector< const char * > & vstr, const char * separators = ",") inline
virtual teo::StringArray::~StringArray () inline virtual
Member Function Documentation
StringArray& teo::StringArray::add (const char * str) inline
References ksnet_stringArrAdd().
StringArray& teo::StringArray::add (const std::string & str) inline
iterator teo::StringArray::begin () inline
iterator teo::StringArray::end () inline
bool teo::StringArray::move (unsigned int fromIdx, unsigned int toIdx) inline
References ksnet_stringArrMoveTo().
StringArray& teo::StringArray::operator= (const StringArray & ar) inline
References size().
const char* teo::StringArray::operator[] (int i) const inline
int teo::StringArray::size () const inline
References ksnet_stringArrLength().
Referenced by operator=().
std::string teo::StringArray::to_string (const char * separator = NULL) const inline
std::string teo::StringArray::to_string (const std::string & separator) const inline
The documentation for this class was generated from the following file:
teonet.hpp