Teonet library: teo::Teonet Class Reference
teo::Teonet Class Reference
Teonet class.
#include <teonet.hpp>
Inherited by MyTeonet.
Data Structures
class CQue
Teonet CQue callback function.
class LogReader
class TeoDB
Public Types
typedef void(* teoEventsCb) (Teonet &teo, teoEvents event, void *data, size_t data_len, void *user_data)
Teonet event callback.
typedef ksnCQueData cqueData
typedef ksnCQueCallback cqueCallback
Teonet CQue data structure.
Public Member Functions
ksnetEvMgrClass * getKe () const
Teonet class version.
Teonet (int argc, char **argv, teoEventsCb event_cb=NULL, int options=READ_ALL, int port=0, void *user_data=NULL)
Teonet constructor.
virtual ~Teonet ()
Teonet simple destructor.
void setAppType (const char *type)
Set Teonet application type.
void setAppVersion (const char *version)
Set Teonet application version.
int run ()
Start Teonet Event Manager and network communication.
void BroadcastSend (const char *to, uint8_t cmd, void *data, size_t data_len) const
Send command by name to peer.
ksnet_arp_data * sendTo (const char *to, uint8_t cmd, void *data, size_t data_len) const
ksnet_arp_data * sendTo (const char *to, uint8_t cmd, const std::string &data) const
void sendToA (const char *to, uint8_t cmd, void *data, size_t data_len) const
Send command by name to peer(asynchronously)
void sendToA (const char *to, uint8_t cmd, const std::string &data) const
void sendAnswerTo (teo::teoPacket *rd, const char *name, void *data, size_t data_len) const
Sent teonet command to peer or l0 client depend of input rd.
void sendAnswerTo (teo::teoPacket *rd, const char *name, const std::string &data) const
void sendAnswerToA (teo::teoPacket *rd, uint8_t cmd, void *data, size_t data_len) const
Sent teonet command to peer or l0 client depend of input rd (asynchronously)
void sendAnswerToA (teo::teoPacket *rd, uint8_t cmd, const std::string &data) const
int sendEchoTo (const char *to, void *data=NULL, size_t data_len=0) const
Send ECHO command to peer.
int sendToL0 (const char *addr, int port, const char *cname, size_t cname_length, uint8_t cmd, void *data, size_t data_len) const
Send data to L0 client.
int sendToL0 (const char *addr, int port, const std::string &cname, uint8_t cmd, void *data, size_t data_len) const
int sendToL0 (const char *addr, int port, const std::string &cname, uint8_t cmd, const std::string &data) const
int sendToL0 (teoL0Client *l0cli, uint8_t cmd, void *data, size_t data_len) const
Send data to L0 client with the teoL0Client structure.
void sendToL0A (const char *addr, int port, const char *cname, size_t cname_length, uint8_t cmd, void *data, size_t data_len) const
Send data to L0 client.
int sendEchoToL0 (const char *addr, int port, const char *cname, size_t cname_length, void *data, size_t data_len) const
Send ECHO command to L0 client.
int sendEchoToL0A (const char *addr, int port, const char *cname, size_t cname_length, void *data, size_t data_len) const
int sendEchoToL0 (teoL0Client *l0cli, void *data, size_t data_len) const
Send ECHO command to L0 client with teoL0Client structure.
int sendEchoToL0A (teoL0Client *l0cli, void *data, size_t data_len) const
void subscribe (const char *peer_name, uint16_t ev) const
void subscribeA (const char *peer_name, uint16_t ev) const
void sendToSscr (uint16_t ev, void *data, size_t data_length, uint8_t cmd=0) const
void sendToSscr (uint16_t ev, const std::string &data, uint8_t cmd=0) const
void sendToSscrA (uint16_t ev, const std::string &data, uint8_t cmd=0) const
void setCustomTimer (double time_interval=2.00)
Set custom timer interval.
const char * getClassVersion () const
Get this class version.
const char * getHostName () const
Return host name.
const char * getParam (int parm_number) const
Get additional application command line parameter defined in teoAppParam.
double getTime () const
Get KSNet event manager time.
const std::string getPath ()
Get path to teonet data folder.
void stop ()
Stop Teonet event manager.
teo::teoPacket * getPacket (void *data) const
Cast data to teo::teoPacket.
void metricCounter (const std::string &name, int value)
Send counter metric.
void metricCounter (const std::string &name, double value)
Send counter metric.
void metricMs (const std::string &name, double value)
Send time(ms) metric.
void metricGauge (const std::string &name, int value)
Send gauge metric.
void metricGauge (const std::string &name, double value)
Send gauge metric.
virtual void eventCb (teo::teoEvents event, void *data, size_t data_len, void *user_data)
Virtual Teonet event callback.
virtual void cqueueCb (uint32_t id, int type, void *data)
template<typename... Arguments>
std::string formatMessage (const char *format, const Arguments &... args)
CQue::cquePtr getCQueP ()
CQue class factory(maker)
CQue & getCQueR ()
CQue class factory(maker)
template<typename T >
T getCQue ()
CQue class factory(maker)
Static Public Member Functions
static const char * getTeonetVersion ()
Get Teonet library version.
static teo::teoAppParam * appParam (std::vector< const char * > params, std::vector< const char * > params_description)
Create Application parameters.
Detailed Description
Teonet class.
This is Teonet L0 client C++ wrapper
Examples
teocquecpp.cpp.
Member Typedef Documentation
cqueCallback
typedef ksnCQueCallback teo::Teonet::cqueCallback
Teonet CQue data structure.
cqueData
typedef ksnCQueData teo::Teonet::cqueData
teoEventsCb
typedef void(* teo::Teonet::teoEventsCb) (Teonet &teo, teoEvents event, void *data, size_t data_len, void *user_data)
Teonet event callback.
Constructor & Destructor Documentation
Teonet()
teo::Teonet::Teonet (int argc, char ** argv, teoEventsCb event_cb = NULL, int options = READ_ALL, int port = 0, void * user_data = NULL) inline
Teonet constructor.
Initialize KSNet Event Manager and network and set new default port
Parameters
argc Number of applications arguments (from main)
argv Applications arguments array (from main)
event_cb Events callback function called when an event happens
options Options set:
READ_OPTIONS - read options from command line parameters;
READ_CONFIGURATION - read options from configuration file
port Set default port number if non 0
user_data Pointer to user data or NULL if absent
References data, event_cb(), ke, and ksnetEvMgrInitPort().
~Teonet()
virtual teo::Teonet::~Teonet () inline virtual
Teonet simple destructor.
Member Function Documentation
appParam()
static teo::teoAppParam* teo::Teonet::appParam (std::vector< const char * > params, std::vector< const char * > params_description) inline static
Create Application parameters.
Parameters
params
params_description
Returns
References ksnetEvMgrAppParam::app_argc, ksnetEvMgrAppParam::app_argv, and ksnetEvMgrAppParam::app_descr.
BroadcastSend()
void teo::Teonet::BroadcastSend (const char * to, uint8_t cmd, void * data, size_t data_len) const inline
Send command by name to peer.
Parameters
kc Pointer to ksnCoreClass
to Peer name to send to
cmd Command
data Commands data
data_len Commands data length
Returns
Pointer to ksnet_arp_data or NULL if to peer is absent
References data, ke, and teoBroadcastSend().
cqueueCb()
virtual void teo::Teonet::cqueueCb (uint32_t id, int type, void * data) inline virtual
eventCb()
virtual void teo::Teonet::eventCb (teo::teoEvents event, void * data, size_t data_len, void * user_data) inline virtual
Virtual Teonet event callback.
Parameters
event
data
data_len
user_data
References data, and event_cb().
formatMessage()
template<typename... Arguments> std::string teo::Teonet::formatMessage (const char * format, const Arguments &... args) inline
References ksnet_formatMessage().
getClassVersion()
const char* teo::Teonet::getClassVersion () const inline
Get this class version.
Returns
getCQue()
template<typename T > T teo::Teonet::getCQue () inline
CQue class factory(maker)
Returns
T
getCQueP()
CQue::cquePtr teo::Teonet::getCQueP () inline
CQue class factory(maker)
Returns
Unique pointer to CQue object
Referenced by getCQueR().
getCQueR()
CQue& teo::Teonet::getCQueR () inline
CQue class factory(maker)
Returns
Reference to CQue object
References getCQueP().
getHostName()
const char* teo::Teonet::getHostName () const inline
Return host name.
Returns
References ke, and ksnetEvMgrGetHostName().
getKe()
ksnetEvMgrClass* teo::Teonet::getKe () const inline
Teonet class version.
References ke.
Referenced by teo::Teonet::TeoDB::getKe(), and getParam().
getPacket()
teo::teoPacket* teo::Teonet::getPacket (void * data) const inline
Cast data to teo::teoPacket.
Parameters
data Pointer to data
Returns
Pointer to teo::teoPacket
References data.
getParam()
const char* teo::Teonet::getParam (int parm_number) const inline
Get additional application command line parameter defined in teoAppParam.
Parameters
parm_number Number of application parameter (started from 1)
Returns
References ksnet_cfg::app_argv, getKe(), and ksnetEvMgrClass::ksn_cfg.
getPath()
const std::string teo::Teonet::getPath () inline
Get path to teonet data folder.
Returns
Null terminated static string
References getDataPath().
getTeonetVersion()
static const char* teo::Teonet::getTeonetVersion () inline static
Get Teonet library version.
Returns
References teoGetLibteonetVersion().
getTime()
double teo::Teonet::getTime () const inline
Get KSNet event manager time.
Parameters
ke Pointer to ksnetEvMgrClass
Returns
References ke, and ksnetEvMgrGetTime().
metricCounter() [1/2]
void teo::Teonet::metricCounter (const std::string & name, double value) inline
Send counter metric.
Parameters
name Metric name
value Metric counter value
References ke, and teoMetricCounterf().
metricCounter() [2/2]
void teo::Teonet::metricCounter (const std::string & name, int value) inline
Send counter metric.
Parameters
name Metric name
value Metric counter value
References ke, and teoMetricCounter().
metricGauge() [1/2]
void teo::Teonet::metricGauge (const std::string & name, double value) inline
Send gauge metric.
Parameters
name Metric name
value Metric gauge value
References ke, and teoMetricGaugef().
metricGauge() [2/2]
void teo::Teonet::metricGauge (const std::string & name, int value) inline
Send gauge metric.
Parameters
name Metric name
value Metric gauge value
References ke, and teoMetricGauge().
metricMs()
void teo::Teonet::metricMs (const std::string & name, double value) inline
Send time(ms) metric.
Parameters
name Metric name
value Metric ms value
References ke, and teoMetricMs().
run()
int teo::Teonet::run () inline
Start Teonet Event Manager and network communication.
Returns
Always 0
References ke, and ksnetEvMgrRun().
sendAnswerTo() [1/2]
void teo::Teonet::sendAnswerTo (teo::teoPacket * rd, const char * name, const std::string & data) const inline
References data, rd, and sendAnswerTo().
sendAnswerTo() [2/2]
void teo::Teonet::sendAnswerTo (teo::teoPacket * rd, const char * name, void * data, size_t data_len) const inline
Sent teonet command to peer or l0 client depend of input rd.
Parameters
ke Pointer to ksnetEvMgrClass
rd Pointer to rd
name Name to send to
data
data_len
Returns
References data, ke, rd, and sendCmdAnswerTo.
Referenced by sendAnswerTo().
sendAnswerToA() [1/2]
void teo::Teonet::sendAnswerToA (teo::teoPacket * rd, uint8_t cmd, const std::string & data) const inline
References data, ke, rd, and sendCmdAnswerToBinaryA().
sendAnswerToA() [2/2]
void teo::Teonet::sendAnswerToA (teo::teoPacket * rd, uint8_t cmd, void * data, size_t data_len) const inline
Sent teonet command to peer or l0 client depend of input rd (asynchronously)
Parameters
ke Pointer to ksnetEvMgrClass
rd Pointer to rd
name Name to send to
data
data_len
Returns
References data, ke, rd, and sendCmdAnswerToBinaryA().
sendEchoTo()
int teo::Teonet::sendEchoTo (const char * to, void * data = NULL, size_t data_len = 0) const inline
Send ECHO command to peer.
Parameters
to Peer name to send to
cmd Command
data Commands data
data_len Commands data length
Returns
True at success
References data, ke, and ksnCommandSendCmdEcho().
sendEchoToL0() [1/2]
int teo::Teonet::sendEchoToL0 (const char * addr, int port, const char * cname, size_t cname_length, void * data, size_t data_len) const inline
Send ECHO command to L0 client.
Parameters
addr IP address of remote peer
port Port of remote peer
cname L0 client name (include trailing zero)
cname_length Length of the L0 client name
cmd Command
data Data
data_len Data length
Returns
Return 0 if success; -1 if data length is too lage (more than 32319)
References data, ke, and ksnLNullSendEchoToL0().
Referenced by sendEchoToL0().
sendEchoToL0() [2/2]
int teo::Teonet::sendEchoToL0 (teoL0Client * l0cli, void * data, size_t data_len) const inline
Send ECHO command to L0 client with teoL0Client structure.
Parameters
l0cli Pointer to teoL0Client
data Data
data_len Data length
Returns
Return 0 if success; -1 if data length is too lage (more than 32319)
References teo::teoL0Client::addr, data, teo::teoL0Client::name, teo::teoL0Client::name_len, teo::teoL0Client::port, and sendEchoToL0().
sendEchoToL0A() [1/2]
int teo::Teonet::sendEchoToL0A (const char * addr, int port, const char * cname, size_t cname_length, void * data, size_t data_len) const inline
References data, ke, and ksnLNullSendEchoToL0A().
Referenced by sendEchoToL0A().
sendEchoToL0A() [2/2]
int teo::Teonet::sendEchoToL0A (teoL0Client * l0cli, void * data, size_t data_len) const inline
References teo::teoL0Client::addr, data, teo::teoL0Client::name, teo::teoL0Client::name_len, teo::teoL0Client::port, and sendEchoToL0A().
sendTo() [1/2]
ksnet_arp_data* teo::Teonet::sendTo (const char * to, uint8_t cmd, const std::string & data) const inline
References data, and sendTo().
sendTo() [2/2]
ksnet_arp_data* teo::Teonet::sendTo (const char * to, uint8_t cmd, void * data, size_t data_len) const inline
References data, ke, and ksnCoreSendCmdto().
Referenced by sendTo().
sendToA() [1/2]
void teo::Teonet::sendToA (const char * to, uint8_t cmd, const std::string & data) const inline
References data, and sendToA().
sendToA() [2/2]
void teo::Teonet::sendToA (const char * to, uint8_t cmd, void * data, size_t data_len) const inline
Send command by name to peer(asynchronously)
Parameters
kc Pointer to ksnCoreClass
to Peer name to send to
cmd Command
data Commands data
data_len Commands data length
References data, ke, and ksnCoreSendCmdtoA().
Referenced by sendToA().
sendToL0() [1/4]
int teo::Teonet::sendToL0 (const char * addr, int port, const char * cname, size_t cname_length, uint8_t cmd, void * data, size_t data_len) const inline
Send data to L0 client.
Usually it is an answer to request from L0 client
Parameters
addr IP address of remote peer
port Port of remote peer
cname L0 client name (include trailing zero)
cname_length Length of the L0 client name
cmd Command
data Data
data_len Data length
Returns
Return 0 if success; -1 if data length is too lage (more than 32319)
References data, ke, and ksnLNullSendToL0().
Referenced by sendToL0().
sendToL0() [2/4]
int teo::Teonet::sendToL0 (const char * addr, int port, const std::string & cname, uint8_t cmd, const std::string & data) const inline
References data, and sendToL0().
sendToL0() [3/4]
int teo::Teonet::sendToL0 (const char * addr, int port, const std::string & cname, uint8_t cmd, void * data, size_t data_len) const inline
References data, and sendToL0().
sendToL0() [4/4]
int teo::Teonet::sendToL0 (teoL0Client * l0cli, uint8_t cmd, void * data, size_t data_len) const inline
Send data to L0 client with the teoL0Client structure.
Parameters
l0cli Pointer to teoL0Client
cmd Command
data Data
data_len Data length
Returns
Return 0 if success; -1 if data length is too lage (more than 32319)
References teo::teoL0Client::addr, data, teo::teoL0Client::name, teo::teoL0Client::name_len, teo::teoL0Client::port, and sendToL0().
sendToL0A()
void teo::Teonet::sendToL0A (const char * addr, int port, const char * cname, size_t cname_length, uint8_t cmd, void * data, size_t data_len) const inline
Send data to L0 client.
Usually it is an answer to request from L0 client(asynchronously)
Parameters
addr IP address of remote peer
port Port of remote peer
cname L0 client name (include trailing zero)
cname_length Length of the L0 client name
cmd Command
data Data
data_len Data length
References data, ke, rd, and sendCmdAnswerToBinaryA().
sendToSscr() [1/2]
void teo::Teonet::sendToSscr (uint16_t ev, const std::string & data, uint8_t cmd = 0) const inline
References data, and sendToSscr().
sendToSscr() [2/2]
void teo::Teonet::sendToSscr (uint16_t ev, void * data, size_t data_length, uint8_t cmd = 0) const inline
References data, ke, and teoSScrSend().
Referenced by sendToSscr().
sendToSscrA()
void teo::Teonet::sendToSscrA (uint16_t ev, const std::string & data, uint8_t cmd = 0) const inline
References data, ke, and teoSScrSendA().
setAppType()
void teo::Teonet::setAppType (const char * type) inline
Set Teonet application type.
Parameters
type Application type string
References ke, and teoSetAppType().
setAppVersion()
void teo::Teonet::setAppVersion (const char * version) inline
Set Teonet application version.
Parameters
version Application version string
References ke, and teoSetAppVersion().
setCustomTimer()
void teo::Teonet::setCustomTimer (double time_interval = 2.00) inline
Set custom timer interval.
Parameters
time_interval
References ke, and ksnetEvMgrSetCustomTimer().
stop()
void teo::Teonet::stop () inline
Stop Teonet event manager.
References ke, and ksnetEvMgrStop().
subscribe()
void teo::Teonet::subscribe (const char * peer_name, uint16_t ev) const inline
References ke, and teoSScrSubscribe().
subscribeA()
void teo::Teonet::subscribeA (const char * peer_name, uint16_t ev) const inline
References ke, and teoSScrSubscribeA().
The documentation for this class was generated from the following file:
teonet.hpp