Teonet library: conf.h File Reference
conf.h File Reference
Data Structures
struct ksnet_cfg
Macros
#define KSN_BUFFER_DB_SIZE 2048
File: conf.h Author: Kirill Scherba.
#define KSN_BUFFER_SIZE 1024
Size of buffer for string variables.
#define KSN_BUFFER_SM_SIZE 256
Size of small buffer for string.
#define KSN_BUFFER_64_SIZE 64
Size of small buffer for string.
#define KSN_BUFFER_32_SIZE 32
Size of small buffer for string.
#define KSN_MAX_HOST_NAME 31
#define NUMBER_TRY_PORTS 1000
#define DEBUG_KSNET 1
#define KSNET_EVENT_MGR_TIMER 0.25
Main event manager timer interval.
#define KSNET_PORT_DEFAULT "9000"
Main network port.
#define KSNET_CRYPT 1
Crypt packages.
#define M_ENAMBE_CQUE 1
#define M_ENAMBE_STREAM 1
#define M_ENAMBE_PBLKF 1
#define M_ENAMBE_VPN 1
#define M_ENAMBE_TCP 1
#define M_ENAMBE_L0s 1
#define M_ENAMBE_TCP_P 1
#define M_ENAMBE_TUN 1
#define M_ENAMBE_TERM 1
#define M_ENAMBE_ASYNC 1
#define M_ENAMBE_METRIC 1
#define M_ENAMBE_LOGGING_SERVER 1
#define M_ENAMBE_LOGGING_CLIENT 1
#define M_ENAMBE_LOG_READER 1
#define TRUE 1
#define FALSE 0
Typedefs
typedef struct ksnet_cfg ksnet_cfg
Functions
void ksnet_addHWAddrConfig (ksnet_cfg *conf, char *hwaddr)
void read_config (ksnet_cfg *conf, int port_param)
Read configuration parameters from file.
void ksnet_configInit (ksnet_cfg *ksn_cfg, void *ke)
Get configuration parameters.
Macro Definition Documentation
DEBUG_KSNET
#define DEBUG_KSNET 1
FALSE
#define FALSE 0
KSN_BUFFER_32_SIZE
#define KSN_BUFFER_32_SIZE 32
Size of small buffer for string.
KSN_BUFFER_64_SIZE
#define KSN_BUFFER_64_SIZE 64
Size of small buffer for string.
KSN_BUFFER_DB_SIZE
#define KSN_BUFFER_DB_SIZE 2048
File: conf.h Author: Kirill Scherba.
Created on April 11, 2015, 6:10 AM
Configuration parameters module Size of buffer for UDP packets
Examples
teoack.c, teoackm.c, teol0cli.c, and teolarge.c.
KSN_BUFFER_SIZE
#define KSN_BUFFER_SIZE 1024
Size of buffer for string variables.
Examples
teol0cli.c.
KSN_BUFFER_SM_SIZE
#define KSN_BUFFER_SM_SIZE 256
Size of small buffer for string.
Examples
teostream.c.
KSN_MAX_HOST_NAME
#define KSN_MAX_HOST_NAME 31
KSNET_CRYPT
#define KSNET_CRYPT 1
Crypt packages.
KSNET_EVENT_MGR_TIMER
#define KSNET_EVENT_MGR_TIMER 0.25
Main event manager timer interval.
Examples
teomulti_t.c.
KSNET_PORT_DEFAULT
#define KSNET_PORT_DEFAULT "9000"
Main network port.
M_ENAMBE_ASYNC
#define M_ENAMBE_ASYNC 1
M_ENAMBE_CQUE
#define M_ENAMBE_CQUE 1
M_ENAMBE_L0s
#define M_ENAMBE_L0s 1
M_ENAMBE_LOG_READER
#define M_ENAMBE_LOG_READER 1
M_ENAMBE_LOGGING_CLIENT
#define M_ENAMBE_LOGGING_CLIENT 1
M_ENAMBE_LOGGING_SERVER
#define M_ENAMBE_LOGGING_SERVER 1
M_ENAMBE_METRIC
#define M_ENAMBE_METRIC 1
M_ENAMBE_PBLKF
#define M_ENAMBE_PBLKF 1
M_ENAMBE_STREAM
#define M_ENAMBE_STREAM 1
M_ENAMBE_TCP
#define M_ENAMBE_TCP 1
M_ENAMBE_TCP_P
#define M_ENAMBE_TCP_P 1
M_ENAMBE_TERM
#define M_ENAMBE_TERM 1
M_ENAMBE_TUN
#define M_ENAMBE_TUN 1
M_ENAMBE_VPN
#define M_ENAMBE_VPN 1
NUMBER_TRY_PORTS
#define NUMBER_TRY_PORTS 1000
TRUE
#define TRUE 1
Typedef Documentation
ksnet_cfg
typedef struct ksnet_cfg ksnet_cfg
Function Documentation
ksnet_addHWAddrConfig()
void ksnet_addHWAddrConfig (ksnet_cfg * conf, char * hwaddr)
ksnet_configInit()
void ksnet_configInit (ksnet_cfg * ksn_cfg, void * ke)
Get configuration parameters.
Todo:
: Set port param
References ke, ksnet_cfg::ke, and set_defaults().
Referenced by ksnetEvMgrInitPort().
read_config()
void read_config (ksnet_cfg * conf, int port_param)
Read configuration parameters from file.
Parameters
conf
port_param
References ksnet_cfg::block_cli_input_f, ksnet_cfg::color_output_disable_f, ksnet_cfg::crypt_f, ksnet_cfg::dflag, ksnet_cfg::extended_l0_log_f, ksnet_cfg::filter, getDataPath(), ksnet_cfg::host_name, ksnet_cfg::hot_keys_f, KSN_BUFFER_SIZE, KSN_BUFFER_SM_SIZE, ksnet_formatMessage(), ksnet_getSysConfigDir(), ksnet_cfg::l0_allow_f, ksnet_cfg::l0_tcp_ip_remote, ksnet_cfg::l0_tcp_port, ksnet_cfg::log_disable_f, ksnet_cfg::log_priority, ksnet_cfg::logging_f, ksnet_cfg::net_key, ksnet_cfg::network, ksnet_cfg::no_multi_thread_f, ksnet_cfg::pn, ksnet_cfg::port, ksnet_cfg::port_inc_f, ksnet_cfg::pp, ksnet_cfg::r_host_addr, ksnet_cfg::r_port, ksnet_cfg::r_tcp_f, ksnet_cfg::r_tcp_port, save_conf_back, ksnet_cfg::send_ack_event_f, ksnet_cfg::send_all_logs_f, ksnet_cfg::show_connect_f, ksnet_cfg::show_debug_f, ksnet_cfg::show_debug_vv_f, ksnet_cfg::show_debug_vvv_f, ksnet_cfg::show_peers_f, ksnet_cfg::show_tr_udp_f, ksnet_cfg::sig_segv_f, ksnet_cfg::statsd_ip, ksnet_cfg::statsd_peers_f, ksnet_cfg::statsd_port, ksnet_cfg::tcp_allow_f, ksnet_cfg::tcp_port, ksnet_cfg::vpn_connect_f, ksnet_cfg::vpn_dev_hwaddr, ksnet_cfg::vpn_dev_name, ksnet_cfg::vpn_ip, ksnet_cfg::vpn_ip_net, and ksnet_cfg::vpn_mtu.
Referenced by ksnetEvMgrInitPort(), and ksnMultiInit().