Teonet library: ev_mgr.c File Reference
ev_mgr.c File Reference
#include <stdio.h>
#include <errno.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <libgen.h>
#include <signal.h>
#include <pthread.h>
#include <stdbool.h>
#include "ev_mgr.h"
#include "net_multi.h"
#include "utils/utils.h"
#include "utils/rlutil.h"
#include "modules/metric.h"
Macros
#define MODULE "event_manager"
File: ev_mgr.c Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
#define RUN_NAME "-teonet.run"
#define kev ((ksnetEvMgrClass*)(ka->ke))
#define kev ((ksnetEvMgrClass *)w->data)
#define kev ((ksnetEvMgrClass*)(w->data))
#define SEND_EVENT(data, data_len, user_data) kev->event_cb(kev, EV_K_ASYNC , data, data_len, user_data)
#define kev ((ksnetEvMgrClass *)w->data)
Typedefs
typedef void(* set_sigaction_h) (int, siginfo_t *, void *)
Set sigaction function typedef.
Functions
ksnetEvMgrClass * __ke_from_command_class (ksnCommandClass *X)
ksnetArpClass * __arp_from_command_class (ksnCommandClass *X)
void idle_cb (EV_P_ ev_idle *w, int revents)
Idle callback (runs every 11.5 second of Idle time)
void idle_activity_cb (EV_P_ ev_idle *w, int revents)
Check activity Idle callback.
void idle_async_cb (EV_P_ ev_idle *w, int revents)
Async Idle callback.
void timer_cb (EV_P_ ev_timer *w, int revents)
Timer callback (runs every KSNET_EVENT_MGR_TIMER = 0.25 sec)
void host_cb (EV_P_ ev_io *w, int revents)
Teonet host fd read event callback.
void sig_async_cb (EV_P_ ev_async *w, int revents)
Async Event callback (Signal)
void sigint_cb (struct ev_loop *loop, ev_signal *w, int revents)
Signal to stop event loop callback.
void sigusr2_cb (struct ev_loop *loop, ev_signal *w, int revents)
SIGUSR2 signal handler.
int modules_init (ksnetEvMgrClass *ke)
Initialize connected to Event Manager Modules.
void modules_destroy (ksnetEvMgrClass *ke)
Destroy modules.
int send_cmd_disconnect_cb (ksnetArpClass *ka, char *name, ksnet_arp_data *arp_data, void *data)
void teoHotkeySetFilter (void *ke, void *filter)
void metric_teonet_count (teoMetricClass *tm)
Send default teonet metrics.
ksnetEvMgrClass * ksnetEvMgrInit (int argc, char **argv, ksn_event_cb_type event_cb, int options)
Initialize KSNet Event Manager and network.
ksnetEvMgrClass * ksnetEvMgrInitPort (int argc, char **argv, void(*event_cb)(ksnetEvMgrClass *ke, ksnetEvMgrEvents event, void *data, size_t data_len, void *user_data), int options, int port, void *user_data)
Initialize KSNet Event Manager and network and set new default port.
void teoSetAppType (ksnetEvMgrClass *ke, char *type)
Set Teonet application type.
void teoSetAppVersion (ksnetEvMgrClass *ke, char *version)
Set Teonet application version.
const char * teoGetAppType (ksnetEvMgrClass *ke)
Get current application type.
const char * teoGetAppVersion (ksnetEvMgrClass *ke)
Get current application version.
const char * teoGetLibteonetVersion ()
Get teonet library version.
void ksnetEvMgrStop (ksnetEvMgrClass *ke)
Stop event manager.
int ksnetEvMgrStatus (ksnetEvMgrClass *ke)
int ksnetEvMgrRun (ksnetEvMgrClass *ke)
Start KSNet Event Manager and network communication.
int ksnetEvMgrFree (ksnetEvMgrClass *ke, int free_async)
Free ksnetEvMgrClass after run.
void ksnetEvMgrSetCustomTimer (ksnetEvMgrClass *ke, double time_interval)
Set custom timer interval.
char * ksnetEvMgrGetHostName (ksnetEvMgrClass *ke)
Return host name.
host_info_data * teoGetHostInfo (ksnetEvMgrClass *ke, size_t *hd_len)
Get host info data.
void ksnetEvMgrAsync (ksnetEvMgrClass *ke, void *data, size_t data_len, void *user_data)
Async call to Event manager.
double ksnetEvMgrGetTime (ksnetEvMgrClass *ke)
Get KSNet event manager time.
void connect_r_host_cb (ksnetEvMgrClass *ke)
Connect to remote host.
void open_local_port (ksnetEvMgrClass *ke)
Send packet to local address to open private firewall.
int remove_peer_addr (ksnetEvMgrClass *ke, __CONST_SOCKADDR_ARG addr)
Remove peer by address.
int check_connected_cb (ksnetArpClass *ka, char *peer_name, ksnet_arp_data_ext *arp, void *data)
Check connected peers, send trip time request and disconnect peer at timeout.
int ksnetEvMgrRestart (int argc, char **argv)
Restart application.
Variables
int teo_argc
char ** teo_argv
const char * null_str = ""
File: ev_mgr.h Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
char run_file [KSN_BUFFER_SIZE]
Macro Definition Documentation
kev [1/4]
#define kev ((ksnetEvMgrClass*)(ka->ke))
kev [2/4]
#define kev ((ksnetEvMgrClass *)w->data)
kev [3/4]
#define kev ((ksnetEvMgrClass*)(w->data))
kev [4/4]
#define kev ((ksnetEvMgrClass *)w->data)
MODULE
#define MODULE "event_manager"
File: ev_mgr.c Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
Created on April 11, 2015, 2:13 AM
Event manager module
RUN_NAME
#define RUN_NAME "-teonet.run"
SEND_EVENT
#define SEND_EVENT (data, data_len, user_data) kev->event_cb(kev, EV_K_ASYNC , data, data_len, user_data)
Typedef Documentation
set_sigaction_h
typedef void(* set_sigaction_h) (int, siginfo_t *, void *)
Set sigaction function typedef.
Function Documentation
__arp_from_command_class()
ksnetArpClass* __arp_from_command_class (ksnCommandClass * X)
References ksnCommandClass::kc.
__ke_from_command_class()
ksnetEvMgrClass* __ke_from_command_class (ksnCommandClass * X)
References ksnCommandClass::kc.
check_connected_cb()
int check_connected_cb (ksnetArpClass * ka, char * peer_name, ksnet_arp_data_ext * arp, void * data)
Check connected peers, send trip time request and disconnect peer at timeout.
Parameters
ka
peer_name
arp_data
data
References CHECK_EVENTS_AFTER, kev, ksnCommandSendCmdEcho(), ksnetEvMgrGetTime(), send_cmd_disconnect_cb(), TRIPTIME, and TRIPTIME_LEN.
Referenced by idle_activity_cb().
connect_r_host_cb()
void connect_r_host_cb (ksnetEvMgrClass * ke)
Connect to remote host.
Parameters
ke Pointer to ksnetEvMgrClass
References CMD_CONNECT_R, data, DEBUG, getIPs(), ip_is_private(), ke, ksn_printf, ksnCoreSendto(), ksnet_stringArrFree(), ksnet_stringArrLength(), ksnTCPProxyClientConnect(), and MODULE.
Referenced by idle_activity_cb(), and idle_cb().
host_cb()
void host_cb (EV_P_ ev_io * w, int revents)
Teonet host fd read event callback.
param loop
Parameters
w
revents
idle_activity_cb()
void idle_activity_cb (EV_P_ ev_idle * w, int revents)
Check activity Idle callback.
Start(restart) connection to R-Host and check connections to all peers.
param loop
Parameters
w
revents
References check_connected_cb(), connect_r_host_cb(), DEBUG_VV, kev, ksn_printf, ksnetArpGetAll(), MODULE, and w.
Referenced by ksnetEvMgrRun().
idle_async_cb()
void idle_async_cb (EV_P_ ev_idle * w, int revents)
Async Idle callback.
Process async queue messages
param loop
Parameters
w
revents
References kev, and w.
idle_cb()
void idle_cb (EV_P_ ev_idle * w, int revents)
Idle callback (runs every 11.5 second of Idle time)
This callback started by event manager timer after every CHECK_EVENTS_AFTER = 11.5 second. Send two user event: first EV_K_STARTED sent at startup (when application started) and second EV_K_IDLE sent every tick.
param loop
Parameters
w Pointer to watcher
revents
Todo:
: open_local_port(kev);
Todo:
: host_cb(EV_A_ (ev_io*)w, revents);
References connect_r_host_cb(), DEBUG_VV, EV_K_IDLE, EV_K_STARTED, ke, ksn_printf, ksnCoreSetEventTime, MODULE, and w.
Referenced by ksnetEvMgrRun().
ksnetEvMgrAsync()
void ksnetEvMgrAsync (ksnetEvMgrClass * ke, void * data, size_t data_len, void * user_data)
Async call to Event manager.
Parameters
ke Pointer to ksnetEvMgrClass
data Pointer to data
data_len Data length
user_data Pointer to user data
Examples
teofossa.c.
References data, and ke.
Referenced by teoLoggingClientSend().
ksnetEvMgrFree()
int ksnetEvMgrFree (ksnetEvMgrClass * ke, int free_async)
Free ksnetEvMgrClass after run.
Parameters
ke Pointer to ksnetEvMgrClass
free_async 1 - free async queue data and destroy queue mutex; 0 - free basic class data; 2 - free all - async queue data and basic class data
Returns
References EV_K_STOPPED, EV_K_STOPPED_BEFORE, ke, ksn_printf, ksnetEvMgrRestart(), MESSAGE, MODULE, modules_destroy(), and run_file.
Referenced by ksnMultiDestroy(), and teoMultiRemoveNet().
ksnetEvMgrGetHostName()
char* ksnetEvMgrGetHostName (ksnetEvMgrClass * ke) inline
Return host name.
Parameters
ke Pointer to ksnetEvMgrClass
Returns
Examples
teoack.c, teoackm.c, teol0cli.c, teolarge.c, and teosend.c.
References ke.
Referenced by _check_connected(), event_cb(), teo::Teonet::getHostName(), ksnetEvMgrRun(), and teoGetHostInfo().
ksnetEvMgrGetTime()
double ksnetEvMgrGetTime (ksnetEvMgrClass * ke)
Get KSNet event manager time.
Parameters
ke Pointer to ksnetEvMgrClass
Returns
References ke.
Referenced by _check_connected(), check_connected_cb(), teo::Teonet::getTime(), ksnCommandEchoBuffer(), ksnCommandSendCmdEcho(), ksnCoreCheckNewPeer(), ksnCoreProcessPacket(), ksnet_printf(), ksnetArpShowData(), ksnetEvMgrSetCustomTimer(), ksnSplitCombine(), and timer_cb().
ksnetEvMgrInit()
ksnetEvMgrClass* ksnetEvMgrInit (int argc, char ** argv, ksn_event_cb_type event_cb, int options)
Initialize KSNet Event Manager and network.
Parameters
argc Number of applications arguments (from main)
argv Applications arguments array (from main)
event_cb Events callback function called when an event happens
options Options set:
READ_OPTIONS - read options from command line parameters;
READ_CONFIGURATION - read options from configuration file
Returns
Pointer to created ksnetEvMgrClass
Examples
teocque.c, teofossa.c, teolarge.c, teosend.c, teoterm.c, and teotun.c.
References event_cb(), and ksnetEvMgrInitPort().
Referenced by main(), and test2().
ksnetEvMgrInitPort()
ksnetEvMgrClass* ksnetEvMgrInitPort (int argc, char ** argv, void(*)(ksnetEvMgrClass *ke, ksnetEvMgrEvents event, void *data, size_t data_len, void *user_data) event_cb, int options, int port, void * user_data)
Initialize KSNet Event Manager and network and set new default port.
Parameters
argc Number of applications arguments (from main)
argv Applications arguments array (from main)
event_cb Events callback function called when an event happens
options Options set:
READ_OPTIONS - read options from command line parameters;
READ_CONFIGURATION - read options from configuration file
port Set default port number if non 0
user_data Pointer to user data or NULL if absent
Returns
Pointer to created ksnetEvMgrClass
Examples
teoack.c, teoackm.c, teodb_ex.c, teol0cli.c, teomulti_t.c, teosscr.c, teostream.c, and teotcp.c.
References APP_PARAM, BLOCK_CLI_INPUT, event_cb(), ke, ksnet_configInit(), ksnet_optRead(), ksnet_optSetApp(), null_str, read_config(), READ_CONFIGURATION, READ_OPTIONS, teo_argc, and teo_argv.
Referenced by ksnetEvMgrInit(), ksnMultiInit(), main(), teo::Teonet::Teonet(), and teonet_t().
ksnetEvMgrRestart()
int ksnetEvMgrRestart (int argc, char ** argv)
Restart application.
Parameters
argc
argv
Returns
Referenced by ksnetEvMgrFree(), and ksnMultiDestroy().
ksnetEvMgrRun()
int ksnetEvMgrRun (ksnetEvMgrClass * ke)
Start KSNet Event Manager and network communication.
Start KSNet Event Manager and network communication
Parameters
ke Pointer to ksnetEvMgrClass
Returns
Alway 0
Examples
teoack.c, teoackm.c, teocque.c, teodb_ex.c, teofossa.c, teol0cli.c, teolarge.c, teomulti_t.c, teosend.c, teosscr.c, teostream.c, teotcp.c, teoterm.c, and teotun.c.
References _ANSI_BROWN, _ANSI_NONE, DEBUG_VV, getDataPath(), idle_activity_cb(), idle_cb(), ke, KSN_BUFFER_SIZE, ksn_printf, ksn_puts, KSNET_EVENT_MGR_TIMER, ksnetEvMgrGetHostName(), MESSAGE, MODULE, modules_init(), run_file, RUN_NAME, sigint_cb(), sigusr2_cb(), and timer_cb().
Referenced by ksnMultiInit(), main(), teo::Teonet::run(), teonet_t(), and test2().
ksnetEvMgrSetCustomTimer()
void ksnetEvMgrSetCustomTimer (ksnetEvMgrClass * ke, double time_interval)
Set custom timer interval.
Parameters
ke Pointer to ksnetEvMgrClass
time_interval
Examples
teoack.c, teoackm.c, teocque.c, teolarge.c, teosend.c, and teosscr.c.
References ke, and ksnetEvMgrGetTime().
Referenced by event_cb(), main(), and teo::Teonet::setCustomTimer().
ksnetEvMgrStatus()
int ksnetEvMgrStatus (ksnetEvMgrClass * ke)
References ke.
Referenced by ksnCoreProcessPacket(), and teo_recvfrom().
ksnetEvMgrStop()
void ksnetEvMgrStop (ksnetEvMgrClass * ke) inline
Stop event manager.
Parameters
ke Pointer to ksnetEvMgrClass
Examples
teocque.c, teomulti_t.c, and teotcp.c.
References ke.
Referenced by event_cb(), hotkeys_cb(), ksnMultiDestroy(), main(), teo::Teonet::stop(), and teoMultiRemoveNet().
metric_teonet_count()
void metric_teonet_count (teoMetricClass * tm)
Send default teonet metrics.
Parameters
tm Pointer to teoMetricClass
References teoMetricClass::ke, ke, ksnetArpMetrics(), ksnLNullStat(), teoMetricCounter(), and teoMetricGauge().
Referenced by timer_cb().
modules_destroy()
void modules_destroy (ksnetEvMgrClass * ke)
Destroy modules.
Parameters
ke
References ke, ksnCoreDestroy(), ksnCQueDestroy(), ksnetHotkeysDestroy(), ksnLNullDestroy(), ksnStreamDestroy(), ksnTcpDestroy(), ksnTCPProxyDestroy(), ksnTDBdestroy(), ksnTermDestroy(), ksnTunDestroy(), ksnVpnDestroy(), teoAsyncDestroy(), teoLoggingClientDestroy(), teoLoggingServerDestroy(), teoLogReaderDestroy(), and teoMetricDestroy().
Referenced by ksnetEvMgrFree().
modules_init()
int modules_init (ksnetEvMgrClass * ke)
Initialize connected to Event Manager Modules.
Parameters
ke
Returns
References ke, ksnCoreInit(), ksnCQueInit(), ksnetHotkeysInit(), ksnLNullInit(), ksnStreamInit(), ksnTcpInit(), ksnTCPProxyInit(), ksnTDBinit(), ksnTermInit(), ksnTunInit(), ksnVpnInit(), teoAsyncInit(), teoHotkeySetFilter(), teoLoggingClientInit(), teoLoggingServerInit(), teoLogReaderInit(), and teoMetricInit().
Referenced by ksnetEvMgrRun().
open_local_port()
void open_local_port (ksnetEvMgrClass * ke)
Send packet to local address to open private firewall.
Todo:
: Need to send to real local IP
References CMD_NONE, getIPs(), ip_is_private(), ip_to_array(), ke, ksnCoreSendto(), ksnet_formatMessage(), ksnet_stringArrFree(), ksnet_stringArrLength(), and NULL_STR.
remove_peer_addr()
int remove_peer_addr (ksnetEvMgrClass * ke, __CONST_SOCKADDR_ARG addr)
Remove peer by address.
Parameters
ke Pointer to ksnetEvMgrClass
addr
Returns
Return values
0 peer not found
1 peer removed
-1 peer not removed, this is this host
References ke, and ksnetArpFindByAddr().
send_cmd_disconnect_cb()
int send_cmd_disconnect_cb (ksnetArpClass * ka, char * name, ksnet_arp_data * arp_data, void * data)
Referenced by check_connected_cb().
sig_async_cb()
void sig_async_cb (EV_P_ ev_async * w, int revents)
Async Event callback (Signal)
param loop
Parameters
w
revents
References data, DEBUG_VV, kev, ksn_puts, MODULE, and SEND_EVENT.
sigint_cb()
void sigint_cb (struct ev_loop * loop, ev_signal * w, int revents)
Signal to stop event loop callback.
Parameters
loop
w
revents
References DEBUG, DEBUG_KSNET, ke, ksn_puts, MODULE, and w.
Referenced by ksnetEvMgrRun().
sigusr2_cb()
void sigusr2_cb (struct ev_loop * loop, ev_signal * w, int revents)
SIGUSR2 signal handler.
Parameters
loop
w
revents
References DEBUG_KSNET, ke, ksn_printf, MESSAGE, MODULE, and w.
Referenced by ksnetEvMgrRun().
teoGetAppType()
const char* teoGetAppType (ksnetEvMgrClass * ke) inline
Get current application type.
Parameters
ke Pointer to ksnetEvMgrClass
Returns
Application type string
References ke.
teoGetAppVersion()
const char* teoGetAppVersion (ksnetEvMgrClass * ke) inline
Get current application version.
Parameters
ke Pointer to ksnetEvMgrClass
Returns
Application version string
References ke.
teoGetHostInfo()
host_info_data* teoGetHostInfo (ksnetEvMgrClass * ke, size_t * hd_len)
Get host info data.
Parameters
ke Pointer to ksnetEvMgrClass
hd_len Pointer to host_info_data length holder
Returns
Pointer to host_info_data, should be free after use
References ke, and ksnetEvMgrGetHostName().
teoGetLibteonetVersion()
const char* teoGetLibteonetVersion () inline
Get teonet library version.
Returns
References VERSION.
Referenced by teo::Teonet::getTeonetVersion(), and main().
teoHotkeySetFilter()
void teoHotkeySetFilter (void * ke, void * filter)
References khv, ksnet_stringArrFree(), and ksnet_stringArrSplit().
Referenced by hotkeys_cb(), and modules_init().
teoSetAppType()
void teoSetAppType (ksnetEvMgrClass * ke, char * type) inline
Set Teonet application type.
Parameters
ke Pointer to ksnetEvMgrClass
type Application type string
Examples
teodb_ex.c.
References ke.
Referenced by event_cb(), main(), and teo::Teonet::setAppType().
teoSetAppVersion()
void teoSetAppVersion (ksnetEvMgrClass * ke, char * version) inline
Set Teonet application version.
Parameters
ke Pointer to ksnetEvMgrClass
version Application version string
References ke.
Referenced by event_cb(), main(), and teo::Teonet::setAppVersion().
timer_cb()
void timer_cb (EV_P_ ev_timer * w, int revents)
Timer callback (runs every KSNET_EVENT_MGR_TIMER = 0.25 sec)
param loop
Parameters
w
revents
References CHECK_EVENTS_AFTER, DEBUG_VV, EV_K_TIMER, ke, ksn_printf, KSNET_EVENT_MGR_TIMER, ksnetEvMgrGetTime(), metric_teonet_count(), MODULE, and w.
Referenced by ksnetEvMgrRun().
Variable Documentation
null_str
const char* null_str = ""
File: ev_mgr.h Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
Created on April 11, 2015, 2:13 AM
Referenced by ksnetEvMgrInitPort().
run_file
char run_file[KSN_BUFFER_SIZE]
Referenced by ksnetEvMgrFree(), and ksnetEvMgrRun().
teo_argc
int teo_argc
Referenced by ksnetEvMgrInitPort().
teo_argv
char ** teo_argv
Referenced by ksnetEvMgrInitPort().