Teonet library: grammar-filter.c File Reference
grammar-filter.c File Reference
#include <string.h>
#include <stdio.h>
#include <limits.h>
Macros
#define YYBISON 1
#define YYBISON_VERSION "3.5.1"
#define YYSKELETON_NAME "yacc.c"
#define YYPURE 0
#define YYPUSH 0
#define YYPULL 1
#define YY_CAST(Type, Val) ((Type) (Val))
#define YY_REINTERPRET_CAST(Type, Val) ((Type) (Val))
#define YY_NULLPTR ((void*)0)
#define YYERROR_VERBOSE 0
#define YY_YY_GRAMMAR_FILTER_H_INCLUDED
#define YYDEBUG 0
#define YYTOKENTYPE
#define STRING 258
#define WORD 259
#define LOGVAR 260
#define AND 261
#define OR 262
#define NOT 263
#define YYSTYPE_IS_TRIVIAL 1
#define YYSTYPE_IS_DECLARED 1
#define YYPTRDIFF_T long
#define YYPTRDIFF_MAXIMUM LONG_MAX
#define YYSIZE_T unsigned
#define YYSIZE_MAXIMUM
#define YYSIZEOF(X) YY_CAST (YYPTRDIFF_T, sizeof (X))
#define YY_(Msgid) Msgid
#define YY_ATTRIBUTE_PURE
#define YY_ATTRIBUTE_UNUSED
#define YYUSE(E) ((void) (E))
#define YY_INITIAL_VALUE(Value) Value
#define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
#define YY_IGNORE_MAYBE_UNINITIALIZED_END
#define YY_IGNORE_USELESS_CAST_BEGIN
#define YY_IGNORE_USELESS_CAST_END
#define YY_ASSERT(E) ((void) (0 && (E)))
#define YYSTACK_ALLOC YYMALLOC
#define YYSTACK_FREE YYFREE
#define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
#define YYMALLOC malloc
#define YYFREE free
#define YYSTACK_GAP_MAXIMUM (YYSIZEOF (union yyalloc) - 1)
#define YYSTACK_BYTES(N)
#define YYCOPY_NEEDED 1
#define YYSTACK_RELOCATE(Stack_alloc, Stack)
#define YYCOPY(Dst, Src, Count)
#define YYFINAL 2
#define YYLAST 17
#define YYNTOKENS 13
#define YYNNTS 5
#define YYNRULES 10
#define YYNSTATES 21
#define YYUNDEFTOK 2
#define YYMAXUTOK 263
#define YYTRANSLATE(YYX) (0 <= (YYX) && (YYX) <= YYMAXUTOK ? yytranslate[YYX] : YYUNDEFTOK)
#define YYPACT_NINF (-10)
#define yypact_value_is_default(Yyn) ((Yyn) == YYPACT_NINF)
#define YYTABLE_NINF (-1)
#define yytable_value_is_error(Yyn) 0
#define yyerrok (yyerrstatus = 0)
#define yyclearin (yychar = YYEMPTY)
#define YYEMPTY (-2)
#define YYEOF 0
#define YYACCEPT goto yyacceptlab
#define YYABORT goto yyabortlab
#define YYERROR goto yyerrorlab
#define YYRECOVERING() (!!yyerrstatus)
#define YYBACKUP(Token, Value)
#define YYTERROR 1
#define YYERRCODE 256
#define YYDPRINTF(Args)
#define YY_SYMBOL_PRINT(Title, Type, Value, Location)
#define YY_STACK_PRINT(Bottom, Top)
#define YY_REDUCE_PRINT(Rule)
#define YYINITDEPTH 200
#define YYMAXDEPTH 10000
#define YYPOPSTACK(N) (yyvsp -= (N), yyssp -= (N))
Typedefs
typedef union YYSTYPE YYSTYPE
typedef signed char yytype_int8
typedef short yytype_int16
typedef unsigned char yytype_uint8
typedef unsigned short yytype_uint16
typedef yytype_int8 yy_state_t
typedef int yy_state_fast_t
Enumerations
enum yytokentype {
STRING = 258, WORD = 259, LOGVAR = 260, AND = 261,
OR = 262, NOT = 263, STRING = 258, WORD = 259,
LOGVAR = 260, AND = 261, OR = 262, NOT = 263
}
Functions
void yyerror (char *s)
int yylex (void)
int yylex_destroy (void)
void * yy_scan_string (const char *)
int yyparse (void)
void * malloc (YYSIZE_T)
void free (void *)
int log_string_match (char *log, char *match)
Variables
int result
char log_line [1024]
YYSTYPE yylval
int yychar
int yynerrs
Macro Definition Documentation
#define AND 261
#define LOGVAR 260
#define NOT 263
#define OR 262
#define STRING 258
#define WORD 259
#define YY_ (Msgid) Msgid
Referenced by yyparse().
#define YY_ASSERT (E) ((void) (0 && (E)))
Referenced by yyparse().
#define YY_ATTRIBUTE_PURE
#define YY_ATTRIBUTE_UNUSED
#define YY_CAST (Type, Val) ((Type) (Val))
Referenced by yyparse().
#define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
Referenced by yyparse().
#define YY_IGNORE_MAYBE_UNINITIALIZED_END
Referenced by yyparse().
#define YY_IGNORE_USELESS_CAST_BEGIN
Referenced by yyparse().
#define YY_IGNORE_USELESS_CAST_END
Referenced by yyparse().
#define YY_INITIAL_VALUE (Value) Value
#define YY_NULLPTR ((void*)0)
#define YY_REDUCE_PRINT (Rule)
Referenced by yyparse().
#define YY_REINTERPRET_CAST (Type, Val) ((Type) (Val))
#define YY_STACK_PRINT (Bottom, Top)
Referenced by yyparse().
#define YY_SYMBOL_PRINT (Title, Type, Value, Location)
Referenced by yyparse().
#define YY_YY_GRAMMAR_FILTER_H_INCLUDED
#define YYABORT goto yyabortlab
Referenced by yyparse().
#define YYACCEPT goto yyacceptlab
Referenced by yyparse().
#define YYBACKUP (Token, Value)
Value:
do                                                              \
    if (yychar == YYEMPTY)                                        \
      {                                                           \
        yychar = (Token);                                         \
        yylval = (Value);                                         \
        YYPOPSTACK (yylen);                                       \
        yystate = *yyssp;                                         \
        goto yybackup;                                            \
      }                                                           \
    else                                                          \
      {                                                           \
        yyerror (YY_("syntax error: cannot back up")); \
        YYERROR;                                                  \
      }                                                           \
  while (0)
#define YYBISON 1
#define YYBISON_VERSION "3.5.1"
#define yyclearin (yychar = YYEMPTY)
#define YYCOPY (Dst, Src, Count)
Value:
do                                        \
        {                                       \
          YYPTRDIFF_T yyi;                      \
          for (yyi = 0; yyi < (Count); yyi++)   \
            (Dst)[yyi] = (Src)[yyi];            \
        }                                       \
      while (0)
#define YYCOPY_NEEDED 1
#define YYDEBUG 0
#define YYDPRINTF (Args)
Referenced by yyparse().
#define YYEMPTY (-2)
Referenced by yyparse().
#define YYEOF 0
Referenced by yyparse().
#define YYERRCODE 256
#define yyerrok (yyerrstatus = 0)
#define YYERROR goto yyerrorlab
Referenced by yyparse().
#define YYERROR_VERBOSE 0
#define YYFINAL 2
Referenced by yyparse().
#define YYFREE free
#define YYINITDEPTH 200
Referenced by yyparse().
#define YYLAST 17
Referenced by yyparse().
#define YYMALLOC malloc
#define YYMAXDEPTH 10000
Referenced by yyparse().
#define YYMAXUTOK 263
#define YYNNTS 5
#define YYNRULES 10
#define YYNSTATES 21
Referenced by yyparse().
#define YYNTOKENS 13
Referenced by yyparse().
#define YYPACT_NINF (-10)
#define yypact_value_is_default (Yyn) ((Yyn) == YYPACT_NINF)
Referenced by yyparse().
#define YYPOPSTACK (N) (yyvsp -= (N), yyssp -= (N))
Referenced by yyparse().
#define YYPTRDIFF_MAXIMUM LONG_MAX
#define YYPTRDIFF_T long
Referenced by yyparse().
#define YYPULL 1
#define YYPURE 0
#define YYPUSH 0
#define YYRECOVERING () (!!yyerrstatus)
#define YYSIZE_MAXIMUM
Value:
YY_CAST (YYPTRDIFF_T,                                 \
           (YYPTRDIFF_MAXIMUM < YY_CAST (YYSIZE_T, -1)  \
            ? YYPTRDIFF_MAXIMUM                         \
            : YY_CAST (YYSIZE_T, -1)))
#define YYSIZE_T unsigned
Referenced by yyparse().
#define YYSIZEOF (X) YY_CAST (YYPTRDIFF_T, sizeof (X))
Referenced by yyparse().
#define YYSKELETON_NAME "yacc.c"
#define YYSTACK_ALLOC YYMALLOC
Referenced by yyparse().
#define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
#define YYSTACK_BYTES (N)
Value:
((N) * (YYSIZEOF (yy_state_t) + YYSIZEOF (YYSTYPE)) \
      + YYSTACK_GAP_MAXIMUM)
Referenced by yyparse().
#define YYSTACK_FREE YYFREE
Referenced by yyparse().
#define YYSTACK_GAP_MAXIMUM (YYSIZEOF (union yyalloc) - 1)
#define YYSTACK_RELOCATE (Stack_alloc, Stack)
Value:
do                                                                  \
      {                                                                 \
        YYPTRDIFF_T yynewbytes;                                         \
        YYCOPY (&yyptr->Stack_alloc, Stack, yysize);                    \
        Stack = &yyptr->Stack_alloc;                                    \
        yynewbytes = yystacksize * YYSIZEOF (*Stack) + YYSTACK_GAP_MAXIMUM; \
        yyptr += yynewbytes / YYSIZEOF (*yyptr);                        \
      }                                                                 \
    while (0)
Referenced by yyparse().
#define YYSTYPE_IS_DECLARED 1
#define YYSTYPE_IS_TRIVIAL 1
#define YYTABLE_NINF (-1)
#define yytable_value_is_error (Yyn) 0
Referenced by yyparse().
#define YYTERROR 1
Referenced by yyparse().
#define YYTOKENTYPE
#define YYTRANSLATE (YYX) (0 <= (YYX) && (YYX) <= YYMAXUTOK ? yytranslate[YYX] : YYUNDEFTOK)
Referenced by yyparse().
#define YYUNDEFTOK 2
#define YYUSE (E) ((void) (E))
Typedef Documentation
typedef int yy_state_fast_t
typedef yytype_int8 yy_state_t
typedef union YYSTYPE YYSTYPE
typedef short yytype_int16
typedef signed char yytype_int8
typedef unsigned short yytype_uint16
typedef unsigned char yytype_uint8
Enumeration Type Documentation
enum yytokentype
Enumerator
STRING
WORD
LOGVAR
AND
OR
NOT
STRING
WORD
LOGVAR
AND
OR
NOT
Function Documentation
void free (void *)
Examples:
teoackm.c, teodb_ex.c, teofossa.c, teol0cli.c, teosscr.c, and teotcp.c.
Referenced by _check_connected(), _send_subscribe_event_newvisit(), addr_port_free(), base64_cleanup(), cli_allow_user(), cli_command_name(), cli_count_filter(), cli_deny_user(), cli_done(), cli_loop(), cli_loop_free(), cli_match_filter(), cli_register_command(), cli_run_command(), cli_unregister_all(), cmd_disconnected_cb(), cmd_l0_check_cb(), cmd_l0_kick_client(), cmd_l0_to_cb(), connect_r_host_cb(), createCmdConnectPacket(), createCmdConnectRPacketUdp(), destroy_buffer(), event_cb(), event_cb_server(), teo::Teonet::formatMessage(), get_cb(), getDataPath(), teo::Teonet::getPath(), hotkeys_cb(), hotkeysResetFilter(), idle_stdin_cb(), init_pidfile(), ip_to_array(), kill_pidfile(), ksnCommandDestroy(), ksnCommandSendCmdConnect(), ksnCommandSendCmdConnectA(), ksnCommandSendCmdEcho(), ksnCoreDestroy(), ksnCoreProcessPacket(), ksnCoreSendCmdto(), ksnCoreSendto(), ksnCQueDestroy(), ksnCryptDestroy(), ksnDecryptPackage(), ksnet_optRead(), ksnet_printf(), ksnet_sformatMessage(), ksnet_stringArrFree(), ksnet_vformatMessage(), ksnetArpAddHost(), ksnetArpDestroy(), ksnetArpMetrics(), ksnetArpRemove(), ksnetArpRemoveAll(), ksnetArpShow(), ksnetArpShowLine(), ksnetArpShowStr(), ksnetEvMgrFree(), ksnetEvMgrRestart(), ksnetEvMgrRun(), ksnetHotkeysDestroy(), ksnHTTPDestroy(), ksnLNullClientDisconnect(), ksnLNullDestroy(), ksnLNullSendEchoToL0(), ksnLNullSendEchoToL0A(), ksnLNullSendToL0(), ksnModuleLDestroy(), ksnModulesDestroy(), ksnMultiDestroy(), ksnSplitCombine(), ksnSplitDestroy(), ksnSplitFreeRds(), ksnStreamClose(), ksnStreamDestroy(), ksnStreamSendTo(), ksnTCPProxyDestroy(), ksnTDBdelete(), ksnTDBdeleteNs(), ksnTDBdestroy(), ksnTDBgetNs(), ksnTDBnamespaceSet(), ksnTDBsetNs(), ksnTRUDPqueuesShow(), ksnTRUDPstatShow(), launch_app(), list_cb(), log_string_match(), main(), mg_resolve_async_opt(), monitor_timer_stop(), open_local_port(), teo::unique_raw_ptr::destroy< T >::operator()(), opt_usage(), pblMapRemoveFree(), peer_timer_stop(), peer_type_cb(), ping_timer_stop(), read_config(), request_public_ipv6(), set_buffer(), set_defaults(), sig_async_cb(), tcp_read_cb(), tcp_server_receive_cb(), teoArpGetExtendedArpTable_json_delete(), teoAsyncDestroy(), teoAuthDestroy(), teoBroadcastSend(), teoLoggingClientDestroy(), teoLoggingServerDestroy(), teoLogReaderClose(), teoLogReaderDestroy(), teoMetricDestroy(), teoMultiRemoveNet(), teoSScrDestroy(), teoSScrSend(), teowebConfigFree(), teowebConfigRead(), test_3_5(), tr_udp_timer_stop(), trudp_send_event_ack_to_app(), tuntap_release(), uconfigFileName(), yyparse(), and teo::teoL0Client::~teoL0Client().
int log_string_match (char * log, char * match)
References free(), malloc(), result, yy_scan_string(), yylex_destroy(), and yyparse().
Referenced by main(), teoLogCheck(), test_filter_1(), and test_filter_2().
void* malloc (YYSIZE_T)
Examples:
teodb_ex.c, and teosscr.c.
Referenced by _check_connected(), _send_subscribe_event_newvisit(), addr_port_init(), build_decoding_table(), cli_allow_user(), cli_loop(), cmd_l0_to_cb(), createCmdConnectPacket(), createCmdConnectRPacketTcp(), createCmdConnectRPacketUdp(), createCmdResendPacket(), event_cb(), event_cb_server(), init_pidfile(), init_string(), ksn_base64_decode(), ksn_base64_encode(), ksnCommandEchoBuffer(), ksnCoreCheckNewPeer(), ksnCoreCreatePacketFrom(), ksnCoreSendCmdto(), ksnCoreSendCmdtoA(), ksnCQueInit(), ksnCryptInit(), ksnDecryptPackage(), ksnEncryptPackage(), ksnet_stringArrCombine(), ksnet_stringArrSplit(), ksnet_vformatMessage(), ksnetArpShowDataJson(), ksnetEvMgrAsync(), ksnetEvMgrInitPort(), ksnetHotkeysInit(), ksnHTTPInit(), ksnLNullClientDisconnect(), ksnLNullClientsList(), ksnLNullInit(), ksnLNullSendToL0(), ksnModulesInit(), ksnSplitCombine(), ksnSplitPacket(), ksnStreamCreate(), ksnStreamInit(), ksnStreamSendTo(), ksnTCPProxyInit(), ksnTDBget(), ksnTDBinit(), launch_app(), log_string_match(), main(), memdup(), prepare_request_data(), request_public_ipv6(), send_by_type_check_cb(), sendCmdAnswerToBinaryA(), set_buffer(), stdin_cb(), teo_malloc(), teo_strndup(), teoArpGetExtendedArpTable_json(), teoAsyncInit(), teoAuthInit(), teoAuthProcessCommand(), teoGetHostInfo(), teoHotkeySetFilter(), teoLoggingClientInit(), teoLoggingServerInit(), teoLogReaderInit(), teoLogReaderOpenCbPP(), teoMetricInit(), teoSScrInit(), teoSScrSend(), teoSScrSendA(), teoSScrSubscribeA(), teowebConfigInit(), teoWSInit(), test_3_3(), and tuntap_init().
void* yy_scan_string (const char *)
Referenced by log_string_match().
void yyerror (char * s)
Referenced by yyparse().
int yylex (void)
Referenced by yyparse().
int yylex_destroy (void)
Referenced by log_string_match().
int yyparse (void)
References free(), log_line, result, YY_, YY_ASSERT, YY_CAST, YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN, YY_IGNORE_MAYBE_UNINITIALIZED_END, YY_IGNORE_USELESS_CAST_BEGIN, YY_IGNORE_USELESS_CAST_END, YY_REDUCE_PRINT, YY_STACK_PRINT, YY_SYMBOL_PRINT, YYABORT, YYACCEPT, yyalloc(), YYDPRINTF, YYEMPTY, YYEOF, yyerror(), YYERROR, YYFINAL, YYINITDEPTH, YYLAST, yylex(), yylval, YYMAXDEPTH, yynerrs, YYNSTATES, YYNTOKENS, yypact_value_is_default, YYPOPSTACK, YYPTRDIFF_T, YYSIZE_T, YYSIZEOF, YYSTACK_ALLOC, YYSTACK_BYTES, YYSTACK_FREE, YYSTACK_RELOCATE, yytable_value_is_error, YYTERROR, and YYTRANSLATE.
Referenced by log_string_match().
Variable Documentation
char log_line[1024]
Referenced by yyparse().
int result
Referenced by c_snprintf(), ksnet_stringArrSplit(), log_string_match(), main(), mg_parse_date_string(), write_pidfile(), and yyparse().
int yychar
YYSTYPE yylval
Referenced by yyparse().
int yynerrs
Referenced by yyparse().