Teonet library: grammar-filter.h File Reference
grammar-filter.h File Reference
Macros
#define YYDEBUG 0
#define YYTOKENTYPE
#define STRING 258
#define WORD 259
#define LOGVAR 260
#define AND 261
#define OR 262
#define NOT 263
#define YYSTYPE_IS_TRIVIAL 1
#define YYSTYPE_IS_DECLARED 1
Typedefs
typedef union YYSTYPE YYSTYPE
Enumerations
enum yytokentype {
STRING = 258, WORD = 259, LOGVAR = 260, AND = 261,
OR = 262, NOT = 263, STRING = 258, WORD = 259,
LOGVAR = 260, AND = 261, OR = 262, NOT = 263
}
Functions
int yyparse (void)
Variables
YYSTYPE yylval
Macro Definition Documentation
#define AND 261
#define LOGVAR 260
#define NOT 263
#define OR 262
#define STRING 258
#define WORD 259
#define YYDEBUG 0
#define YYSTYPE_IS_DECLARED 1
#define YYSTYPE_IS_TRIVIAL 1
#define YYTOKENTYPE
Typedef Documentation
typedef union YYSTYPE YYSTYPE
Enumeration Type Documentation
enum yytokentype
Enumerator
STRING
WORD
LOGVAR
AND
OR
NOT
STRING
WORD
LOGVAR
AND
OR
NOT
Function Documentation
int yyparse (void)
References free(), log_line, result, YY_, YY_ASSERT, YY_CAST, YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN, YY_IGNORE_MAYBE_UNINITIALIZED_END, YY_IGNORE_USELESS_CAST_BEGIN, YY_IGNORE_USELESS_CAST_END, YY_REDUCE_PRINT, YY_STACK_PRINT, YY_SYMBOL_PRINT, YYABORT, YYACCEPT, yyalloc(), YYDPRINTF, YYEMPTY, YYEOF, yyerror(), YYERROR, YYFINAL, YYINITDEPTH, YYLAST, yylex(), yylval, YYMAXDEPTH, yynerrs, YYNSTATES, YYNTOKENS, yypact_value_is_default, YYPOPSTACK, YYPTRDIFF_T, YYSIZE_T, YYSIZEOF, YYSTACK_ALLOC, YYSTACK_BYTES, YYSTACK_FREE, YYSTACK_RELOCATE, yytable_value_is_error, YYTERROR, and YYTRANSLATE.
Referenced by log_string_match().
Variable Documentation
YYSTYPE yylval