Teonet library: hotkeys.h File Reference
hotkeys.h File Reference
#include "config/config.h"
#include <ev.h>
#include <sys/termios.h>
#include "config/conf.h"
#include "net_core.h"
#include "utils/string_arr.h"
Data Structures
struct ping_timer_data
File: hotkeys.h Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
struct monitor_timer_data
Monitor timer data.
struct tr_udp_timer_data
TR UDP timer data.
struct peer_timer_data
Peer timer data.
struct ksnetHotkeysClass
Hot keys class data.
Macros
#define PING_LEN 5
#define TRACE_LEN 6
#define MONITOR_LEN 8
#define TRIPTIME_LEN 9
#define _keys_non_blocking_stop(kh)
Stop keyboard non-blocking mode.
Typedefs
typedef struct ping_timer_data ping_timer_data
File: hotkeys.h Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
typedef struct monitor_timer_data monitor_timer_data
Monitor timer data.
typedef struct tr_udp_timer_data tr_udp_timer_data
TR UDP timer data.
typedef struct peer_timer_data peer_timer_data
Peer timer data.
typedef struct ksnetHotkeysClass ksnetHotkeysClass
Hot keys class data.
Functions
ksnetHotkeysClass * ksnetHotkeysInit (void *ke)
Initialize hot keys module.
void ksnetHotkeysDestroy (ksnetHotkeysClass *kh)
De-initialize hot key module.
unsigned char teoFilterFlagCheck (void *ke)
unsigned char teoLogCheck (void *ke, void *log)
void _keys_non_blocking_start (ksnetHotkeysClass *kh)
Start keyboard non-blocking mode.
Variables
const char * PING
const char * TRACE
const char * MONITOR
const char * TRIPTIME
Macro Definition Documentation
#define _keys_non_blocking_stop (kh)
Value:
tcsetattr(0, TCSANOW, &kh->initial_settings); \
    kh->non_blocking = 0
Stop keyboard non-blocking mode.
Parameters
kh
Examples:
teoackm.c.
Referenced by event_cb(), hotkeys_cb(), and ksnetHotkeysDestroy().
#define MONITOR_LEN 8
Referenced by monitor_timer_one_cb().
#define PING_LEN 5
Referenced by ping_timer_cb().
#define TRACE_LEN 6
Referenced by hotkeys_cb().
#define TRIPTIME_LEN 9
Referenced by check_connected_cb().
Typedef Documentation
typedef struct ksnetHotkeysClass ksnetHotkeysClass
Hot keys class data.
typedef struct monitor_timer_data monitor_timer_data
Monitor timer data.
typedef struct peer_timer_data peer_timer_data
Peer timer data.
typedef struct ping_timer_data ping_timer_data
File: hotkeys.h Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
Created on April 16, 2015, 10:43 PM
Hot keys monitor module Ping timer data
typedef struct tr_udp_timer_data tr_udp_timer_data
TR UDP timer data.
Function Documentation
void _keys_non_blocking_start (ksnetHotkeysClass * kh)
Start keyboard non-blocking mode.
Parameters
kh
References ksnetHotkeysClass::new_settings, and ksnetHotkeysClass::non_blocking.
Referenced by event_cb(), hotkeys_cb(), and ksnetHotkeysInit().
void ksnetHotkeysDestroy (ksnetHotkeysClass * kh)
De-initialize hot key module.
Parameters
kh
References _keys_non_blocking_stop, ksnetEvMgrClass::ev_loop, ksnetHotkeysClass::filter_arr, ke, ksnetHotkeysClass::ke, ksnetEvMgrClass::kh, ksnet_stringArrFree(), and ksnetHotkeysClass::stdin_w.
Referenced by hotkeys_cb(), and modules_destroy().
ksnetHotkeysClass* ksnetHotkeysInit (void * ke)
Initialize hot keys module.
Parameters
ke
Returns
References _keys_non_blocking_start(), ksnetHotkeysClass::filter_arr, ksnetHotkeysClass::filter_f, idle_stdin_cb(), ksnetHotkeysClass::idle_stdin_w, kc, ke, ksnetHotkeysClass::ke, ksnetHotkeysClass::mt, ksnetHotkeysClass::peer_m, peer_timer_init(), ksnetHotkeysClass::pet, ksnetHotkeysClass::pt, ksnetHotkeysClass::put, stdin_cb(), ksnetHotkeysClass::stdin_w, ksnetHotkeysClass::tr_udp_m, ksnetHotkeysClass::tr_udp_queues_m, tr_udp_timer_init(), ksnetHotkeysClass::wait_y, and Y_NONE.
Referenced by modules_init().
unsigned char teoFilterFlagCheck (void * ke)
unsigned char teoLogCheck (void * ke, void * log)
Variable Documentation
const char * MONITOR
Referenced by cmd_reconnect_cb(), and monitor_timer_one_cb().
const char* PING
Referenced by cmd_reconnect_cb(), hotkeys_cb(), and ping_timer_cb().
const char * TRACE
Referenced by hotkeys_cb().
const char * TRIPTIME
Referenced by check_connected_cb(), and cmd_reconnect_cb().