Teonet library: jsmn.c File Reference
jsmn.c File Reference
#include "jsmn.h"
Functions
int jsmn_parse (jsmn_parser *parser, const char *js, size_t len, jsmntok_t *tokens, unsigned int num_tokens)
Parse JSON string and fill tokens.
void jsmn_init (jsmn_parser *parser)
Creates a new parser based over a given buffer with an array of tokens available.
Function Documentation
void jsmn_init (jsmn_parser * parser)
Creates a new parser based over a given buffer with an array of tokens available.
Create JSON parser over an array of tokens.
References jsmn_parser::pos, jsmn_parser::toknext, and jsmn_parser::toksuper.
Referenced by main(), test_array_nomem(), test_count(), test_input_length(), test_issue_22(), test_partial_array(), test_partial_string(), and test_unquoted_keys().
int jsmn_parse (jsmn_parser * parser, const char * js, size_t len, jsmntok_t * tokens, unsigned int num_tokens)
Parse JSON string and fill tokens.
Run JSON parser.
References jsmntok_t::end, JSMN_ARRAY, JSMN_ERROR_INVAL, JSMN_ERROR_NOMEM, JSMN_ERROR_PART, JSMN_OBJECT, JSMN_STRING, jsmn_parser::pos, jsmntok_t::size, jsmntok_t::start, jsmn_parser::toknext, jsmn_parser::toksuper, and jsmntok_t::type.
Referenced by main(), test_array_nomem(), test_count(), test_input_length(), test_issue_22(), test_partial_array(), test_partial_string(), and test_unquoted_keys().