Teonet library: l0-server.h File Reference
l0-server.h File Reference
#include <pbl.h>
#include "subscribe.h"
#include "teonet_l0_client.h"
Data Structures
struct ksnLNullData
File: l0-server.h Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
struct ksnLNullClass
ksnLNull Class structure definition
struct ksnLNullSPacket
L0 Server resend to peer packet data structure.
Typedefs
typedef struct ksnLNullData ksnLNullData
File: l0-server.h Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
typedef struct ksnLNullClass ksnLNullClass
ksnLNull Class structure definition
typedef struct ksnLNullSPacket ksnLNullSPacket
L0 Server resend to peer packet data structure.
Functions
ksnLNullClass * ksnLNullInit (void *ke)
Initialize ksnLNull module class.
void ksnLNullDestroy (ksnLNullClass *kl)
Destroy ksnLNull module class.
int ksnLNullSendToL0 (void *ke, char *addr, int port, char *cname, size_t cname_length, uint8_t cmd, void *data, size_t data_len)
Send data to L0 client.
int ksnLNullSendEchoToL0 (void *ke, char *addr, int port, char *cname, size_t cname_length, void *data, size_t data_len)
Send echo to L0 client.
int ksnLNullSendEchoToL0A (void *ke, char *addr, int port, char *cname, size_t cname_length, void *data, size_t data_len)
int ksnLNullClientIsConnected (ksnLNullClass *kl, char *client_name)
Check if L0 client is connected and return it FD.
teonet_client_data_ar * ksnLNullClientsList (ksnLNullClass *kl)
Create list of clients.
size_t ksnLNullClientsListLength (teonet_client_data_ar *clients_data)
Return size of teonet_client_data_ar data.
ksnLNullSStat * ksnLNullStat (ksnLNullClass *kl)
Get L0 server statistic.
int ksnLNulltrudpCheckPaket (ksnLNullClass *kl, ksnCorePacketData *rd)
Check and process L0 packet received through TR-UDP.
ssize_t ksnLNullPacketSend (ksnLNullClass *kl, int fd, void *pkg, size_t pkg_length)
Send packet to L0 client.
void ksnLNullClientDisconnect (ksnLNullClass *kl, int fd, int remove_f)
Disconnect l0 Server client.
teoLNullEncryptionContext * ksnLNullClientGetCrypto (ksnLNullClass *kl, int fd)
Returns L0 client encryption context and return it if available.
Typedef Documentation
typedef struct ksnLNullClass ksnLNullClass
ksnLNull Class structure definition
typedef struct ksnLNullData ksnLNullData
File: l0-server.h Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
Created on October 8, 2015, 1:39 PM L0 Server map data structure
typedef struct ksnLNullSPacket ksnLNullSPacket
L0 Server resend to peer packet data structure.
Function Documentation
void ksnLNullClientDisconnect (ksnLNullClass * kl, int fd, int remove_f)
Disconnect l0 Server client.
Called when client disconnected or when the L0 Server closing. Close TCP connections and remove data from L0 Server clients map.
Parameters
kl Pointer to ksnLNullClass
fd TCP client connection file descriptor
remove_f If true than remove disconnected record from map
References CONNECT, ev_ksnet_io::data, EV_K_L0_DISCONNECTED, fail, fd, kev, ksn_printf, ksnLNullClass::map, ksnLNullClass::map_n, MODULE, ksnLNullData::name, ksnLNullData::name_length, pblMapRemoveFree(), ksnLNullData::read_buffer, ksnLNullData::read_buffer_ptr, ksnLNullData::read_buffer_size, ksnLNullData::server_crypt, ksnLNullClass::stat, ksnLNullData::t_addr, teoSScrSend(), ksnLNullData::w, and w.
Referenced by _check_connected(), _send_subscribe_event_newvisit(), cmd_l0_check_cb(), ksnLNullDestroy(), recvCheck(), and trudp_event_cb().
teoLNullEncryptionContext* ksnLNullClientGetCrypto (ksnLNullClass * kl, int fd)
Returns L0 client encryption context and return it if available.
Parameters
kl Pointer to ksnLNullClass
fd Client name connection fd
Returns
teoLNullEncryptionContext pointer or null if not available
References ksnLNullData::server_crypt.
int ksnLNullClientIsConnected (ksnLNullClass * kl, char * client_name)
Check if L0 client is connected and return it FD.
Parameters
kl Pointer to ksnLNullClass
client_name Client name
Returns
Connection fd or NULL ifnot connected
References fd, and ksnLNullClass::map_n.
Referenced by _send_subscribe_event_newvisit(), cmd_l0_check_cb(), cmd_l0_to_cb(), and ksnCoreSendCmdto().
teonet_client_data_ar* ksnLNullClientsList (ksnLNullClass * kl)
Create list of clients.
Parameters
kl
Returns
References data, ksnLNullClass::fd, kev, ksnLNullClass::map, and ksnLNullData::name.
Referenced by ksnCommandSendCmdConnectA().
size_t ksnLNullClientsListLength (teonet_client_data_ar * clients_data) inline
Return size of teonet_client_data_ar data.
Parameters
clients_data
Returns
Size of teonet_client_data_ar data
Referenced by ksnCommandSendCmdConnectA().
void ksnLNullDestroy (ksnLNullClass * kl)
Destroy ksnLNull module class.
Parameters
kl Pointer to ksnLNullClass
References _ANSI_NONE, _ANSI_RED, data, DEBUG, DEBUG_VV, ERROR_M, get_byte_checksum(), ksnLNullClass::ke, kev, KSN_BUFFER_DB_SIZE, ksn_printf, ksnetEvMgrGetTime(), ksnLNullClientDisconnect(), ksnLNullData::last_time, ksnLNullClass::map, ksnLNullClass::map_n, MODULE, ksnLNullData::name, ksnLNullData::name_length, ksnLNullData::read_buffer, ksnLNullData::read_buffer_ptr, ksnLNullData::read_buffer_size, ksnLNullData::server_crypt, ksnLNullData::t_addr, ksnLNullData::t_port, teoLNullPacketCheckMiscrypted(), and w.
Referenced by modules_destroy().
ksnLNullClass* ksnLNullInit (void * ke)
Initialize ksnLNull module class.
Parameters
ke Pointer to ksnetEvMgrClass
Returns
Pointer to created ksnLNullClass or NULL if error occurred
References fd, ksnLNullClass::fd_trudp, ksnLNullClass::ke, ke, ksnLNullClass::map, ksnLNullClass::map_n, and ksnLNullClass::stat.
Referenced by modules_init().
ssize_t ksnLNullPacketSend (ksnLNullClass * kl, int fd, void * pkg, size_t pkg_length)
Send packet to L0 client.
Parameters
fd L0 client socket
pkg Package to send
pkg_length Package length
Returns
Length of send data or -1 at error
< Remote address
< Remote address length
References CMD_TRUDP_CHECK, DEBUG_VV, dump_bytes(), fd, ksnLNullClass::ke, kev, ksn_printf, ksnTRUDPsendto(), MODULE, ksnLNullData::server_crypt, ksnLNullClass::stat, ksnLNullData::t_addr, ksnLNullData::t_port, and ksnLNullData::w.
Referenced by _check_connected(), _send_subscribe_event_newvisit(), cmd_l0_check_cb(), cmd_l0_to_cb(), and ksnCoreSendCmdto().
int ksnLNullSendEchoToL0 (void * ke, char * addr, int port, char * cname, size_t cname_length, void * data, size_t data_len)
Send echo to L0 client.
Parameters
ke Pointer to ksnetEvMgrClass
addr IP address of remote peer
port Port of remote peer
cname L0 client name (include trailing zero)
cname_length Length of the L0 client name
data Data
data_len Data length
Returns
Return 0 if success; -1 if data length is too lage (more than 32319)
References CMD_ECHO, kc, ksnCommandEchoBuffer(), and ksnLNullSendToL0().
Referenced by teo::Teonet::sendEchoToL0().
int ksnLNullSendEchoToL0A (void * ke, char * addr, int port, char * cname, size_t cname_length, void * data, size_t data_len)
References ksnCorePacketData::addr, CMD_ECHO, data, ERROR_M, fd, ksnCorePacketData::from, ksnCorePacketData::from_len, kc, ksnLNullClass::ke, kev, ksn_printf, ksnCommandEchoBuffer(), ksnetEvMgrGetTime(), ksnCorePacketData::l0_f, ksnLNullData::last_time, ksnLNullClass::map, MODULE, ksnLNullData::name, ksnLNullData::name_length, ksnCorePacketData::port, rd, ksnLNullData::read_buffer, ksnLNullData::read_buffer_ptr, ksnLNullData::read_buffer_size, sendCmdAnswerToBinaryA(), ksnLNullData::server_crypt, ksnLNullClass::stat, ksnLNullData::t_addr, ksnLNullData::t_channel, and ksnLNullData::t_port.
Referenced by teo::Teonet::sendEchoToL0A().
int ksnLNullSendToL0 (void * ke, char * addr, int port, char * cname, size_t cname_length, uint8_t cmd, void * data, size_t data_len)
Send data to L0 client.
Usually it is an answer to request from L0 client
Parameters
ke Pointer to ksnetEvMgrClass
addr IP address of remote peer
port Port of remote peer
cname L0 client name (include trailing zero)
cname_length Length of the L0 client name
cmd Command
data Data
data_len Data length
Returns
Return 0 if success; -1 if data length is too lage (more than 32319)
References ksnLNullSPacket::cmd, CMD_L0_TO, ksnLNullSPacket::data_length, DEBUG_VV, ksnLNullSPacket::from, ksnLNullSPacket::from_length, kc, ksn_printf, ksnCoreSendto(), and MODULE.
Referenced by ksnCommandSendCmdConnectA(), ksnLNullSendEchoToL0(), sendCmdAnswerToBinaryA(), teo::Teonet::sendToL0(), and teoSScrSend().
ksnLNullSStat* ksnLNullStat (ksnLNullClass * kl)
Get L0 server statistic.
Parameters
kl Pointer to ksnLNullClass
Returns
Pointer to ksnLNullSStat or NULL if L0 server has not started
References ksnLNullSPacket::cmd, CMD_L0, ksnLNullSPacket::data_length, DEBUG, DEBUG_VV, ksnLNullSPacket::from, ksnLNullSPacket::from_length, kev, ksn_printf, ksnCoreCreatePacket(), ksnCoreProcessPacket(), ksnCoreSendCmdto(), ksnetArpGet(), ksnetEvMgrGetHostName(), localhost, make_addr, MODULE, and ksnLNullClass::stat.
Referenced by ksnCommandSendCmdConnectA(), and metric_teonet_count().
int ksnLNulltrudpCheckPaket (ksnLNullClass * kl, ksnCorePacketData * rd)
Check and process L0 packet received through TR-UDP.
Parameters
data
data_len
Returns
References ksnCorePacketData::addr, ksnCorePacketData::data, ksnCorePacketData::data_len, DEBUG_VV, ksnLNullClass::fd, kev, ksn_printf, MODULE, ksnCorePacketData::port, and recvCheck().
Referenced by ksnCoreProcessPacket().