Teonet library: l0-server.c File Reference
l0-server.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>
#include "jsmn.h"
#include "ev_mgr.h"
#include "l0-server.h"
#include "utils/rlutil.h"
#include "teonet_l0_client_crypt.h"
Macros
#define MODULE _ANSI_LIGHTCYAN "l0_server" _ANSI_NONE
File: l0-server.c Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
#define TEO_AUTH "teo-auth"
#define WG001 "wg001-"
#define WG001_NEW "wg001-new-"
#define kev ((ksnetEvMgrClass*)kl->ke)
Pointer to ksnetEvMgrClass.
#define L0_VERSION 0
L0 Server version.
#define CHECK_TIMEOUT 10.00
#define SEND_PING_TIMEOUT 30.00
#define DISCONNECT_TIMEOUT 60.00
#define find_tag(VAR, KEY, TAG)
#define BUFFER_SIZE_CLIENT 4096
Typedefs
typedef struct json_param json_param
JSON request parameters structure.
Functions
void * ksnCoreCreatePacket (ksnCoreClass *kc, uint8_t cmd, const void *data, size_t data_len, size_t *packet_len)
Create ksnet packet.
void teoLNullPacketCheckMiscrypted (ksnLNullClass *kl, ksnLNullData *kld, teoLNullCPacket *packet)
ksnLNullClass * ksnLNullInit (void *ke)
Initialize ksnLNull module class.
void ksnLNullDestroy (ksnLNullClass *kl)
Destroy ksnLNull module class.
ksnLNullSStat * ksnLNullStat (ksnLNullClass *kl)
Get L0 server statistic.
int ksnLNullSendToL0 (void *ke, char *addr, int port, char *cname, size_t cname_length, uint8_t cmd, void *data, size_t data_len)
Send data to L0 client.
int ksnLNullSendEchoToL0 (void *ke, char *addr, int port, char *cname, size_t cname_length, void *data, size_t data_len)
Send echo to L0 client.
int ksnLNullSendEchoToL0A (void *ke, char *addr, int port, char *cname, size_t cname_length, void *data, size_t data_len)
void _send_subscribe_event_disconnected (ksnetEvMgrClass *ke, const char *payload, size_t payload_length)
void _send_subscribe_event_connected (ksnetEvMgrClass *ke, const char *payload, size_t payload_length)
Send Connected event to all subscribers.
void _send_subscribe_event_newvisit (ksnetEvMgrClass *ke, const char *payload, size_t payload_length)
Send "new visit" event to all subscribers.
ssize_t ksnLNullPacketSend (ksnLNullClass *kl, int fd, void *pkg, size_t pkg_length)
Send packet to L0 client.
void ksnLNullClientDisconnect (ksnLNullClass *kl, int fd, int remove_f)
Disconnect l0 Server client.
void _check_connected (uint32_t id, int type, void *data)
int cmd_l0_broadcast_cb (ksnetEvMgrClass *ke, ksnCorePacketData *rd)
Process CMD_L0_CLIENT_BROADCAST teonet command (from peer to l0)
int cmd_l0_cb (ksnetEvMgrClass *ke, ksnCorePacketData *rd)
Process CMD_L0 teonet command.
int ksnLNullClientIsConnected (ksnLNullClass *kl, char *client_name)
Check if L0 client is connected and return it FD.
int cmd_l0_to_cb (ksnetEvMgrClass *ke, ksnCorePacketData *rd)
Process CMD_L0_TO teonet command.
int cmd_l0_check_cb (ksnCommandClass *kco, ksnCorePacketData *rd)
Check l0 client answer from authentication application.
teonet_client_data_ar * ksnLNullClientsList (ksnLNullClass *kl)
Create list of clients.
size_t ksnLNullClientsListLength (teonet_client_data_ar *clients_data)
Return size of teonet_client_data_ar data.
ssize_t recvCheck (trudpChannelData *tcd, char *data, ssize_t data_length)
int ksnLNulltrudpCheckPaket (ksnLNullClass *kl, ksnCorePacketData *rd)
Check and process L0 packet received through TR-UDP.
teoLNullEncryptionContext * ksnLNullClientGetCrypto (ksnLNullClass *kl, int fd)
Returns L0 client encryption context and return it if available.
Variables
const char * localhost
KSNet mesh core module.
Macro Definition Documentation
#define BUFFER_SIZE_CLIENT 4096
Referenced by recvCheck().
#define CHECK_TIMEOUT 10.00
Referenced by _check_connected().
#define DISCONNECT_TIMEOUT 60.00
Referenced by _check_connected().
#define find_tag (VAR, KEY, TAG)
Value:
if(!(keys & KEY) && jsoneq(data, &t[i], TAG) == 0) { \
            \
            VAR = strndup((char*)data + t[i+1].start, \
                    t[i+1].end-t[i+1].start); \
            keys |= KEY; \
            i++; \
        }
#define kev ((ksnetEvMgrClass*)kl->ke)
Pointer to ksnetEvMgrClass.
Referenced by _check_connected(), cmd_l0_check_cb(), ksnLNullClientDisconnect(), ksnLNullClientsList(), ksnLNullPacketSend(), ksnLNulltrudpCheckPaket(), and teoLNullPacketCheckMiscrypted().
#define L0_VERSION 0
L0 Server version.
#define MODULE _ANSI_LIGHTCYAN "l0_server" _ANSI_NONE
File: l0-server.c Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
L0 Server module
Created on October 8, 2015, 1:38 PM
Referenced by _check_connected(), cmd_l0_cb(), cmd_l0_check_cb(), cmd_l0_to_cb(), ksnLNullClientDisconnect(), ksnLNullPacketSend(), ksnLNullSendToL0(), ksnLNulltrudpCheckPaket(), and teoLNullPacketCheckMiscrypted().
#define SEND_PING_TIMEOUT 30.00
Referenced by _check_connected().
#define TEO_AUTH "teo-auth"
Referenced by cmd_l0_check_cb().
#define WG001 "wg001-"
#define WG001_NEW "wg001-new-"
Typedef Documentation
typedef struct json_param json_param
JSON request parameters structure.
userId clientId username accessToken
Function Documentation
void _check_connected (uint32_t id, int type, void * data)
References CHECK_TIMEOUT, CMD_ECHO, ksnLNullClass::cque, data, DEBUG, DISCONNECT_TIMEOUT, ksnLNullClass::ke, kev, ksn_printf, ksnCommandEchoBuffer(), ksnCQueAdd(), ksnetEvMgrGetHostName(), ksnetEvMgrGetTime(), ksnLNullClientDisconnect(), ksnLNullPacketSend(), ksnLNullData::last_time, ksnLNullClass::map, MODULE, ksnLNullData::name, and SEND_PING_TIMEOUT.
void _send_subscribe_event_connected (ksnetEvMgrClass * ke, const char * payload, size_t payload_length)
Send Connected event to all subscribers.
References EV_K_L0_CONNECTED, ksnetEvMgrClass::kc, ksnCoreClass::kco, ksnetEvMgrClass::kl, ksnCommandClass::ksscr, ksnLNullClass::stat, and teoSScrSend().
Referenced by cmd_l0_check_cb().
void _send_subscribe_event_disconnected (ksnetEvMgrClass * ke, const char * payload, size_t payload_length)
References EV_K_L0_DISCONNECTED, ksnetEvMgrClass::kc, ksnCoreClass::kco, ksnCommandClass::ksscr, and teoSScrSend().
Referenced by ksnLNullClientDisconnect().
void _send_subscribe_event_newvisit (ksnetEvMgrClass * ke, const char * payload, size_t payload_length)
Send "new visit" event to all subscribers.
References EV_K_L0_NEW_VISIT, ksnetEvMgrClass::kc, ksnCoreClass::kco, ksnetEvMgrClass::kl, ksnCommandClass::ksscr, ksnLNullClass::stat, and teoSScrSend().
int cmd_l0_broadcast_cb (ksnetEvMgrClass * ke, ksnCorePacketData * rd)
Process CMD_L0_CLIENT_BROADCAST teonet command (from peer to l0)
Parameters
ke Pointer to ksnetEvMgrClass
rd Pointer to ksnCorePacketData data
Returns
If true - than command was processed by this function
References ksnCorePacketData::cmd, ksnCorePacketData::data, ksnCorePacketData::data_len, ksnetEvMgrClass::kl, ksnetEvMgrClass::ksn_cfg, and ksnet_cfg::l0_allow_f.
Referenced by ksnCommandCheck().
int cmd_l0_cb (ksnetEvMgrClass * ke, ksnCorePacketData * rd)
Process CMD_L0 teonet command.
Parameters
ke Pointer to ksnetEvMgrClass
rd Pointer to ksnCorePacketData data
Returns
If true - than command was processed by this function
References ksnLNullSPacket::cmd, ksnCorePacketData::cmd, CMD_192_RESERVED, CMD_ECHO, CMD_ECHO_ANSWER, CMD_ECHO_UNRELIABLE, CMD_ECHO_UNRELIABLE_ANSWER, CMD_GET_NUM_PEERS, CMD_HOST_INFO, CMD_L0_CLIENTS, CMD_L0_CLIENTS_N, CMD_L0_STAT, CMD_LAST, CMD_PEERS, CMD_RESET, CMD_SUBSCRIBE, CMD_SUBSCRIBE_RND, CMD_TRUDP_INFO, CMD_UNSUBSCRIBE, CMD_USER, CMD_USER_NR, ksnCorePacketData::data, ksnCorePacketData::data_len, ksnLNullSPacket::data_length, DEBUG_VV, ksnLNullSPacket::from, ksnCorePacketData::from, ksnCorePacketData::from_len, ksnLNullSPacket::from_length, ksnetEvMgrClass::kc, ksnCoreClass::kco, ksn_printf, ksnCommandCheck(), ksnCorePacketData::l0_f, MODULE, and rd.
Referenced by ksnCommandCheck().
int cmd_l0_check_cb (ksnCommandClass * kco, ksnCorePacketData * rd)
Check l0 client answer from authentication application.
Parameters
kco Pointer to ksnCommandClass
rd Pointer to ksnCorePacketData
Returns
References _send_subscribe_event_connected(), CMD_L0_AUTH, CMD_L0_CLIENT_RESET, CONNECT, DEBUG, ksnLNullClass::ke, ke, kev, ksnetEvMgrClass::kl, ksn_printf, ksnet_formatMessage(), ksnLNullClientDisconnect(), ksnLNullClientIsConnected(), ksnLNullPacketSend(), ksnLNullClass::map, ksnLNullClass::map_n, MODULE, ksnLNullData::name, ksnLNullData::name_length, pblMapRemoveFree(), ksnLNullData::t_addr, and TEO_AUTH.
Referenced by ksnCommandCheck().
int cmd_l0_to_cb (ksnetEvMgrClass * ke, ksnCorePacketData * rd)
Process CMD_L0_TO teonet command.
Parameters
ke Pointer to ksnetEvMgrClass
rd Pointer to ksnCorePacketData data
Returns
If true - than command was processed by this function
References ksnLNullSPacket::cmd, ksnCorePacketData::data, ksnLNullSPacket::data_length, DEBUG_VV, ERROR_M, ksnLNullSPacket::from, ksnCorePacketData::from, ksnCorePacketData::from_len, ksnLNullSPacket::from_length, ksnetEvMgrClass::kl, ksn_printf, ksnLNullClientIsConnected(), ksnLNullPacketSend(), MODULE, and ksnLNullClass::stat.
Referenced by ksnCommandCheck().
void * ksnCoreCreatePacket (ksnCoreClass * kc, uint8_t cmd, const void * data, size_t data_len, size_t * packet_len) inline
Create ksnet packet.
Parameters
kc Pointer to ksnCore Class object
cmd Command ID
data Pointer to data
data_len Data length
[out] packet_len Pointer to packet length
Returns
Pointer to packet. Should be free after use.
References ksnCoreCreatePacketFrom(), ksnCoreClass::name, and ksnCoreClass::name_len.
Referenced by ksnCoreSendto().
void ksnLNullClientDisconnect (ksnLNullClass * kl, int fd, int remove_f)
Disconnect l0 Server client.
Called when client disconnected or when the L0 Server closing. Close TCP connections and remove data from L0 Server clients map.
Parameters
kl Pointer to ksnLNullClass
fd TCP client connection file descriptor
remove_f If true than remove disconnected record from map
References _send_subscribe_event_disconnected(), CONNECT, kev, ksn_printf, ksnLNullClass::map, ksnLNullClass::map_n, MODULE, ksnLNullData::name, ksnLNullData::name_length, pblMapRemoveFree(), ksnLNullData::read_buffer, ksnLNullData::read_buffer_ptr, ksnLNullData::read_buffer_size, ksnLNullData::server_crypt, ksnLNullClass::stat, ksnLNullData::t_addr, and ksnLNullData::w.
Referenced by _check_connected(), cmd_l0_check_cb(), and trudp_event_cb().
teoLNullEncryptionContext* ksnLNullClientGetCrypto (ksnLNullClass * kl, int fd)
Returns L0 client encryption context and return it if available.
Parameters
kl Pointer to ksnLNullClass
fd Client name connection fd
Returns
teoLNullEncryptionContext pointer or null if not available
References ksnLNullData::server_crypt.
int ksnLNullClientIsConnected (ksnLNullClass * kl, char * client_name)
Check if L0 client is connected and return it FD.
Parameters
kl Pointer to ksnLNullClass
client_name Client name
Returns
Connection fd or NULL ifnot connected
References ksnLNullClass::map_n.
Referenced by cmd_l0_check_cb(), cmd_l0_to_cb(), and ksnCoreSendCmdto().
teonet_client_data_ar* ksnLNullClientsList (ksnLNullClass * kl)
Create list of clients.
Parameters
kl
Returns
References ksnLNullClass::fd, kev, ksnLNullClass::map, and ksnLNullData::name.
size_t ksnLNullClientsListLength (teonet_client_data_ar * clients_data) inline
Return size of teonet_client_data_ar data.
Parameters
clients_data
Returns
Size of teonet_client_data_ar data
void ksnLNullDestroy (ksnLNullClass * kl)
Destroy ksnLNull module class.
Parameters
kl Pointer to ksnLNullClass
References ksnLNullClass::map, and ksnLNullClass::map_n.
Referenced by modules_destroy().
ksnLNullClass* ksnLNullInit (void * ke)
Initialize ksnLNull module class.
Parameters
ke Pointer to ksnetEvMgrClass
Returns
Pointer to created ksnLNullClass or NULL if error occurred
References ksnLNullClass::fd_trudp, ksnLNullClass::ke, ke, ksnLNullClass::map, ksnLNullClass::map_n, and ksnLNullClass::stat.
Referenced by modules_init().
ssize_t ksnLNullPacketSend (ksnLNullClass * kl, int fd, void * pkg, size_t pkg_length)
Send packet to L0 client.
Parameters
fd L0 client socket
pkg Package to send
pkg_length Package length
Returns
Length of send data or -1 at error
< Remote address
< Remote address length
References CMD_TRUDP_CHECK, dump_bytes(), ksnLNullClass::ke, kev, ksn_printf, ksnTRUDPsendto(), MODULE, ksnLNullData::server_crypt, ksnLNullClass::stat, ksnLNullData::t_addr, and ksnLNullData::t_port.
Referenced by _check_connected(), cmd_l0_check_cb(), cmd_l0_to_cb(), and ksnCoreSendCmdto().
int ksnLNullSendEchoToL0 (void * ke, char * addr, int port, char * cname, size_t cname_length, void * data, size_t data_len)
Send echo to L0 client.
Parameters
ke Pointer to ksnetEvMgrClass
addr IP address of remote peer
port Port of remote peer
cname L0 client name (include trailing zero)
cname_length Length of the L0 client name
data Data
data_len Data length
Returns
Return 0 if success; -1 if data length is too lage (more than 32319)
References CMD_ECHO, kc, ksnCommandEchoBuffer(), and ksnLNullSendToL0().
Referenced by teo::Teonet::sendEchoToL0().
int ksnLNullSendEchoToL0A (void * ke, char * addr, int port, char * cname, size_t cname_length, void * data, size_t data_len)
References ksnCorePacketData::addr, CMD_ECHO, ksnCorePacketData::from, ksnCorePacketData::from_len, kc, ksnCommandEchoBuffer(), ksnCorePacketData::l0_f, ksnCorePacketData::port, rd, and sendCmdAnswerToBinaryA().
Referenced by teo::Teonet::sendEchoToL0A().
int ksnLNullSendToL0 (void * ke, char * addr, int port, char * cname, size_t cname_length, uint8_t cmd, void * data, size_t data_len)
Send data to L0 client.
Usually it is an answer to request from L0 client
Parameters
ke Pointer to ksnetEvMgrClass
addr IP address of remote peer
port Port of remote peer
cname L0 client name (include trailing zero)
cname_length Length of the L0 client name
cmd Command
data Data
data_len Data length
Returns
Return 0 if success; -1 if data length is too lage (more than 32319)
References ksnLNullSPacket::cmd, CMD_L0_TO, ksnLNullSPacket::data_length, DEBUG_VV, ksnLNullSPacket::from, ksnLNullSPacket::from_length, kc, ksn_printf, ksnCoreSendto(), and MODULE.
Referenced by ksnLNullSendEchoToL0(), sendCmdAnswerToBinaryA(), teo::Teonet::sendToL0(), and teoSScrSend().
ksnLNullSStat* ksnLNullStat (ksnLNullClass * kl)
Get L0 server statistic.
Parameters
kl Pointer to ksnLNullClass
Returns
Pointer to ksnLNullSStat or NULL if L0 server has not started
References ksnLNullClass::stat.
Referenced by metric_teonet_count().
int ksnLNulltrudpCheckPaket (ksnLNullClass * kl, ksnCorePacketData * rd)
Check and process L0 packet received through TR-UDP.
Parameters
data
data_len
Returns
References ksnCorePacketData::addr, ksnCorePacketData::data, ksnCorePacketData::data_len, DEBUG_VV, ksnLNullClass::fd, kev, ksn_printf, MODULE, ksnCorePacketData::port, and recvCheck().
Referenced by ksnCoreProcessPacket().
ssize_t recvCheck (trudpChannelData * tcd, char * data, ssize_t data_length)
References BUFFER_SIZE_CLIENT.
Referenced by ksnLNulltrudpCheckPaket().
void teoLNullPacketCheckMiscrypted (ksnLNullClass * kl, ksnLNullData * kld, teoLNullCPacket * packet)
References _ANSI_LIGHTCYAN, _ANSI_NONE, _ANSI_RED, _ANSI_YELLOW, DEBUG, dump_bytes(), get_byte_checksum(), kev, ksn_printf, MODULE, ksnLNullData::t_addr, and ksnLNullData::t_port.
Variable Documentation
const char* localhost
KSNet mesh core module.