Teonet library: log_reader.c File Reference
log_reader.c File Reference
#include <fcntl.h>
#include <stdlib.h>
#include "ev_mgr.h"
#include "log_reader.h"
Macros
#define MODULE "log_reader"
#define kev ((ksnetEvMgrClass*)(lr->ke))
#define BUFINC 256
#define retstr ((char*)lr->line_buffer)
Functions
teoLogReaderClass * teoLogReaderInit (void *ke)
void teoLogReaderDestroy (teoLogReaderClass *lr)
teoLogReaderWatcher * teoLogReaderOpenCbPP (teoLogReaderClass *lr, const char *name, const char *file_name, teoLogReaderFlag flags, teoLogReaderCallback cb, void *user_data)
teoLogReaderWatcher * teoLogReaderOpenCb (teoLogReaderClass *lr, const char *name, const char *file_name, teoLogReaderFlag flags, teoLogReaderCallback cb)
teoLogReaderWatcher * teoLogReaderOpen (teoLogReaderClass *lr, const char *name, const char *file_name, teoLogReaderFlag flags)
int teoLogReaderClose (teoLogReaderWatcher *wd)
Macro Definition Documentation
#define BUFINC 256
#define kev ((ksnetEvMgrClass*)(lr->ke))
Referenced by teoLogReaderInit(), and teoLogReaderOpenCbPP().
#define MODULE "log_reader"
Referenced by teoLogReaderDestroy(), teoLogReaderInit(), and teoLogReaderOpenCbPP().
#define retstr ((char*)lr->line_buffer)
Function Documentation
int teoLogReaderClose (teoLogReaderWatcher * wd)
References teoLogReaderWatcher::fd, teoLogReaderWatcher::file_name, teoLogReaderClass::ke, teoLogReaderWatcher::lr, teoLogReaderWatcher::name, and teoLogReaderWatcher::w.
Referenced by teo::Teonet::LogReader::close().
void teoLogReaderDestroy (teoLogReaderClass * lr)
References teoLogReaderClass::buffer, DEBUG_VV, teoLogReaderClass::ke, ke, ksn_puts, teoLogReaderClass::line_buffer, and MODULE.
Referenced by modules_destroy().
teoLogReaderClass* teoLogReaderInit (void * ke)
References teoLogReaderClass::buf_size, teoLogReaderClass::buffer, DEBUG_VV, teoLogReaderClass::ke, ke, kev, ksn_puts, teoLogReaderClass::line_buf_size, teoLogReaderClass::line_buffer, and MODULE.
Referenced by modules_init().
teoLogReaderWatcher* teoLogReaderOpen (teoLogReaderClass * lr, const char * name, const char * file_name, teoLogReaderFlag flags) inline
References teoLogReaderOpenCbPP().
teoLogReaderWatcher* teoLogReaderOpenCb (teoLogReaderClass * lr, const char * name, const char * file_name, teoLogReaderFlag flags, teoLogReaderCallback cb) inline
References teoLogReaderOpenCbPP().
teoLogReaderWatcher* teoLogReaderOpenCbPP (teoLogReaderClass * lr, const char * name, const char * file_name, teoLogReaderFlag flags, teoLogReaderCallback cb, void * user_data)
References teoLogReaderWatcher::cb, ERROR_M, fd, teoLogReaderWatcher::fd, teoLogReaderWatcher::file_name, teoLogReaderWatcher::flags, kev, ksn_printf, teoLogReaderWatcher::lr, MODULE, teoLogReaderWatcher::name, READ_FROM_END, teoLogReaderWatcher::user_data, w, and teoLogReaderWatcher::w.
Referenced by teo::Teonet::LogReader::open(), teoLogReaderOpen(), and teoLogReaderOpenCb().