Teonet library: log_reader.h File Reference
log_reader.h File Reference
Data Structures
struct teoLogReaderClass
struct teoLogReaderWatcher
Typedefs
typedef uint32_t teoLogReaderFlag
typedef enum _teoLogReaderFlag _teoLogReaderFlag
typedef struct teoLogReaderClass teoLogReaderClass
typedef struct teoLogReaderWatcher teoLogReaderWatcher
typedef void(* teoLogReaderCallback) (void *data, size_t data_length, teoLogReaderWatcher *wd)
Enumerations
enum _teoLogReaderFlag { READ_FROM_BEGIN, READ_FROM_END = 0b001, SKIP_EMPTY = 0b010 }
Functions
teoLogReaderClass * teoLogReaderInit (void *ke)
void teoLogReaderDestroy (teoLogReaderClass *lr)
teoLogReaderWatcher * teoLogReaderOpen (teoLogReaderClass *lr, const char *name, const char *file_name, teoLogReaderFlag flags)
teoLogReaderWatcher * teoLogReaderOpenCb (teoLogReaderClass *lr, const char *name, const char *file_name, teoLogReaderFlag flags, teoLogReaderCallback cb)
teoLogReaderWatcher * teoLogReaderOpenCbPP (teoLogReaderClass *lr, const char *name, const char *file_name, teoLogReaderFlag flags, teoLogReaderCallback cb, void *user_data)
int teoLogReaderClose (teoLogReaderWatcher *wd)
Typedef Documentation
_teoLogReaderFlag
typedef enum _teoLogReaderFlag _teoLogReaderFlag
teoLogReaderCallback
typedef void(* teoLogReaderCallback) (void *data, size_t data_length, teoLogReaderWatcher *wd)
teoLogReaderClass
typedef struct teoLogReaderClass teoLogReaderClass
teoLogReaderFlag
typedef uint32_t teoLogReaderFlag
teoLogReaderWatcher
typedef struct teoLogReaderWatcher teoLogReaderWatcher
Enumeration Type Documentation
_teoLogReaderFlag
enum _teoLogReaderFlag
Enumerator
READ_FROM_BEGIN
READ_FROM_END
SKIP_EMPTY
Function Documentation
teoLogReaderClose()
int teoLogReaderClose (teoLogReaderWatcher * wd)
References teoLogReaderWatcher::fd, teoLogReaderWatcher::file_name, teoLogReaderClass::ke, teoLogReaderWatcher::lr, teoLogReaderWatcher::name, and teoLogReaderWatcher::w.
Referenced by teo::Teonet::LogReader::close().
teoLogReaderDestroy()
void teoLogReaderDestroy (teoLogReaderClass * lr)
References teoLogReaderClass::buffer, DEBUG_VV, teoLogReaderClass::ke, ke, ksn_puts, teoLogReaderClass::line_buffer, and MODULE.
Referenced by modules_destroy().
teoLogReaderInit()
teoLogReaderClass* teoLogReaderInit (void * ke)
References teoLogReaderClass::buf_size, teoLogReaderClass::buffer, DEBUG_VV, teoLogReaderClass::ke, ke, kev, ksn_puts, teoLogReaderClass::line_buf_size, teoLogReaderClass::line_buffer, and MODULE.
Referenced by modules_init().
teoLogReaderOpen()
teoLogReaderWatcher* teoLogReaderOpen (teoLogReaderClass * lr, const char * name, const char * file_name, teoLogReaderFlag flags) inline
References teoLogReaderOpenCbPP().
teoLogReaderOpenCb()
teoLogReaderWatcher* teoLogReaderOpenCb (teoLogReaderClass * lr, const char * name, const char * file_name, teoLogReaderFlag flags, teoLogReaderCallback cb) inline
References teoLogReaderOpenCbPP().
teoLogReaderOpenCbPP()
teoLogReaderWatcher* teoLogReaderOpenCbPP (teoLogReaderClass * lr, const char * name, const char * file_name, teoLogReaderFlag flags, teoLogReaderCallback cb, void * user_data)
References teoLogReaderWatcher::cb, ERROR_M, fd, teoLogReaderWatcher::fd, teoLogReaderWatcher::file_name, teoLogReaderWatcher::flags, kev, ksn_printf, teoLogReaderWatcher::lr, MODULE, teoLogReaderWatcher::name, teoLogReaderWatcher::user_data, w, and teoLogReaderWatcher::w.
Referenced by teo::Teonet::LogReader::open(), teoLogReaderOpen(), and teoLogReaderOpenCb().