Teonet library: logging_client.c File Reference
logging_client.c File Reference
#include "ev_mgr.h"
#include "logging_client.h"
Macros
#define MODULE "logging_client"
#define kev ((ksnetEvMgrClass*)(ke))
Typedefs
typedef struct
teoLoggingClientSendData teoLoggingClientSendData
Logging servers Maps Foreach user data.
Functions
teoLoggingClientClass * teoLoggingClientInit (void *ke)
Logging client initialize.
void teoLoggingClientDestroy (teoLoggingClientClass *lc)
Logging client destroy and free allocated memory.
void teoLoggingClientSend (void *ke, const char *message)
Send log data to logging servers.
Detailed Description
Author
Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
Teonet logging client module
Created on May 30, 2018, 1:33 PM
Macro Definition Documentation
#define kev ((ksnetEvMgrClass*)(ke))
Referenced by teoLoggingClientInit(), and teoLoggingClientSend().
#define MODULE "logging_client"
Referenced by teoLoggingClientDestroy(), and teoLoggingClientInit().
Typedef Documentation
typedef struct teoLoggingClientSendData teoLoggingClientSendData
Logging servers Maps Foreach user data.
Function Documentation
void teoLoggingClientDestroy (teoLoggingClientClass * lc)
Logging client destroy and free allocated memory.
Parameters
ls Pointer to teoLoggingClientClass
References DEBUG_VV, teoLoggingClientClass::event_cb, ksnetEvMgrClass::event_cb, free(), teoLoggingClientClass::ke, ksn_puts, ksnetEvMgrClass::lc, teoLoggingClientClass::map, and MODULE.
Referenced by modules_destroy().
teoLoggingClientClass* teoLoggingClientInit (void * ke)
Logging client initialize.
Parameters
ke Pointer to ksnetEvMgrClass
Returns
Pointer to teoLoggingClientClass
References DEBUG, DEBUG_VV, teoLoggingClientClass::event_cb, event_cb(), teoLoggingClientClass::ke, ke, kev, ksn_puts, malloc(), teoLoggingClientClass::map, and MODULE.
Referenced by modules_init().
void teoLoggingClientSend (void * ke, const char * message)
Send log data to logging servers.
Parameters
ke Pointer to ksnetEvMgrClass
message Pointer to cstring message
References kev, and ksnetEvMgrAsync().
Referenced by ksnet_printf().