Teonet library: logging_server.c File Reference
logging_server.c File Reference
#include <syslog.h>
#include "ev_mgr.h"
#include "logging_server.h"
#include "modules/teodb_com.h"
Macros
#define MODULE "logging_server"
#define kev ((ksnetEvMgrClass*)(ke))
Typedefs
typedef void(* event_cb_t)(struct ksnetEvMgrClass *ke, ksnetEvMgrEvents event, void *data, size_t data_len, void *user_data)
Functions
signed char teoLoggingServerLogCheck (void *ke, void *log)
teoLoggingServerClass * teoLoggingServerInit (void *ke)
Logging server initialize.
void teoLoggingServerDestroy (teoLoggingServerClass *ls)
Logging server destroy and free allocated memory.
Detailed Description
Author
Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
Teonet logging server module
Created on May 30, 2018, 1:33 PM
Macro Definition Documentation
#define kev ((ksnetEvMgrClass*)(ke))
Referenced by teoLoggingServerInit().
#define MODULE "logging_server"
Referenced by teoLoggingServerDestroy(), and teoLoggingServerInit().
Typedef Documentation
typedef void(* event_cb_t)(struct ksnetEvMgrClass *ke, ksnetEvMgrEvents event, void *data, size_t data_len, void *user_data)
Function Documentation
void teoLoggingServerDestroy (teoLoggingServerClass * ls)
Logging server destroy and free allocated memory.
Parameters
ls Pointer to teoLoggingServerClass
References DEBUG, teoLoggingServerClass::event_cb, ksnetEvMgrClass::event_cb, free(), teoLoggingServerClass::ke, ksn_puts, ksnetEvMgrClass::ls, and MODULE.
Referenced by modules_destroy().
teoLoggingServerClass* teoLoggingServerInit (void * ke)
Logging server initialize.
Parameters
ke Pointer to ksnetEvMgrClass
Returns
Pointer to teoLoggingServerClass
References DEBUG, teoLoggingServerClass::event_cb, ksnetEvMgrClass::event_cb, teoLoggingServerClass::ke, ke, kev, ksn_puts, ksnetEvMgrClass::ls, malloc(), and MODULE.
Referenced by modules_init().
signed char teoLoggingServerLogCheck (void * ke, void * log)