Teonet library: metric.c File Reference
metric.c File Reference
#include "metric.h"
#include "ev_mgr.h"
Macros
#define MODULE "metrics"
File: metric.c Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
Functions
teoMetricClass * teoMetricInit (void *kep)
Initialize Metrics module.
void teoMetricDestroy (teoMetricClass *tm)
Destroy Metrics module.
void teoMetricCounter (teoMetricClass *tm, const char *name, int value)
Send counter teonet metric.
void teoMetricCounterf (teoMetricClass *tm, const char *name, double value)
Send counter teonet metric.
void teoMetricMs (teoMetricClass *tm, const char *name, double value)
Send time(ms) teonet metric.
void teoMetricGauge (teoMetricClass *tm, const char *name, int value)
Send gauge teonet metrics.
void teoMetricGaugef (teoMetricClass *tm, const char *name, double value)
Send gauge teonet metrics.
void metric_teonet_count (teoMetricClass *tm)
Send default teonet metrics.
Macro Definition Documentation
#define MODULE "metrics"
File: metric.c Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
Metrics module
Created on November 28, 2019, 1:38 PM
See Teonet Metrics System description in sh/statsd/README.md
Referenced by teoMetricInit().
Function Documentation
void metric_teonet_count (teoMetricClass * tm)
Send default teonet metrics.
Parameters
tm Pointer to teoMetricClass
References ksnCoreClass::ka, ksnetEvMgrClass::kc, teoMetricClass::ke, ksnetEvMgrClass::kl, ksnetEvMgrClass::ksn_cfg, ksnetArpMetrics(), ksnLNullStat(), ksnet_cfg::statsd_peers_f, teoMetricCounter(), and teoMetricGauge().
Referenced by timer_cb().
void teoMetricCounter (teoMetricClass * tm, const char * name, int value)
Send counter teonet metric.
Parameters
tm Pointer to teoMetricClass
name Metrics name
value Metrics counter value
Referenced by metric_teonet_count(), and teo::Teonet::metricCounter().
void teoMetricCounterf (teoMetricClass * tm, const char * name, double value)
Send counter teonet metric.
Parameters
tm Pointer to teoMetricClass
name Metrics name
value Metrics counter value
Referenced by teo::Teonet::metricCounter().
void teoMetricDestroy (teoMetricClass * tm)
Destroy Metrics module.
Parameters
tm Pointer to teoMetricClass
Referenced by modules_destroy().
void teoMetricGauge (teoMetricClass * tm, const char * name, int value)
Send gauge teonet metrics.
Parameters
tm Pointer to teoMetricClass
name Metrics name
value Metrics gauge value
Referenced by cmd_disconnected_cb(), metric_teonet_count(), and teo::Teonet::metricGauge().
void teoMetricGaugef (teoMetricClass * tm, const char * name, double value)
Send gauge teonet metrics.
Parameters
tm Pointer to teoMetricClass
name Metrics name
value Metrics gauge value
Referenced by ksnetArpMetrics(), and teo::Teonet::metricGauge().
teoMetricClass* teoMetricInit (void * kep)
Initialize Metrics module.
Parameters
kep Pointer to ksnetEvMgrClass
References teoMetricClass::ke, ke, ksnetEvMgrClass::ksn_cfg, ksn_printf, MESSAGE, MODULE, ksnet_cfg::statsd_ip, ksnet_cfg::statsd_port, and teoMetricClass::to.
Referenced by modules_init().
void teoMetricMs (teoMetricClass * tm, const char * name, double value)
Send time(ms) teonet metric.
Parameters
tm Pointer to teoMetricClass
name Metrics name
value Metrics ms value
Referenced by teo::Teonet::metricMs().