Teonet library: metric.h File Reference
metric.h File Reference
#include <netinet/in.h>
Data Structures
struct teoMetricClass
Typedefs
typedef struct teoMetricClass teoMetricClass
Functions
teoMetricClass * teoMetricInit (void *ke)
Initialize Metrics module.
void teoMetricDestroy (teoMetricClass *tm)
Destroy Metrics module.
void teoMetricCounter (teoMetricClass *tm, const char *name, int value)
Send counter teonet metric.
void teoMetricCounterf (teoMetricClass *tm, const char *name, double value)
Send counter teonet metric.
void teoMetricMs (teoMetricClass *tm, const char *name, double value)
Send time(ms) teonet metric.
void teoMetricGauge (teoMetricClass *tm, const char *name, int value)
Send gauge teonet metrics.
void teoMetricGaugef (teoMetricClass *tm, const char *name, double value)
Send gauge teonet metrics.
Typedef Documentation
teoMetricClass
typedef struct teoMetricClass teoMetricClass
Function Documentation
teoMetricCounter()
void teoMetricCounter (teoMetricClass * tm, const char * name, int value)
Send counter teonet metric.
Parameters
tm Pointer to teoMetricClass
name Metrics name
value Metrics counter value
Referenced by metric_teonet_count(), and teo::Teonet::metricCounter().
teoMetricCounterf()
void teoMetricCounterf (teoMetricClass * tm, const char * name, double value)
Send counter teonet metric.
Parameters
tm Pointer to teoMetricClass
name Metrics name
value Metrics counter value
Referenced by teo::Teonet::metricCounter().
teoMetricDestroy()
void teoMetricDestroy (teoMetricClass * tm)
Destroy Metrics module.
Parameters
tm Pointer to teoMetricClass
Referenced by modules_destroy().
teoMetricGauge()
void teoMetricGauge (teoMetricClass * tm, const char * name, int value)
Send gauge teonet metrics.
Parameters
tm Pointer to teoMetricClass
name Metrics name
value Metrics gauge value
Referenced by cmd_disconnected_cb(), metric_teonet_count(), and teo::Teonet::metricGauge().
teoMetricGaugef()
void teoMetricGaugef (teoMetricClass * tm, const char * name, double value)
Send gauge teonet metrics.
Parameters
tm Pointer to teoMetricClass
name Metrics name
value Metrics gauge value
Referenced by ksnetArpMetrics(), and teo::Teonet::metricGauge().
teoMetricInit()
teoMetricClass* teoMetricInit (void * kep)
Initialize Metrics module.
Parameters
kep Pointer to ksnetEvMgrClass
References teoMetricClass::ke, ke, ksn_printf, MESSAGE, MODULE, and teoMetricClass::to.
Referenced by modules_init().
teoMetricMs()
void teoMetricMs (teoMetricClass * tm, const char * name, double value)
Send time(ms) teonet metric.
Parameters
tm Pointer to teoMetricClass
name Metrics name
value Metrics ms value
Referenced by teo::Teonet::metricMs().