Teonet library: modules.c File Reference
modules.c File Reference
#include <stdlib.h>
#include "ev_mgr.h"
#include "modules.h"
Functions
void ksnModuleLInit (ksnModulesClass *km)
File: modules.c Author: Kirill Scherba.
void ksnModuleLDestroy (ksnModulesClass *km)
Destroy modules list.
void ksnModulesLAdd (ksnModulesClass *km, ksnModuleElement *modules, int numer_of_elements)
Appends the specified element to the end of this list.
ksnModulesClass * ksnModulesInit (void *ke, ksnModuleElement *modules, int numer_of_modules)
Initialize module.
void ksnModulesDestroy (ksnModulesClass *km)
Destroy module.
Function Documentation
ksnModuleLDestroy()
void ksnModuleLDestroy (ksnModulesClass * km)
Destroy modules list.
References ksnModuleElement::destroy, ksnModulesClass::list, ksnModuleElement::mc, and ksnModulesClass::modules.
Referenced by ksnModulesDestroy().
ksnModuleLInit()
void ksnModuleLInit (ksnModulesClass * km)
File: modules.c Author: Kirill Scherba.
Initialize modules list.
Created on July 3, 2015, 12:25 PM
References ksnModulesClass::list.
Referenced by ksnModulesInit().
ksnModulesDestroy()
void ksnModulesDestroy (ksnModulesClass * km)
Destroy module.
Parameters
km
References ksnModulesClass::ke, ke, and ksnModuleLDestroy().
ksnModulesInit()
ksnModulesClass* ksnModulesInit (void * ke, ksnModuleElement * modules, int numer_of_modules)
Initialize module.
Parameters
ke Pointer to ksnetEvMgrClass
modules
numer_of_modules
Returns
Pointer to ksnModulesClass
References ksnModulesClass::ke, ke, ksnModuleLInit(), ksnModulesLAdd(), and ksnModulesClass::modules.
ksnModulesLAdd()
void ksnModulesLAdd (ksnModulesClass * km, ksnModuleElement * elements, int numer_of_elements)
Appends the specified element to the end of this list.
References ksnModuleElement::init, ksnModulesClass::ke, ksnModulesClass::list, and ksnModuleElement::mc.
Referenced by ksnModulesInit().