Teonet library: modules.h File Reference
modules.h File Reference
#include "config/conf.h"
Data Structures
struct ksnModuleElement
File: modules.h Author: Kirill Scherba.
struct ksnModulesClass
Modules class data.
Typedefs
typedef struct ksnModuleElement ksnModuleElement
File: modules.h Author: Kirill Scherba.
typedef struct ksnModulesClass ksnModulesClass
Modules class data.
Functions
ksnModulesClass * ksnModulesInit (void *ke, ksnModuleElement *modules, int numer_of_modules)
Initialize module.
void ksnModulesDestroy (ksnModulesClass *km)
Destroy module.
Typedef Documentation
ksnModuleElement
typedef struct ksnModuleElement ksnModuleElement
File: modules.h Author: Kirill Scherba.
Created on July 3, 2015, 12:25 PM Module Element structure
ksnModulesClass
typedef struct ksnModulesClass ksnModulesClass
Modules class data.
Function Documentation
ksnModulesDestroy()
void ksnModulesDestroy (ksnModulesClass * km)
Destroy module.
Parameters
km
References ksnModulesClass::ke, ke, and ksnModuleLDestroy().
ksnModulesInit()
ksnModulesClass* ksnModulesInit (void * ke, ksnModuleElement * modules, int numer_of_modules)
Initialize module.
Parameters
ke Pointer to ksnetEvMgrClass
modules
numer_of_modules
Returns
Pointer to ksnModulesClass
References ksnModulesClass::ke, ke, ksnModuleLInit(), ksnModulesLAdd(), and ksnModulesClass::modules.