Teonet library: net_split.h File Reference
net_split.h File Reference
#include "ev_mgr.h"
Data Structures
struct ksnSplitClass
KSNet split class data.
Macros
#define MAX_DATA_LEN 448
File: net_split.h Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
#define MAX_PACKET_LEN 0x7FFFF * 2
#define LAST_PACKET_FLAG 0x8000
Typedefs
typedef struct ksnSplitClass ksnSplitClass
KSNet split class data.
Functions
ksnSplitClass * ksnSplitInit (ksnCommandClass *kc)
Initialize split module.
void ksnSplitDestroy (ksnSplitClass *ks)
Destroy split module.
void ** ksnSplitPacket (ksnSplitClass *ks, uint8_t cmd, void *packet, size_t packet_len, int *num_subpackets)
Split large packet to array of small.
ksnCorePacketData * ksnSplitCombine (ksnSplitClass *ks, ksnCorePacketData *rd)
Combine packets to one large packet.
void ksnSplitFreeRds (ksnSplitClass *ks, ksnCorePacketData *rd)
Free ksnCorePacketData created in ksnSplitCombine function.
Macro Definition Documentation
LAST_PACKET_FLAG
#define LAST_PACKET_FLAG 0x8000
MAX_DATA_LEN
#define MAX_DATA_LEN 448
File: net_split.h Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
Created on July 17, 2015, 10:20 AM
Module to split large packets when send and combine it when receive.
MAX_PACKET_LEN
#define MAX_PACKET_LEN 0x7FFFF * 2
Typedef Documentation
ksnSplitClass
typedef struct ksnSplitClass ksnSplitClass
KSNet split class data.
Function Documentation
ksnSplitCombine()
ksnCorePacketData* ksnSplitCombine (ksnSplitClass * ks, ksnCorePacketData * rd)
Combine packets to one large packet.
Parameters
ks Pointer to ksnSplitClass
rd Pointer to ksnCorePacketData
Returns
Pointer to combined packet ksnCorePacketData or NULL if not combined or error
References ksnCorePacketData::addr, ksnCorePacketData::arp, ksnCorePacketData::cmd, create_key, data, ksnCorePacketData::data, ksnCorePacketData::data_len, ksnSplitClass::data_save, DEBUG_VV, ERROR_M, ksnCorePacketData::from, ksnCorePacketData::from_len, kev, ksn_printf, ksn_puts, ksnetEvMgrGetTime(), ksnSplitClass::last_added, LAST_PACKET_FLAG, ksnSplitClass::map, MAX_DATA_LEN, MODULE, ksnCorePacketData::mtu, pblMapRemoveFree(), ksnCorePacketData::port, ksnCorePacketData::raw_data, ksnCorePacketData::raw_data_len, rd, teo_calloc(), and teo_realloc().
ksnSplitDestroy()
void ksnSplitDestroy (ksnSplitClass * ks)
Destroy split module.
Parameters
ks
References ksnSplitClass::map.
Referenced by ksnCommandDestroy().
ksnSplitFreeRds()
void ksnSplitFreeRds (ksnSplitClass * ks, ksnCorePacketData * rd)
Free ksnCorePacketData created in ksnSplitCombine function.
Parameters
ks
rd
References ksnSplitClass::data_save, and rd.
ksnSplitInit()
ksnSplitClass* ksnSplitInit (ksnCommandClass * kco)
Initialize split module.
Parameters
kco
Returns
References ksnSplitClass::kco, ksnSplitClass::last_added, ksnSplitClass::map, ksnSplitClass::packet_number, and teo_malloc().
Referenced by ksnCommandInit().
ksnSplitPacket()
void** ksnSplitPacket (ksnSplitClass * ks, uint8_t cmd, void * packet, size_t packet_len, int * num_subpackets)
Split large packet to array of small.
Parameters
ks
cmd
packet
packet_len
num_subpackets
Returns
References DEBUG_VV, kev, ksn_printf, MAX_DATA_LEN, MODULE, and ksnSplitClass::packet_number.
Referenced by ksnCoreSendto().