Teonet library: net_multi.h File Reference
net_multi.h File Reference
#include "ev_mgr.h"
Data Structures
struct ksnMultiClass
File: net_multi.h Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
struct ksnMultiData
ksnMultiClass initialize input data
Macros
#define ksnMultiGet(X, Y)
Typedefs
typedef struct ksnMultiClass ksnMultiClass
File: net_multi.h Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
typedef struct ksnMultiData ksnMultiData
ksnMultiClass initialize input data
Functions
ksnMultiClass * ksnMultiInit (ksnMultiData *md, void *user_data)
Initialize ksnMultiClass object.
void teoMultiRun (ksnMultiClass *km)
Start teonet event loop (for all functions added with ksnMultiInit)
void ksnMultiDestroy (ksnMultiClass *km)
Destroy ksnMultiClass object and running networks.
void teoMultiAddNet (ksnMultiClass *km, ksn_event_cb_type e_cb, const char *host, int port, const char *network, void *user_data)
Add new network.
void teoMultiRemoveNet (ksnMultiClass *km, const char *network)
Remove network.
ksnetEvMgrClass * teoMultiGetByNumber (ksnMultiClass *km, int number)
Get network by number.
ksnetEvMgrClass * teoMultiGetByNetwork (ksnMultiClass *km, char *network_name)
Get network by network name.
bool teoMultiIsNetworkExist (ksnMultiClass *km, int number)
Check if network with input number is exist.
char * ksnMultiShowListStr (ksnMultiClass *km)
Show list of networks.
ksnet_arp_data * teoMultiSendCmdToNet (ksnMultiClass *km, char *peer, char *network, uint8_t cmd, void *data, size_t data_len)
Send command by name (or type) and by network.
ksnet_arp_data * ksnMultiSendCmdTo (ksnMultiClass *km, char *to, uint8_t cmd, void *data, size_t data_len)
: It will be new function for broadcast sending Send command by name to peer
Macro Definition Documentation
#define ksnMultiGet (X, Y)
Value:
_Generic((Y), \
      int : teoMultiGetByNumber, \
      char* : teoMultiGetByNetwork) \
      ((X), (Y))
Referenced by hotkeys_cb().
Typedef Documentation
typedef struct ksnMultiClass ksnMultiClass
File: net_multi.h Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
Created on July 23, 2015, 11:46 AM ksnMultiClass module data
typedef struct ksnMultiData ksnMultiData
ksnMultiClass initialize input data
Function Documentation
void ksnMultiDestroy (ksnMultiClass * km)
Destroy ksnMultiClass object and running networks.
Parameters
km Pointer to ksnMultiClass
References ksnetEvMgrFree(), ksnetEvMgrRestart(), ksnetEvMgrStop(), ksnMultiClass::last_net_idx, ksnMultiClass::list, and teoMultiGetByNumber().
Referenced by main(), and sigusr2_cb().
ksnMultiClass* ksnMultiInit (ksnMultiData * md, void * user_data)
Initialize ksnMultiClass object.
Parameters
md Pointer to initialize input data
user_data Pointer to user data added to every teonet network
Returns
Pointer to ksnMultiClass
References ksnMultiData::argc, ksnMultiData::argv, ksnMultiData::event_cb, ksnet_cfg::host_name, ke, ksnetEvMgrClass::km, KSN_BUFFER_SM_SIZE, ksnetEvMgrClass::ksn_cfg, KSN_MAX_HOST_NAME, ksnetEvMgrInitPort(), ksnetEvMgrRun(), ksnMultiClass::last_net_idx, ksnMultiClass::list, ksnMultiData::names, ksnMultiClass::net_count, ksnetEvMgrClass::net_count, ksnetEvMgrClass::net_idx, ksnet_cfg::network, ksnMultiData::networks, ksnMultiData::num, ksnet_cfg::port, ksnMultiData::ports, read_config(), READ_CONFIGURATION, READ_OPTIONS, and teo_malloc().
Referenced by main().
ksnet_arp_data* ksnMultiSendCmdTo (ksnMultiClass * km, char * to, uint8_t cmd, void * data, size_t data_len)
: It will be new function for broadcast sending Send command by name to peer
Parameters
km Pointer to ksnMultiClass
to Recipient peer name
cmd Command
data Command data
data_len Data length
Returns
Pointer to ksnet_arp_data or NULL if not found
Referenced by ksnCoreSendCmdto().
char* ksnMultiShowListStr (ksnMultiClass * km)
Show list of networks.
Parameters
km Pointer to ksnMultiClass
Returns
Pointer to string, should be free after use
References add_line, ke, ksnet_formatMessage(), ksnet_sformatMessage(), LIGHTCYAN, LIGHTGREEN, ksnMultiClass::list, and NONE.
Referenced by hotkeys_cb().
void teoMultiAddNet (ksnMultiClass * km, ksn_event_cb_type e_cb, const char * host, int port, const char * network, void * user_data)
Add new network.
Parameters
km Pointer to ksnMultiClass
event_cb Teonet event callback
host Host name
port Port number
network Network name
user_data Pointer to user data added to this teonet network
References ksnetEvMgrClass::argc, ksnetEvMgrClass::argv, ksnet_cfg::host_name, ksnetEvMgrClass::km, KSN_BUFFER_SM_SIZE, ksnetEvMgrClass::ksn_cfg, KSN_MAX_HOST_NAME, ksnetEvMgrInitPort(), ksnetEvMgrRun(), ksnMultiClass::last_net_idx, ksnMultiClass::list, ksnMultiClass::net_count, ksnetEvMgrClass::net_count, ksnetEvMgrClass::net_idx, ksnet_cfg::network, ksnet_cfg::port, read_config(), READ_CONFIGURATION, READ_OPTIONS, and teoMultiGetByNumber().
Referenced by event_cb().
ksnetEvMgrClass* teoMultiGetByNetwork (ksnMultiClass * km, char * network_name)
Get network by network name.
Parameters
km Pointer to ksnMultiClass
network_name Network name
Returns
Pointer to ksnetEvMgrClass or NULL if not found
References ke, and ksnMultiClass::list.
ksnetEvMgrClass* teoMultiGetByNumber (ksnMultiClass * km, int number)
Get network by number.
Parameters
km Pointer to ksnMultiClass
num Number of network
Returns
Pointer to ksnetEvMgrClass
References ke, and ksnMultiClass::list.
Referenced by ksnMultiDestroy(), teoMultiAddNet(), and teoMultiRun().
bool teoMultiIsNetworkExist (ksnMultiClass * km, int number)
Check if network with input number is exist.
Parameters
km Pointer to ksnMultiClass
num Number of network
Returns
true if network with input number is exist
References ke, and ksnMultiClass::list.
Referenced by hotkeys_cb().
void teoMultiRemoveNet (ksnMultiClass * km, const char * network)
Remove network.
Parameters
km Pointer to ksnMultiClass
network Network name
References ke, ksnetEvMgrFree(), ksnetEvMgrStop(), ksnMultiClass::list, and ksnMultiClass::net_count.
void teoMultiRun (ksnMultiClass * km)
Start teonet event loop (for all functions added with ksnMultiInit)
Parameters
km Pointer to ksnMultiClass
References ksnetEvMgrClass::ev_loop, ksnMultiClass::last_net_idx, and teoMultiGetByNumber().
Referenced by main().
ksnet_arp_data* teoMultiSendCmdToNet (ksnMultiClass * km, char * peer, char * network, uint8_t cmd, void * data, size_t data_len)
Send command by name (or type) and by network.
Parameters
km Pointer to ksnMultiClass
peer Peer name
network Network name
cmd Command ID
data Pointer to data
data_len Data length
Returns
Pointer to ksnet_arp_data or NULL if network not found or peer not found in arp table of selected network
References ke, ksnCoreSendCmdto(), and ksnMultiClass::list.