Teonet library: net_com.c File Reference
net_com.c File Reference
#include <stdlib.h>
#include <string.h>
#include "ev_mgr.h"
#include "net_split.h"
#include "net_recon.h"
#include "utils/rlutil.h"
#include "utils/teo_memory.h"
#include "modules/subscribe.h"
#include "trudp_stat.h"
Macros
#define MODULE _ANSI_LIGHTBLUE "net_command" _ANSI_NONE
Typedefs
typedef struct cmd_connect_cque_cb_data cmd_connect_cque_cb_data
Functions
int cmd_stream_cb (ksnStreamClass *ks, ksnCorePacketData *rd)
Process CMD_STREAM teonet command.
int cmd_l0_cb (ksnetEvMgrClass *ke, ksnCorePacketData *rd)
Process CMD_L0 teonet command.
int cmd_l0_to_cb (ksnetEvMgrClass *ke, ksnCorePacketData *rd)
Process CMD_L0_TO teonet command.
int cmd_l0_broadcast_cb (ksnetEvMgrClass *ke, ksnCorePacketData *rd)
Process CMD_L0_CLIENT_BROADCAST teonet command (from peer to l0)
int cmd_reconnect_cb (ksnCommandClass *kco, ksnCorePacketData *rd)
Process CMD_RECONNECT command.
int cmd_subscribe_cb (ksnCommandClass *kco, ksnCorePacketData *rd)
Process CMD_SUBSCRIBE, CMD_UNSUBSCRIBE and CMD_SUBSCRIBE_ANSWER commands.
int cmd_l0_check_cb (ksnCommandClass *kco, ksnCorePacketData *rd)
Check l0 client answer from authentication application.
ksnCommandClass * ksnCommandInit (void *kc)
Initialize ksnet command class.
void ksnCommandDestroy (ksnCommandClass *kco)
Destroy ksnet command class.
int ksnCommandCheck (ksnCommandClass *kco, ksnCorePacketData *rd)
Check and process command.
void * ksnCommandEchoBuffer (ksnCommandClass *kco, void *data, size_t data_len, size_t *data_t_len)
Create ECHO command buffer.
int ksnCommandSendCmdEcho (ksnCommandClass *kco, char *to, void *data, size_t data_len)
Send ECHO command to peer.
void fillConnectData (char *data, size_t *ptr, char *name, char *addr, uint32_t port)
int ksnCommandSendCmdConnect (ksnCommandClass *kco, char *to, char *name, char *addr, uint32_t port)
Send CONNECTED command to peer.
int ksnCommandSendCmdConnectA (ksnCommandClass *kco, char *to_addr, uint32_t to_port, char *name, char *addr, uint32_t port)
Send CONNECTED command to peer by address.
int send_cmd_connect_cb (ksnetArpClass *ka, char *peer_name, ksnet_arp_data_ext *arp, void *data)
Send connect command.
int send_cmd_connect_cb_b (ksnetArpClass *ka, char *peer_name, ksnet_arp_data_ext *arp, void *data)
Send connect command.
int cmd_disconnected_cb (ksnCommandClass *kco, ksnCorePacketData *rd)
Process CMD_DISCONNECTED command.
Variables
const char * JSON = "JSON"
const char * BINARY = "BINARY"
Macro Definition Documentation
#define MODULE _ANSI_LIGHTBLUE "net_command" _ANSI_NONE
Referenced by cmd_disconnected_cb(), cmd_reconnect_cb(), ksnCommandSendCmdConnect(), ksnCommandSendCmdConnectA(), and send_cmd_connect_cb_b().
Typedef Documentation
typedef struct cmd_connect_cque_cb_data cmd_connect_cque_cb_data
Function Documentation
int cmd_disconnected_cb (ksnCommandClass * kco, ksnCorePacketData * rd)
Process CMD_DISCONNECTED command.
A peer send disconnect command
Parameters
kco Pointer to ksnCommandClass
rd Pointer to ksnCorePacketData
Returns
True if command is processed
References ksnCorePacketData::addr, ARP_TABLE_CLASS, ksnCorePacketData::cmd, ksnCorePacketData::data, DEBUG_VV, EV_K_DISCONNECTED, EV_K_RECEIVED, ksnetEvMgrClass::event_cb, EVENT_MANAGER_CLASS, ksnCorePacketData::from, ksnCorePacketData::from_len, ke, ksnCommandClass::kr, ksnCommandClass::ks, ksnetEvMgrClass::ksn_cfg, ksn_printf, ksnCommandCheck(), ksnet_formatMessage(), ksnetArpRemove(), ksnSplitCombine(), ksnSplitFreeRds(), ksnCommandClass::ksscr, MODULE, ksnCorePacketData::port, ksnet_cfg::r_host_name, teoMetricGauge(), teoSScrSend(), and ksnetEvMgrClass::tm.
Referenced by ksnCommandCheck(), and open_local_port().
int cmd_l0_broadcast_cb (ksnetEvMgrClass * ke, ksnCorePacketData * rd)
Process CMD_L0_CLIENT_BROADCAST teonet command (from peer to l0)
Parameters
ke Pointer to ksnetEvMgrClass
rd Pointer to ksnCorePacketData data
Returns
If true - than command was processed by this function
References ksnCorePacketData::cmd, ksnCorePacketData::data, ksnCorePacketData::data_len, ksnetEvMgrClass::kl, ksnetEvMgrClass::ksn_cfg, and ksnet_cfg::l0_allow_f.
Referenced by ksnCommandCheck().
int cmd_l0_cb (ksnetEvMgrClass * ke, ksnCorePacketData * rd)
Process CMD_L0 teonet command.
Parameters
ke Pointer to ksnetEvMgrClass
rd Pointer to ksnCorePacketData data
Returns
If true - than command was processed by this function
References ksnLNullSPacket::cmd, ksnCorePacketData::cmd, CMD_192_RESERVED, CMD_ECHO, CMD_ECHO_ANSWER, CMD_ECHO_UNRELIABLE, CMD_ECHO_UNRELIABLE_ANSWER, CMD_GET_NUM_PEERS, CMD_HOST_INFO, CMD_L0_CLIENTS, CMD_L0_CLIENTS_N, CMD_L0_STAT, CMD_LAST, CMD_PEERS, CMD_RESET, CMD_SUBSCRIBE, CMD_SUBSCRIBE_RND, CMD_TRUDP_INFO, CMD_UNSUBSCRIBE, CMD_USER, CMD_USER_NR, data, ksnCorePacketData::data, ksnCorePacketData::data_len, ksnLNullSPacket::data_length, DEBUG_VV, ksnLNullSPacket::from, ksnCorePacketData::from, ksnCorePacketData::from_len, ksnLNullSPacket::from_length, ksnetEvMgrClass::kc, ksnCoreClass::kco, ksn_printf, ksnCommandCheck(), ksnCorePacketData::l0_f, MODULE, and rd.
Referenced by ksnCommandCheck().
int cmd_l0_check_cb (ksnCommandClass * kco, ksnCorePacketData * rd)
Check l0 client answer from authentication application.
Parameters
kco Pointer to ksnCommandClass
rd Pointer to ksnCorePacketData
Returns
References _send_subscribe_event_connected(), CMD_L0_AUTH, CMD_L0_CLIENT_RESET, CONNECT, ksnCorePacketData::data, ksnCorePacketData::data_len, DEBUG, fd, ksnCorePacketData::from, ksnCorePacketData::from_len, ksnCommandClass::kc, ksnLNullClass::ke, ke, kev, ksnetEvMgrClass::kl, ksn_printf, ksnet_formatMessage(), ksnLNullClientDisconnect(), ksnLNullClientIsConnected(), ksnLNullPacketSend(), ksnLNullClass::map, ksnLNullClass::map_n, MODULE, ksnLNullData::name, ksnLNullData::name_length, pblMapRemoveFree(), ksnLNullData::t_addr, and TEO_AUTH.
Referenced by ksnCommandCheck().
int cmd_l0_to_cb (ksnetEvMgrClass * ke, ksnCorePacketData * rd)
Process CMD_L0_TO teonet command.
Parameters
ke Pointer to ksnetEvMgrClass
rd Pointer to ksnCorePacketData data
Returns
If true - than command was processed by this function
References ksnLNullSPacket::cmd, data, ksnCorePacketData::data, ksnLNullSPacket::data_length, DEBUG_VV, jsmntok_t::end, ERROR_M, fd, find_tag, ksnLNullSPacket::from, ksnCorePacketData::from, ksnCorePacketData::from_len, ksnLNullSPacket::from_length, get_num_of_tags(), jsmn_init(), JSMN_OBJECT, jsmn_parse(), ksnetEvMgrClass::kl, ksn_printf, ksnLNullClientIsConnected(), ksnLNullPacketSend(), MODULE, jsmntok_t::start, and ksnLNullClass::stat.
Referenced by ksnCommandCheck().
int cmd_reconnect_cb (ksnCommandClass * kco, ksnCorePacketData * rd) inline
Process CMD_RECONNECT command.
Parameters
kco Pointer to ksnCommandClass
rd Pointer to ksnCorePacketData
Returns
True if command is processed
References ksnCorePacketData::addr, ksnCorePacketData::arp, ARP_TABLE_CLASS, ksnCorePacketData::cmd, ksnCorePacketData::data, ksnCorePacketData::data_len, DEBUG_VV, DISPLAY_M, EVENT_MANAGER_CLASS, ksnCorePacketData::from, ke, ksnCommandClass::kr, ksnetEvMgrClass::ksn_cfg, ksn_printf, ksnet_printf(), ksnetArpAdd(), ksnetArpGet(), ksnetEvMgrGetTime(), MODULE, MONITOR, PING, ksnCorePacketData::port, and TRIPTIME.
Referenced by ksnCommandCheck().
int cmd_stream_cb (ksnStreamClass * ks, ksnCorePacketData * rd)
Process CMD_STREAM teonet command.
Parameters
ks
rd
Returns
References stream_packet::cmd, CMD_ST_CLOSE, CMD_ST_CLOSE_GOT, CMD_ST_CREATE, CMD_ST_CREATE_GOT, CMD_ST_CREATED, CMD_ST_DATA, data, stream_packet::data, ksnCorePacketData::data, stream_packet::data_len, DEBUG_VV, ksnCorePacketData::from, kev, ksn_printf, ksnStreamClose(), ksnStreamCreate(), ksnStreamClass::map, MODULE, ksnStreamMapData::pipe_in, and stream_packet::stream_name_len.
Referenced by ksnCommandCheck().
int cmd_subscribe_cb (ksnCommandClass * kco, ksnCorePacketData * rd)
Process CMD_SUBSCRIBE, CMD_UNSUBSCRIBE and CMD_SUBSCRIBE_ANSWER commands.
Parameters
kco Pointer to ksnCommandClass
rd Pointer to ksnCorePacketData
Returns
True if command is processed
References ksnCorePacketData::arp, ksnCorePacketData::cmd, CMD_SUBSCRIBE, CMD_SUBSCRIBE_ANSWER, CMD_SUBSCRIBE_RND, CMD_UNSUBSCRIBE, ksnCorePacketData::data, ksnCorePacketData::data_len, EV_K_SUBSCRIBE, EV_K_SUBSCRIBED, ksnCorePacketData::from, kev, ksnCommandClass::ksscr, ksnCorePacketData::l0_f, teoSScrSubscription(), and teoSScrUnSubscription().
Referenced by ksnCommandCheck().
void fillConnectData (char * data, size_t * ptr, char * name, char * addr, uint32_t port)
References KSN_BUFFER_DB_SIZE.
Referenced by ksnCommandSendCmdConnect(), and ksnCommandSendCmdConnectA().
int ksnCommandCheck (ksnCommandClass * kco, ksnCorePacketData * rd)
Check and process command.
Returns
True if command processed
References ksnCorePacketData::cmd, CMD_CONNECT, CMD_CONNECT_R, CMD_DISCONNECTED, cmd_disconnected_cb(), CMD_ECHO, CMD_ECHO_ANSWER, CMD_ECHO_UNRELIABLE, CMD_GET_NUM_PEERS, CMD_HOST_INFO, CMD_HOST_INFO_ANSWER, CMD_L0, CMD_L0_AUTH, cmd_l0_broadcast_cb(), cmd_l0_cb(), cmd_l0_check_cb(), CMD_L0_CLIENT_BROADCAST, CMD_L0_CLIENTS, CMD_L0_CLIENTS_N, CMD_L0_INFO, CMD_L0_STAT, CMD_L0_TO, cmd_l0_to_cb(), CMD_NONE, CMD_PEERS, CMD_RECONNECT, CMD_RECONNECT_ANSWER, cmd_reconnect_cb(), CMD_RESEND, CMD_RESET, CMD_SPLIT, CMD_STREAM, cmd_stream_cb(), CMD_SUBSCRIBE, CMD_SUBSCRIBE_ANSWER, cmd_subscribe_cb(), CMD_SUBSCRIBE_RND, CMD_TRUDP_INFO, CMD_TUN, cmd_tun_cb(), CMD_UNSUBSCRIBE, CMD_VPN, cmd_vpn_cb(), ksnCorePacketData::data, ksnCorePacketData::data_len, EVENT_MANAGER_CLASS, ksnCorePacketData::from, ke, ksnetEvMgrClass::kl, ksnetEvMgrClass::ks, ksnetEvMgrClass::ktun, and ksnetEvMgrClass::kvpn.
Referenced by cmd_disconnected_cb(), cmd_l0_cb(), and ksnCoreProcessPacket().
void ksnCommandDestroy (ksnCommandClass * kco)
Destroy ksnet command class.
Parameters
kco
References ksnCommandClass::kr, ksnCommandClass::ks, ksnSplitDestroy(), ksnCommandClass::ksscr, and teoSScrDestroy().
Referenced by ksnCoreDestroy().
void* ksnCommandEchoBuffer (ksnCommandClass * kco, void * data, size_t data_len, size_t * data_t_len)
Create ECHO command buffer.
Parameters
kco Pointer to ksnCommandClass
data Echo data
data_len Echo data length
data_t_len Pointer to hold ECHO buffer size
Returns
Pointer to ECHO command buffer. SHould be free after use.
References EVENT_MANAGER_CLASS, ke, and ksnetEvMgrGetTime().
Referenced by _check_connected(), ksnCommandSendCmdEcho(), ksnLNullSendEchoToL0(), and ksnLNullSendEchoToL0A().
ksnCommandClass* ksnCommandInit (void * kc)
Initialize ksnet command class.
Returns
References kc, ksnCommandClass::kc, ke, ksnCommandClass::kr, ksnCommandClass::ks, ksnReconnectInit(), ksnSplitInit(), ksnCommandClass::ksscr, teo_malloc(), and teoSScrInit().
Referenced by ksnCoreInit().
int ksnCommandSendCmdConnect (ksnCommandClass * kco, char * to, char * name, char * addr, uint32_t port)
Send CONNECTED command to peer.
Parameters
kco Pointer to ksnCommandClass
to Send command to peer name
name Name of peer to connect
addr IP address of peer to connect
port Port of peer to connect
Returns
References CMD_CONNECT, data, DEBUG_VV, EVENT_MANAGER_CLASS, fillConnectData(), ksnCommandClass::kc, ke, KSN_BUFFER_DB_SIZE, ksn_printf, ksnCoreSendCmdto(), and MODULE.
Referenced by ksnCommandSendCmdConnectA(), send_cmd_connect_cb(), and send_cmd_connected_cb().
int ksnCommandSendCmdConnectA (ksnCommandClass * kco, char * to_addr, uint32_t to_port, char * name, char * addr, uint32_t port)
Send CONNECTED command to peer by address.
Parameters
kco Pointer to ksnCommandClass
to_addr Send command to IP address
to_port Send command to Port
name Name of peer to connect
addr IP address of peer to connect
port Port of peer to connect
Returns
References ksnCorePacketData::addr, ksnCorePacketData::arp, ARP_TABLE_CLASS, ksnCorePacketData::cmd, CMD_CONNECT, CMD_ECHO_ANSWER, CMD_ECHO_UNRELIABLE_ANSWER, CMD_GET_NUM_PEERS_ANSWER, CMD_HOST_INFO_ANSWER, CMD_L0_CLIENTS_ANSWER, CMD_L0_CLIENTS_N_ANSWER, CMD_L0_INFO_ANSWER, CMD_L0_STAT_ANSWER, CMD_PEERS_ANSWER, CMD_TRUDP_INFO_ANSWER, data, ksnCorePacketData::data, ksnCorePacketData::data_len, DEBUG_VV, EV_K_CONNECTED, ksnetEvMgrClass::event_cb, EVENT_MANAGER_CLASS, fillConnectData(), ksnCorePacketData::from, ksnCorePacketData::from_len, JSON, ksnCommandClass::kc, ksnetEvMgrClass::kc, ke, ksnetEvMgrClass::kl, ksnetEvMgrClass::kq, KSN_BUFFER_DB_SIZE, ksnetEvMgrClass::ksn_cfg, ksn_printf, ksnCommandSendCmdConnect(), ksnCoreSendCmdto(), ksnCoreSendto(), ksnCQueExec(), ksnet_formatMessage(), ksnet_sformatMessage(), ksnetArpGet(), ksnetArpShowData(), ksnetArpShowDataJson(), ksnetArpShowDataLength(), ksnetArpSize(), ksnLNullClientsList(), ksnLNullClientsListLength(), ksnLNullSendToL0(), ksnLNullStat(), ksnCommandClass::ksscr, ksnCoreClass::ku, ksnet_cfg::l0_allow_f, ksnCorePacketData::l0_f, ksnet_cfg::l0_tcp_ip_remote, ksnet_cfg::l0_tcp_port, memdup(), MODULE, null_str, ksnCorePacketData::port, rd, teoGetHostInfo(), teoMetricGauge(), teoSScrSend(), and ksnetEvMgrClass::tm.
Referenced by send_cmd_connect_cb_b().
int ksnCommandSendCmdEcho (ksnCommandClass * kco, char * to, void * data, size_t data_len)
Send ECHO command to peer.
Parameters
kco Pointer to ksnCommandClass
to Send command to peer name
data Echo data
data_len Echo data length
Returns
True at success
References CMD_ECHO, EVENT_MANAGER_CLASS, ksnCommandClass::kc, ke, ksnCommandEchoBuffer(), ksnCoreSendCmdto(), and ksnetEvMgrGetTime().
Referenced by check_connected_cb(), hotkeys_cb(), monitor_timer_one_cb(), ping_timer_cb(), and teo::Teonet::sendEchoTo().
int send_cmd_connect_cb (ksnetArpClass * ka, char * peer_name, ksnet_arp_data_ext * arp, void * data)
Send connect command.
Parameters
ka Pointer to ksnetArpClass
peer_name Peer name
arp_data Pointer to ARP data ksnet_arp_data
data Pointer to ksnCorePacketData
References ksnCorePacketData::addr, data, ksnCorePacketData::from, ksnetArpClass::ke, ksnCommandSendCmdConnect(), and ksnCorePacketData::port.
Referenced by ksnCoreCheckNewPeer(), and send_cmd_connect_cb_b().
int send_cmd_connect_cb_b (ksnetArpClass * ka, char * peer_name, ksnet_arp_data_ext * arp, void * data)
Send connect command.
Parameters
ka Pointer to ksnetArpClass
peer_name Peer name
arp_data Pointer to ARP data ksnet_arp_data
data Pointer to ksnCorePacketData
References ksnCorePacketData::addr, ksnCorePacketData::arp, ARP_TABLE_CLASS, ksnCorePacketData::cmd, CMD_NONE, data, ksnCorePacketData::data, ksnCorePacketData::data_len, DEBUG_VV, EVENT_MANAGER_CLASS, ksnCorePacketData::from, getIPs(), ip_is_private(), ksnetEvMgrClass::is_rhost, ksnCommandClass::kc, ke, ksnetArpClass::ke, ksnetEvMgrClass::kq, ksnetEvMgrClass::ksn_cfg, ksn_printf, ksnCommandSendCmdConnectA(), ksnCoreSendCmdto(), ksnCoreSendto(), ksnCQueAdd(), ksnet_stringArrFree(), ksnet_stringArrLength(), ksnetArpFindByAddr(), ksnetArpGet(), ksnetArpGetAll(), localhost, make_addr, MODULE, NULL_STR, ksnCorePacketData::port, send_cmd_connect_cb(), and send_cmd_connect_cb_b().
Referenced by ksnCoreCheckNewPeer(), and send_cmd_connect_cb_b().
Variable Documentation
const char* BINARY = "BINARY"
const char* JSON = "JSON"
Referenced by ksnCommandSendCmdConnectA().