Teonet library: net_com.h File Reference
net_com.h File Reference
Data Structures
struct ksnCommandClass
KSNet command class data.
struct ksnCorePacketData
KSNet core received data structure.
Macros
#define CMD_TRUDP_CHECK(CMD) (!CMD || CMD == CMD_CONNECT || (CMD >= CMD_64_RESERVED && CMD < CMD_192_RESERVED))
Typedefs
typedef struct ksnCommandClass ksnCommandClass
KSNet command class data.
typedef struct ksnCorePacketData ksnCorePacketData
KSNet core received data structure.
Enumerations
enum ksnCMD {
CMD_NONE = 0, CMD_1_RESERVED, CMD_2_RESERVED, CMD_3_RESERVED,
CMD_CONNECT_R, CMD_CONNECT, CMD_DISCONNECTED, CMD_VPN,
CMD_RESET, CMD_64_RESERVED = 64, CMD_ECHO, CMD_ECHO_ANSWER,
CMD_TUN, CMD_SPLIT, CMD_STREAM, CMD_L0,
CMD_L0_TO, CMD_PEERS, CMD_PEERS_ANSWER, CMD_RESEND,
CMD_RECONNECT, CMD_RECONNECT_ANSWER, CMD_AUTH, CMD_AUTH_ANSWER,
CMD_L0_CLIENTS, CMD_L0_CLIENTS_ANSWER, CMD_SUBSCRIBE, CMD_UNSUBSCRIBE,
CMD_SUBSCRIBE_ANSWER, CMD_L0_CLIENTS_N, CMD_L0_CLIENTS_N_ANSWER, CMD_GET_NUM_PEERS,
CMD_GET_NUM_PEERS_ANSWER, CMD_L0_STAT, CMD_L0_STAT_ANSWER, CMD_HOST_INFO,
CMD_HOST_INFO_ANSWER, CMD_L0_INFO, CMD_L0_INFO_ANSWER, CMD_TRUDP_INFO,
CMD_TRUDP_INFO_ANSWER, CMD_L0_AUTH, CMD_AM, CMD_LOGGING,
CMD_L0_CLIENT_RESET, CMD_SUBSCRIBE_RND, CMD_L0_CLIENT_BROADCAST, CMD_GET_PUBLIC_IP,
CMD_GET_PUBLIC_IP_ANSWER, CMD_128_RESERVED = 128, CMD_USER, CMD_CONFIRM_AUTH = 147,
CMD_192_RESERVED = 192, CMD_USER_NR, CMD_ECHO_UNRELIABLE = 195, CMD_ECHO_UNRELIABLE_ANSWER = 196,
CMD_LAST = 255
}
File: net_com.c Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
Functions
ksnCommandClass * ksnCommandInit (void *kc)
Initialize ksnet command class.
void ksnCommandDestroy (ksnCommandClass *kco)
Destroy ksnet command class.
int ksnCommandCheck (ksnCommandClass *kco, ksnCorePacketData *rd)
Check and process command.
int ksnCommandSendCmdEcho (ksnCommandClass *kco, char *to, void *data, size_t data_len)
Send ECHO command to peer.
void * ksnCommandEchoBuffer (ksnCommandClass *kco, void *data, size_t data_len, size_t *data_t_len)
Create ECHO command buffer.
int ksnCommandSendCmdConnect (ksnCommandClass *kco, char *to, char *name, char *addr, uint32_t port)
Send CONNECTED command to peer.
int cmd_disconnected_cb (ksnCommandClass *kco, ksnCorePacketData *rd)
Process CMD_DISCONNECTED command.
int send_cmd_connect_cb_b (ksnetArpClass *ka, char *peer_name, ksnet_arp_data_ext *arp, void *data)
Send connect command.
int send_cmd_connect_cb (ksnetArpClass *ka, char *peer_name, ksnet_arp_data_ext *arp, void *data)
Send connect command.
Macro Definition Documentation
#define CMD_TRUDP_CHECK (CMD) (!CMD || CMD == CMD_CONNECT || (CMD >= CMD_64_RESERVED && CMD < CMD_192_RESERVED))
Referenced by ksnLNullPacketSend(), and ksnTRUDPsendto().
Typedef Documentation
typedef struct ksnCommandClass ksnCommandClass
KSNet command class data.
typedef struct ksnCorePacketData ksnCorePacketData
KSNet core received data structure.
Enumeration Type Documentation
enum ksnCMD
File: net_com.c Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
Created on April 29, 2015, 7:57 PM
KSNet Network command processing module
Enumerator
CMD_NONE
#0 Common command
CMD_1_RESERVED
#1 Reserver for future use
CMD_2_RESERVED
#2 Reserver for future use
CMD_3_RESERVED
#3 Reserver for future use
CMD_CONNECT_R
#4 A Peer want connect to r-host
CMD_CONNECT
#5 Inform peer about connected peer
CMD_DISCONNECTED
#6 Inform peer about disconnected peer
CMD_VPN
#7 VPN command
CMD_RESET
#8 Reset command, data: byte or char 0 - soft reset; 1 - hard reset
CMD_64_RESERVED
#64 Reserver for future use
CMD_ECHO
#65 Echo test message: auto replay test message command
CMD_ECHO_ANSWER
#66 Answer to auto replay message command
CMD_TUN
#67 Tunnel command
CMD_SPLIT
#68 Group of packets (Splited packets)
CMD_STREAM
#69 Stream command
CMD_L0
#70 Command from L0 Client
CMD_L0_TO
#71 Command to L0 Client
CMD_PEERS
#72 Get peers, allow JSON in request
CMD_PEERS_ANSWER
#73 Get peers answer
CMD_RESEND
#74 Resend command
CMD_RECONNECT
#75 Reconnect command
CMD_RECONNECT_ANSWER
#76 Reconnect answer command
CMD_AUTH
#77 Auth command
CMD_AUTH_ANSWER
#78 Auth answer command
CMD_L0_CLIENTS
#79 Request clients list
CMD_L0_CLIENTS_ANSWER
#80 Clients list
CMD_SUBSCRIBE
#81 Subscribe to event
CMD_UNSUBSCRIBE
#82 UnSubscribe from event
CMD_SUBSCRIBE_ANSWER
#83 Subscribe answer
CMD_L0_CLIENTS_N
#84 Request clients number, allow JSON in request
CMD_L0_CLIENTS_N_ANSWER
#85 Clients number
CMD_GET_NUM_PEERS
#86 Request number of peers, allow JSON in request
CMD_GET_NUM_PEERS_ANSWER
#87 Number of peers answer
CMD_L0_STAT
#88 Get LO server statistic request, allow JSON in request
CMD_L0_STAT_ANSWER
#89 LO server statistic
CMD_HOST_INFO
#90 Request host info, allow JSON in request
CMD_HOST_INFO_ANSWER
#91 Host info amswer
CMD_L0_INFO
#92 L0 server info request
CMD_L0_INFO_ANSWER
#93 L0 server info answer
CMD_TRUDP_INFO
#94 TR-UDP info request
CMD_TRUDP_INFO_ANSWER
#95 TR-UDP info answer
CMD_L0_AUTH
#96 L0 server auth request answer command
CMD_AM
#97 AM application command
CMD_LOGGING
#98 LOGGING command
CMD_L0_CLIENT_RESET
#99 L0 client reset command
CMD_SUBSCRIBE_RND
#100 Subscribe command extension. (Send answer for one random peer by type)
CMD_L0_CLIENT_BROADCAST
#101 Send data to all L0 clients
CMD_GET_PUBLIC_IP
#102 Request public IPs, which set by l0_public_ipv4, l0_public_ipv6 parameters
CMD_GET_PUBLIC_IP_ANSWER
#103 Public IPs answer
CMD_128_RESERVED
#128 Reserver for future use
CMD_USER
#129 User command
CMD_CONFIRM_AUTH
#147 Confirm auth
CMD_192_RESERVED
#192 Reserver for future use
CMD_USER_NR
#193 User command
CMD_ECHO_UNRELIABLE
#195
CMD_ECHO_UNRELIABLE_ANSWER
#196
CMD_LAST
#255 Last command Reserved for future use
Function Documentation
int cmd_disconnected_cb (ksnCommandClass * kco, ksnCorePacketData * rd)
Process CMD_DISCONNECTED command.
A peer send disconnect command
Parameters
kco Pointer to ksnCommandClass
rd Pointer to ksnCorePacketData
Returns
True if command is processed
References ksnCorePacketData::addr, ARP_TABLE_CLASS, ksnCorePacketData::cmd, ksnCorePacketData::data, DEBUG_VV, EV_K_DISCONNECTED, ksnetEvMgrClass::event_cb, EVENT_MANAGER_CLASS, ksnCorePacketData::from, ksnCorePacketData::from_len, ksnCommandClass::kr, ksnetEvMgrClass::ksn_cfg, ksn_printf, ksnet_formatMessage(), ksnetArpRemove(), ksnCommandClass::ksscr, MODULE, ksnCorePacketData::port, ksnet_cfg::r_host_name, teoMetricGauge(), teoSScrSend(), and ksnetEvMgrClass::tm.
Referenced by ksnCommandCheck().
int ksnCommandCheck (ksnCommandClass * kco, ksnCorePacketData * rd)
Check and process command.
Returns
True if command processed
References ksnCorePacketData::addr, ksnCorePacketData::cmd, CMD_CONNECT, CMD_CONNECT_R, CMD_DISCONNECTED, cmd_disconnected_cb(), CMD_ECHO, CMD_ECHO_ANSWER, CMD_ECHO_UNRELIABLE, CMD_GET_NUM_PEERS, CMD_GET_PUBLIC_IP, CMD_HOST_INFO, CMD_HOST_INFO_ANSWER, CMD_L0, CMD_L0_AUTH, cmd_l0_broadcast_cb(), cmd_l0_cb(), cmd_l0_check_cb(), CMD_L0_CLIENT_BROADCAST, CMD_L0_CLIENTS, CMD_L0_CLIENTS_N, CMD_L0_INFO, CMD_L0_STAT, CMD_L0_TO, cmd_l0_to_cb(), CMD_NONE, CMD_PEERS, CMD_RECONNECT, CMD_RECONNECT_ANSWER, cmd_reconnect_cb(), CMD_RESEND, CMD_RESET, CMD_SPLIT, CMD_STREAM, cmd_stream_cb(), CMD_SUBSCRIBE, CMD_SUBSCRIBE_ANSWER, cmd_subscribe_cb(), CMD_SUBSCRIBE_RND, CMD_TRUDP_INFO, CMD_TUN, cmd_tun_cb(), CMD_UNSUBSCRIBE, CMD_VPN, cmd_vpn_cb(), ksnCorePacketData::data, ksnCorePacketData::data_len, DEBUG_VV, EVENT_MANAGER_CLASS, ksnCorePacketData::from, ke, ksnetEvMgrClass::kl, ksnetEvMgrClass::ks, ksn_printf, ksnetEvMgrClass::ktun, ksnetEvMgrClass::kvpn, MODULE, and ksnCorePacketData::port.
Referenced by cmd_l0_cb(), and ksnCoreProcessPacket().
void ksnCommandDestroy (ksnCommandClass * kco)
Destroy ksnet command class.
Parameters
kco
References ksnCommandClass::kr, ksnCommandClass::ks, ksnSplitDestroy(), ksnCommandClass::ksscr, and teoSScrDestroy().
Referenced by ksnCoreDestroy().
void* ksnCommandEchoBuffer (ksnCommandClass * kco, void * data, size_t data_len, size_t * data_t_len)
Create ECHO command buffer.
Parameters
kco Pointer to ksnCommandClass
data Echo data
data_len Echo data length
data_t_len Pointer to hold ECHO buffer size
Returns
Pointer to ECHO command buffer. SHould be free after use.
References EVENT_MANAGER_CLASS, ke, and ksnetEvMgrGetTime().
Referenced by _check_connected(), ksnCommandSendCmdEcho(), ksnLNullSendEchoToL0(), and ksnLNullSendEchoToL0A().
ksnCommandClass* ksnCommandInit (void * kc)
Initialize ksnet command class.
Returns
References kc, ksnCommandClass::kc, ke, ksnCommandClass::kr, ksnCommandClass::ks, ksnReconnectInit(), ksnSplitInit(), ksnCommandClass::ksscr, teo_malloc(), and teoSScrInit().
Referenced by ksnCoreInit().
int ksnCommandSendCmdConnect (ksnCommandClass * kco, char * to, char * name, char * addr, uint32_t port)
Send CONNECTED command to peer.
Parameters
kco Pointer to ksnCommandClass
to Send command to peer name
name Name of peer to connect
addr IP address of peer to connect
port Port of peer to connect
Returns
References CMD_CONNECT, data, DEBUG_VV, EVENT_MANAGER_CLASS, fillConnectData(), ksnCommandClass::kc, ke, KSN_BUFFER_DB_SIZE, ksn_printf, ksnCoreSendCmdto(), and MODULE.
Referenced by send_cmd_connect_cb(), and send_cmd_connected_cb().
int ksnCommandSendCmdEcho (ksnCommandClass * kco, char * to, void * data, size_t data_len)
Send ECHO command to peer.
Parameters
kco Pointer to ksnCommandClass
to Send command to peer name
data Echo data
data_len Echo data length
Returns
True at success
References CMD_ECHO, EVENT_MANAGER_CLASS, ksnCommandClass::kc, ke, ksnCommandEchoBuffer(), ksnCoreSendCmdto(), and ksnetEvMgrGetTime().
Referenced by check_connected_cb(), hotkeys_cb(), monitor_timer_one_cb(), ping_timer_cb(), and teo::Teonet::sendEchoTo().
int send_cmd_connect_cb (ksnetArpClass * ka, char * peer_name, ksnet_arp_data_ext * arp, void * data)
Send connect command.
Parameters
ka Pointer to ksnetArpClass
peer_name Peer name
arp_data Pointer to ARP data ksnet_arp_data
data Pointer to ksnCorePacketData
References ksnCorePacketData::addr, data, ksnCorePacketData::from, ksnetArpClass::ke, ksnCommandSendCmdConnect(), and ksnCorePacketData::port.
Referenced by ksnCoreCheckNewPeer().
int send_cmd_connect_cb_b (ksnetArpClass * ka, char * peer_name, ksnet_arp_data_ext * arp, void * data)
Send connect command.
Parameters
ka Pointer to ksnetArpClass
peer_name Peer name
arp_data Pointer to ARP data ksnet_arp_data
data Pointer to ksnCorePacketData
References ksnCorePacketData::addr, data, ksnCorePacketData::from, ksnetArpClass::ke, ksnCommandSendCmdConnectA(), and ksnCorePacketData::port.
Referenced by ksnCoreCheckNewPeer().