Teonet library: net_core.h File Reference
net_core.h File Reference
#include "config/config.h"
#include <ev.h>
#include <stdint.h>
#include "net_arp.h"
#include "net_com.h"
#include "tr-udp.h"
#include "crypt.h"
#include "trudp.h"
Data Structures
struct ksnCoreClass
KSNet mesh core data.
Macros
#define sendCmdAnswerTo(ke, rd, name, out_data, out_data_len)
Sent teonet command to peer or l0 client.
#define ksnCoreSetEventTime(kc) kc->last_check_event = ksnetEvMgrGetTime(kc->ke)
Typedefs
typedef struct ksnCoreClass ksnCoreClass
KSNet mesh core data.
Functions
ksnCoreClass * ksnCoreInit (void *ke, char *name, int port, char *addr)
Initialize ksnet core.
void ksnCoreDestroy (ksnCoreClass *kc)
Close socket and free memory.
int ksnCoreSendto (ksnCoreClass *kc, char *addr, int port, uint8_t cmd, void *data, size_t data_len)
Send data to remote peer IP:Port.
void teoBroadcastSend (ksnCoreClass *kc, char *to, uint8_t cmd, void *data, size_t data_len)
Send brodcast command to peers by type.
ksnet_arp_data * ksnCoreSendCmdto (ksnCoreClass *kc, char *to, uint8_t cmd, void *data, size_t data_len)
Send command by name to peer.
void ksnCoreProcessPacket (void *kc, void *buf, size_t recvlen, __SOCKADDR_ARG remaddr)
Process teonet packet.
int ksnCoreParsePacket (void *packet, size_t packet_len, ksnCorePacketData *recv_data)
Parse received data to ksnCoreRecvData structure.
void ksnCoreCheckNewPeer (ksnCoreClass *kc, ksnCorePacketData *rd)
Check new peer.
int ksnCoreBindRaw (int *port, int allow_port_increment_f)
Create and bind UDP socket for client/server.
Variables
const char * localhost
KSNet mesh core module.
const char * null_str
File: ev_mgr.h Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
Macro Definition Documentation
#define ksnCoreSetEventTime (kc) kc->last_check_event = ksnetEvMgrGetTime(kc->ke)
Referenced by host_cb(), idle_cb(), and ksnCoreSendto().
#define sendCmdAnswerTo (ke, rd, name, out_data, out_data_len)
Value:
if(rd->l0_f) \
        ksnLNullSendToL0(ke, \
            rd->addr, rd->port, name, strlen(name) + 1, rd->cmd, \
            out_data, out_data_len); \
    else \
        ksnCoreSendCmdto(ke->kc, name, rd->cmd, \
            out_data, out_data_len)
Sent teonet command to peer or l0 client.
Parameters
ke Pointer to ksnetEvMgrClass
rd
name
out_data
out_data_len
Returns
Referenced by teo::Teonet::sendAnswerTo().
Typedef Documentation
typedef struct ksnCoreClass ksnCoreClass
KSNet mesh core data.
Function Documentation
int ksnCoreBindRaw (int * port, int allow_port_increment_f)
Create and bind UDP socket for client/server.
Parameters
[in] ksn_cfg Pointer to teonet configuration: ksnet_cfg
[out] port Pointer to Port number
Returns
File descriptor or error if return value < 0
Referenced by ksnCoreBind(), and ksnTCPProxyServerClientConnect().
void ksnCoreCheckNewPeer (ksnCoreClass * kc, ksnCorePacketData * rd)
Check new peer.
Parameters
kc
rd
Returns
References ksnCoreClass::addr, ksnCorePacketData::addr, ksnCorePacketData::arp, ksnCorePacketData::cmd, CMD_CONNECT_R, CMD_HOST_INFO, CMD_NONE, cq, ksnCorePacketData::data_len, DEBUG, DEBUG_VV, ksnCorePacketData::from, ksnCQueData::id, ksnCoreClass::ka, ksnetEvMgrClass::kc, ke, ksnCoreClass::ke, ksnetEvMgrClass::kq, ksnetEvMgrClass::ksn_cfg, ksn_printf, ksnCoreSendto(), ksnCQueAdd(), ksnetArpAdd(), ksnetArpGet(), ksnetArpGetAll(), ksnetEvMgrGetTime(), MODULE, peer_type_cb(), ksnCorePacketData::port, ksnet_cfg::r_host_addr, ksnet_cfg::r_host_name, ksnet_cfg::r_port, rd, send_cmd_connect_cb(), and send_cmd_connect_cb_b().
Referenced by ksnCoreProcessPacket().
void ksnCoreDestroy (ksnCoreClass * kc)
Close socket and free memory.
Parameters
kc Pointer to ksnCore class object
References ksnCoreClass::addr, ksnCoreClass::fd, ksnCoreClass::host_w, ksnCoreClass::ka, ksnetEvMgrClass::kc, ksnCoreClass::kco, ke, ksnCoreClass::ke, ksnCommandDestroy(), ksnCryptDestroy(), ksnetArpDestroy(), ksnetArpGetAll(), ksnCoreClass::ku, ksnCoreClass::name, send_cmd_disconnect_cb(), and send_cmd_disconnect_peer_cb().
Referenced by modules_destroy().
ksnCoreClass* ksnCoreInit (void * ke, char * name, int port, char * addr)
Initialize ksnet core.
Create socket FD and Bind ksnet UDP client/server
Parameters
ke Pointer to ksnetEvMgrClass
name Host name
port Host port. 0 - create system dependent port number
addr Host IP. NULL - listen at all IPs
Returns
Pointer to ksnCoreClass or NULL if error
References ksnCoreClass::addr, ksnCoreClass::fd, host_cb(), ksnCoreClass::host_w, ksnCoreClass::ka, kc, ksnCoreClass::kco, ke, ksnCoreClass::ke, ksnCommandInit(), ksnCoreBind(), ksnCryptInit(), ksnetArpInit(), ksnetArpSetHostPort(), ksnCoreClass::ku, ksnCoreClass::last_check_event, ksnCoreClass::name, ksnCoreClass::name_len, ksnCoreClass::port, teo_malloc(), teo_strdup(), and trudp_event_cb().
Referenced by modules_init().
int ksnCoreParsePacket (void * packet, size_t packet_len, ksnCorePacketData * rd)
Parse received data to ksnCoreRecvData structure.
Parameters
packet Received packet
packet_len Received packet length
rd Pointer to ksnCoreRecvData structure
References ksnCorePacketData::cmd, ksnCorePacketData::data, ksnCorePacketData::data_len, ksnCorePacketData::from, ksnCorePacketData::from_len, PACKET_HEADER_ADD_SIZE, ksnCorePacketData::raw_data, and ksnCorePacketData::raw_data_len.
Referenced by ksnCoreProcessPacket(), and trudp_send_event_ack_to_app().
void ksnCoreProcessPacket (void * vkc, void * buf, size_t recvlen, __SOCKADDR_ARG remaddr)
Process teonet packet.
Parameters
vkc Pointer to ksnCoreClass
buf Buffer with packet
recvlen Packet length
remaddr Address
References addr_port::addr, ksnCorePacketData::addr, addr_port_free(), ksnCorePacketData::arp, ksnCorePacketData::cmd, CMD_L0, ksnet_cfg::crypt_f, data, ksnCorePacketData::data, ksnCorePacketData::data_len, DEBUG_VV, EV_K_RECEIVED, EV_K_RECEIVED_WRONG, ksnetEvMgrClass::event_cb, ksnCorePacketData::from, ksnCorePacketData::from_len, kc, ksnCoreClass::kco, ke, ksnCoreClass::ke, kEventMgrStopped, ksnetEvMgrClass::kl, ksnetEvMgrClass::ksn_cfg, ksn_printf, ksnCheckEncrypted(), ksnCommandCheck(), ksnCoreCheckNewPeer(), ksnCoreParsePacket(), ksnDecryptPackage(), ksnetEvMgrGetTime(), ksnetEvMgrStatus(), ksnLNulltrudpCheckPaket(), MODULE, addr_port::port, ksnCorePacketData::port, rd, and wrap_inet_ntop().
Referenced by host_cb(), ksnLNullStat(), and trudp_event_cb().
ksnet_arp_data* ksnCoreSendCmdto (ksnCoreClass * kc, char * to, uint8_t cmd, void * data, size_t data_len)
Send command by name to peer.
Parameters
kc Pointer to ksnCoreClass
to Peer name to send to
cmd Command
data Commands data
data_len Commands data length
Returns
Pointer to ksnet_arp_data or NULL if to peer is absent
References ksnCoreClass::addr, ksnLNullSPacket::cmd, CMD_L0, CMD_RESEND, data, ksnLNullSPacket::data_length, DEBUG, DEBUG_VV, fd, ksnLNullSPacket::from, ksnLNullSPacket::from_length, ksnCoreClass::ka, ke, ksnCoreClass::ke, ksnetEvMgrClass::kl, ksnetEvMgrClass::km, ksnetEvMgrClass::ksn_cfg, ksn_printf, ksnCoreSendto(), ksnetArpGet(), ksnetArpGetAll(), ksnLNullClientIsConnected(), ksnLNullPacketSend(), ksnMultiSendCmdTo(), ksnet_cfg::l0_allow_f, MODULE, ksnet_cfg::r_host_name, and send_by_type_check_cb().
Referenced by _send_subscribe_event_newvisit(), event_cb(), event_cb_client(), get_cb(), ksnCommandSendCmdConnect(), ksnCommandSendCmdConnectA(), ksnCommandSendCmdEcho(), ksnCoreSendCmdtoA(), ksnLNullStat(), ksnStreamSendTo(), send_cmd_connect_cb_b(), sendCmdT(), teo::Teonet::sendTo(), teoMultiSendCmdToNet(), teoSScrSend(), teoSScrSubscribe(), teoSScrUnSubscribe(), and test_01().
int ksnCoreSendto (ksnCoreClass * kc, char * addr, int port, uint8_t cmd, void * data, size_t data_len)
Send data to remote peer IP:Port.
Parameters
kc Pointer to KSNet core class object
addr IP address of remote peer
port Port of remote peer
cmd Command ID
data Pointer to data
data_len Data size
Returns
Return 0 if success; -1 if data length is too lage (more than MAX_PACKET_LEN)
References CMD_SPLIT, CMD_VPN, DEBUG_VV, ERROR_M, ksnCoreClass::kco, ksnCoreClass::ke, ksnCommandClass::ks, ksn_printf, ksnCoreCreatePacket(), ksnCoreSetEventTime, ksnSplitPacket(), make_addr, MAX_DATA_LEN, MAX_PACKET_LEN, MODULE, and sendto_encrypt.
Referenced by connect_r_host_cb(), ksnCommandSendCmdConnectA(), ksnCoreCheckNewPeer(), ksnCoreSendCmdto(), ksnLNullSendToL0(), open_local_port(), peer_type_cb(), send_cmd_connect_cb_b(), send_cmd_disconnect_cb(), sendCmdAnswerToBinaryA(), and teoBroadcastSend().
void teoBroadcastSend (ksnCoreClass * kc, char * to, uint8_t cmd, void * data, size_t data_len)
Send brodcast command to peers by type.
Parameters
kc Pointer to ksnCoreClass
to Peer name to send to
cmd Command
data Commands data
data_len Commands data length
Returns
Pointer to ksnet_arp_data or NULL if to peer is absent
References DEBUG, ksnCoreClass::ka, ke, ksnCoreClass::ke, ksn_printf, ksnCoreSendto(), ksnetArpGetAll(), MODULE, and send_by_type_check_cb().
Referenced by teo::Teonet::BroadcastSend().
Variable Documentation
const char* localhost
KSNet mesh core module.
const char* null_str
File: ev_mgr.h Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
Created on April 11, 2015, 2:13 AM
Referenced by ksnetEvMgrInitPort(), and teoGetHostInfo().