Teonet library: net_split.c File Reference
net_split.c File Reference
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include "net_split.h"
#include "utils/rlutil.h"
#include "utils/teo_memory.h"
Macros
#define MODULE _ANSI_BLUE "net_split" _ANSI_NONE
File: net_split.c Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
#define kev ((ksnetEvMgrClass*)(((ksnCoreClass*)(ks->kco->kc))->ke))
#define create_key(subpacket_num)
Functions
ksnSplitClass * ksnSplitInit (ksnCommandClass *kco)
Initialize split module.
void ksnSplitDestroy (ksnSplitClass *ks)
Destroy split module.
void ** ksnSplitPacket (ksnSplitClass *ks, uint8_t cmd, void *packet, size_t packet_len, int *num_subpackets)
Split large packet to array of small.
ksnCorePacketData * ksnSplitCombine (ksnSplitClass *ks, ksnCorePacketData *rd)
Combine packets to one large packet.
void ksnSplitFreeRds (ksnSplitClass *ks, ksnCorePacketData *rd)
Free ksnCorePacketData created in ksnSplitCombine function.
Macro Definition Documentation
#define create_key (subpacket_num)
Value:
size_t key_len = sizeof(uint8_t) + rd->from_len + sizeof(uint16_t)*2; \
    void *key = teo_malloc(key_len); \
    size_t ptr = 0; \
    *(uint8_t*)key = rd->from_len; ptr += sizeof(uint8_t); \
    memcpy(key + ptr, rd->from, rd->from_len); ptr += rd->from_len; \
    *(uint16_t*)(key + ptr) = packet_num ; ptr += sizeof(packet_num); \
    *(uint16_t*)(key + ptr) = subpacket_num ; ptr += sizeof(subpacket_num)
Referenced by ksnSplitCombine().
#define kev ((ksnetEvMgrClass*)(((ksnCoreClass*)(ks->kco->kc))->ke))
Referenced by ksnSplitCombine(), and ksnSplitPacket().
#define MODULE _ANSI_BLUE "net_split" _ANSI_NONE
File: net_split.c Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
Created on July 17, 2015, 10:20 AM
Referenced by ksnSplitCombine(), and ksnSplitPacket().
Function Documentation
ksnCorePacketData* ksnSplitCombine (ksnSplitClass * ks, ksnCorePacketData * rd)
Combine packets to one large packet.
Parameters
ks Pointer to ksnSplitClass
rd Pointer to ksnCorePacketData
Returns
Pointer to combined packet ksnCorePacketData or NULL if not combined or error
References ksnCorePacketData::addr, ksnCorePacketData::arp, ksnCorePacketData::cmd, create_key, data, ksnCorePacketData::data, ksnCorePacketData::data_len, ksnSplitClass::data_save, DEBUG_VV, ERROR_M, free(), ksnCorePacketData::from, ksnCorePacketData::from_len, kev, ksn_printf, ksn_puts, ksnetEvMgrGetTime(), ksnSplitClass::last_added, LAST_PACKET_FLAG, malloc(), ksnSplitClass::map, MAX_DATA_LEN, MODULE, ksnCorePacketData::mtu, pblMapRemoveFree(), ksnCorePacketData::port, ksnCorePacketData::raw_data, ksnCorePacketData::raw_data_len, teo_calloc(), and teo_realloc().
void ksnSplitDestroy (ksnSplitClass * ks)
Destroy split module.
Parameters
ks
References free(), and ksnSplitClass::map.
Referenced by ksnCommandDestroy().
void ksnSplitFreeRds (ksnSplitClass * ks, ksnCorePacketData * rd)
Free ksnCorePacketData created in ksnSplitCombine function.
Parameters
ks
rd
References ksnSplitClass::data_save, and free().
ksnSplitClass* ksnSplitInit (ksnCommandClass * kco)
Initialize split module.
Parameters
kco
Returns
References ksnSplitClass::kco, ksnSplitClass::last_added, ksnSplitClass::map, ksnSplitClass::packet_number, and teo_malloc().
Referenced by ksnCommandInit().
void** ksnSplitPacket (ksnSplitClass * ks, uint8_t cmd, void * packet, size_t packet_len, int * num_subpackets)
Split large packet to array of small.
Parameters
ks
cmd
packet
packet_len
num_subpackets
Returns
References DEBUG_VV, kev, ksn_printf, malloc(), MAX_DATA_LEN, MODULE, and ksnSplitClass::packet_number.
Referenced by ksnCoreSendto().