Teonet library: opt.c File Reference
opt.c File Reference
#include <time.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <getopt.h>
#include <syslog.h>
#include <libgen.h>
#include <sys/stat.h>
#include <uuid/uuid.h>
#include "config/config.h"
#include "utils/utils.h"
#include "config/conf.h"
#include "daemon.h"
#include "ev_mgr.h"
Functions
void opt_usage (char *app_name, int app_argc, char **app_argv)
Read command line options.
char ** ksnet_optRead (int argc, char **argv, ksnet_cfg *conf, int app_argc, char **app_argv, char **app_argv_descr, int show_arg)
Read configuration and command line options.
void ksnet_optSetApp (ksnet_cfg *conf, const char *app_name, const char *app_prompt, const char *app_description)
Set application name.
Function Documentation
ksnet_optRead()
char** ksnet_optRead (int argc, char ** argv, ksnet_cfg * conf, int app_argc, char ** app_argv, char ** app_argv_descr, int show_arg)
Read configuration and command line options.
This function should be called to read configuration and command line options
Parameters
argc Number of command line arguments
argv String array with command line arguments
conf Pointer to ksnet_cfg structure to read configuration and command line parameters to
app_argc Number of application arguments
app_argv String array with application arguments names
app_argv_descr String array with application arguments descriptions
show_arg Show arguments
Returns
Entered application arguments
References ksnet_cfg::app_description, ksnet_cfg::app_name, ksnet_cfg::block_cli_input_f, ksnet_cfg::color_output_disable_f, ksnet_cfg::dflag, ksnet_cfg::extended_l0_log_f, ksnet_cfg::filter, getDataPath(), ksnet_cfg::host_name, ksnet_cfg::hot_keys_f, ip_type(), ksnet_cfg::kflag, KSN_BUFFER_SM_SIZE, KSN_MAX_HOST_NAME, ksnet_formatMessage(), ksnet_sformatMessage(), ksnet_cfg::l0_allow_f, ksnet_cfg::l0_tcp_ip_remote, ksnet_cfg::l0_tcp_port, ksnet_cfg::log_disable_f, ksnet_cfg::log_priority, ksnet_cfg::logging_f, ksnet_cfg::net_key, ksnet_cfg::network, ksnet_cfg::no_multi_thread_f, opt_usage(), PACKAGE_NAME, ksnet_cfg::port, ksnet_cfg::port_inc_f, ksnet_cfg::r_host_addr, ksnet_cfg::r_port, ksnet_cfg::r_tcp_f, ksnet_cfg::r_tcp_port, ksnet_cfg::send_ack_event_f, ksnet_cfg::send_all_logs_f, ksnet_cfg::show_connect_f, ksnet_cfg::show_debug_f, ksnet_cfg::show_debug_vv_f, ksnet_cfg::show_debug_vvv_f, SHOW_PEER_CONTINUOSLY, ksnet_cfg::show_peers_f, ksnet_cfg::show_tr_udp_f, ksnet_cfg::sig_segv_f, start_stop_daemon(), ksnet_cfg::statsd_ip, ksnet_cfg::statsd_peers_f, ksnet_cfg::statsd_port, ksnet_cfg::tcp_allow_f, ksnet_cfg::tcp_port, VERSION, ksnet_cfg::vpn_connect_f, ksnet_cfg::vpn_ip, and ksnet_cfg::vpn_mtu.
Referenced by ksnetEvMgrInitPort().
ksnet_optSetApp()
void ksnet_optSetApp (ksnet_cfg * conf, const char * app_name, const char * app_prompt, const char * app_description)
Set application name.
Set application name, prompt and description (use it before ksnet_optRead)
References ksnet_cfg::app_description, ksnet_cfg::app_name, ksnet_cfg::app_prompt, and KSN_BUFFER_SM_SIZE.
Referenced by ksnetEvMgrInitPort().
opt_usage()
void opt_usage (char * app_name, int app_argc, char ** app_argv)
Read command line options.
Show online parameters usage help.
References DEBUG_KSNET, KSN_BUFFER_SIZE, KSNET_PORT_DEFAULT, M_ENAMBE_LOGGING_CLIENT, M_ENAMBE_LOGGING_SERVER, and M_ENAMBE_VPN.
Referenced by ksnet_optRead().