Teonet library: pidfile.h File Reference
pidfile.h File Reference
Functions
void init_pidfile (int port)
Create the pid file name.
void kill_pidfile ()
Free the pid file name.
int write_pidfile ()
Write current pid to the all pidfiles.
void read_pidfile (int *port_pid)
Read current pid from the all pidfiles.
int check_pid (int pid)
Search for process with pid.
void remove_pidfile ()
Remove the pid files.
Function Documentation
check_pid()
int check_pid (int pid)
Search for process with pid.
Parameters
pid
Returns
References FALSE, and TRUE.
Referenced by start_stop_daemon().
init_pidfile()
void init_pidfile (int port)
Create the pid file name.
Parameters
port Port number
Referenced by start_stop_daemon().
kill_pidfile()
void kill_pidfile ()
Free the pid file name.
Referenced by start_stop_daemon().
read_pidfile()
void read_pidfile (int * port_pid)
Read current pid from the all pidfiles.
Parameters
port_pid
References _read_pidfile().
Referenced by start_stop_daemon().
remove_pidfile()
void remove_pidfile ()
Remove the pid files.
Referenced by start_stop_daemon().
write_pidfile()
int write_pidfile ()
Write current pid to the all pidfiles.
Returns
References _write_pidfile().
Referenced by start_stop_daemon().