Teonet library: stream.h File Reference
stream.h File Reference
#include <stdint.h>
#include <stdio.h>
#include <pbl.h>
#include <ev.h>
#include "modules/cque.h"
Data Structures
struct ksnStreamMapData
File: stream.h Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
struct ksnStreamData
Stream map data structure.
struct stream_packet
Stream packet data structure.
struct ksnStreamClass
Stream module class structure.
Typedefs
typedef struct ksnStreamMapData ksnStreamMapData
File: stream.h Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
typedef struct ksnStreamData ksnStreamData
Stream map data structure.
typedef struct ksnStreamClass ksnStreamClass
Stream module class structure.
Enumerations
enum stream_cmd {
CMD_ST_NONE, CMD_ST_CREATE, CMD_ST_CREATE_GOT, CMD_ST_CREATED,
CMD_ST_DATA, CMD_ST_CLOSE, CMD_ST_CLOSE_GOT, CMD_ST_CLOSE_NOTREMOVE
}
Stream subcommands.
Functions
ksnStreamClass * ksnStreamInit (void *ke)
Initialize Stream module.
void ksnStreamDestroy (ksnStreamClass *ks)
Stream module destroy.
int ksnStreamCreate (ksnStreamClass *ks, char *to_peer, char *stream_name, int send_f)
Create new named stream with selected peer.
int ksnStreamClose (ksnStreamClass *ks, char *to_peer, char *stream_name, int send_f)
Close named stream with selected peer.
int ksnStreamClosePeer (ksnStreamClass *ks, const char *peer_name)
Close all streams connected to selected peer.
ksnStreamData * ksnStreamGetDataFromMap (ksnStreamData *sd, ksnStreamMapData *smd)
Get stream data.
ksnStreamMapData * ksnStreamGetMapData (ksnStreamClass *ks, void *key, size_t key_len)
Get stream map data by key.
Typedef Documentation
typedef struct ksnStreamClass ksnStreamClass
Stream module class structure.
typedef struct ksnStreamData ksnStreamData
Stream map data structure.
typedef struct ksnStreamMapData ksnStreamMapData
File: stream.h Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
Teonet stream module
Created on October 3, 2015, 3:02 PM Stream map data structure
Enumeration Type Documentation
enum stream_cmd
Stream subcommands.
Enumerator
CMD_ST_NONE
CMD_ST_CREATE
Create stream command.
CMD_ST_CREATE_GOT
Got create request.
CMD_ST_CREATED
Stream created (answer to create) command.
CMD_ST_DATA
Send data command.
CMD_ST_CLOSE
Close stream command.
CMD_ST_CLOSE_GOT
Got close request from stream.
CMD_ST_CLOSE_NOTREMOVE
Close stream but not remove from stream map.
Function Documentation
int ksnStreamClose (ksnStreamClass * ks, char * to_peer, char * stream_name, int send_f)
Close named stream with selected peer.
Parameters
ks
to_peer
stream_name
send_f
Returns
References CMD_ST_CLOSE, CMD_ST_CLOSE_GOT, CMD_ST_CLOSE_NOTREMOVE, ksnStreamMapData::created, DEBUG_VV, EV_K_STREAM_DISCONNECTED, kev, ksnStreamMapData::key, ksn_printf, ksnStreamSendTo(), ksnStreamClass::map, MODULE, pblMapRemoveFree(), stream_packet::stream_name_len, ksnStreamMapData::w_in, and ksnStreamMapData::w_out.
Referenced by cmd_stream_cb(), kq_connect_cb(), ksnStreamCloseAll(), and ksnStreamClosePeer().
int ksnStreamClosePeer (ksnStreamClass * ks, const char * peer_name)
Close all streams connected to selected peer.
Parameters
ks
peer_name
Returns
References CMD_ST_CLOSE_GOT, ksnStreamClose(), ksnStreamClosePeer(), and ksnStreamClass::map.
Referenced by ksnetArpRemove(), and ksnStreamClosePeer().
int ksnStreamCreate (ksnStreamClass * ks, char * to_peer, char * stream_name, int send_f)
Create new named stream with selected peer.
Parameters
ks
to_peer
stream_name
send_f CMD_ST_CREATE - create pipes and send CREATE request to peer; CMD_ST_CREATE_GOT - CREATE command received, create pipes and send CREATED response CMD_ST_CREATED - CREATED command received
Returns
References CMD_ST_CREATE, CMD_ST_CREATE_GOT, CMD_ST_CREATED, connect_watchers(), ksnStreamMapData::cq, ksnStreamMapData::created, data, DEBUG_VV, ksnCQueData::id, ksnStreamMapData::ke, kev, ksnStreamMapData::key, ksnStreamMapData::key_len, kq_connect_cb(), ksn_printf, KSN_STREAM_CONNECT_TIMEOUT, ksnCQueAdd(), ksnCQueExec(), ksnStreamSendTo(), ksnStreamClass::map, MODULE, ksnStreamMapData::pipe_in, ksnStreamMapData::pipe_out, and stream_packet::stream_name_len.
Referenced by cmd_stream_cb(), and event_cb().
void ksnStreamDestroy (ksnStreamClass * ks)
Stream module destroy.
Parameters
ks Pointer to ksnStreamClass
References ksnStreamCloseAll(), and ksnStreamClass::map.
Referenced by modules_destroy().
ksnStreamData* ksnStreamGetDataFromMap (ksnStreamData * sd, ksnStreamMapData * smd)
Get stream data.
Parameters
sd Pointer to ksnStreamData
smd Pointer to ksnStreamMapData
Returns
References ksnStreamData::fd_in, ksnStreamData::fd_out, ksnStreamMapData::key, ksnStreamData::peer_name, ksnStreamMapData::pipe_in, ksnStreamMapData::pipe_out, and ksnStreamData::stream_name.
Referenced by event_cb().
ksnStreamMapData* ksnStreamGetMapData (ksnStreamClass * ks, void * key, size_t key_len)
Get stream map data by key.
Parameters
ks
key
key_len
Returns
Pointer to ksnStreamMapData or NULL if not found
References data, and ksnStreamClass::map.
Referenced by event_cb().
ksnStreamClass* ksnStreamInit (void * ke)
Initialize Stream module.
Parameters
ke Pointer to
Returns
References ke, ksnStreamClass::ke, and ksnStreamClass::map.
Referenced by modules_init().