Teonet library: string_arr.c File Reference
string_arr.c File Reference
#include <stdlib.h>
#include <string.h>
#include "string_arr.h"
#include "teo_memory.h"
Macros
#define MAX_STRING_LEN 1024
#define arr_realloc(_len_)
#define arr_inc_size(_pos_)
Functions
ksnet_stringArr ksnet_stringArrCreate ()
Create empty c string array.
ksnet_stringArr ksnet_stringArrAdd (ksnet_stringArr *arr, const char *str)
Add c string to string array.
int ksnet_stringArrLength (ksnet_stringArr arr)
Get length of string array.
int ksnet_stringArrMoveTo (ksnet_stringArr arr, unsigned int fromIdx, unsigned toIdx)
Move array item from one position to another.
ksnet_stringArr ksnet_stringArrFree (ksnet_stringArr *arr)
Free string array.
ksnet_stringArr ksnet_stringArrSplit (const char *string, const char *separators, int with_empty, int max_parts)
Split string by separators into words.
char * ksnet_stringArrCombine (ksnet_stringArr arr, const char *separator)
Combine string array to string.
Macro Definition Documentation
arr_inc_size
#define arr_inc_size (_pos_)
Value:
        if(_pos_ >= result_len) { \
            arr_realloc(result_len + MAX_STRING_LEN); \
        }
arr_realloc
#define arr_realloc (_len_)
Value:
        result_len = _len_; \
        result = teo_realloc(result, sizeof(char*) * result_len)
MAX_STRING_LEN
#define MAX_STRING_LEN 1024
Function Documentation
ksnet_stringArrAdd()
ksnet_stringArr ksnet_stringArrAdd (ksnet_stringArr * arr, const char * str)
Add c string to string array.
Parameters
str
arr
Returns
References ksnet_stringArrLength(), teo_malloc(), and teo_realloc().
Referenced by teo::StringArray::add(), getIPs(), and ksnTDBkeyList().
ksnet_stringArrCombine()
char* ksnet_stringArrCombine (ksnet_stringArr arr, const char * separator)
Combine string array to string.
Parameters
arr String array
separator
Returns
Combined string, should be free after use
Referenced by hotkeys_cb(), and test_3_5().
ksnet_stringArrCreate()
ksnet_stringArr ksnet_stringArrCreate ()
Create empty c string array.
Returns
Referenced by getIPs(), and test_3_5().
ksnet_stringArrFree()
ksnet_stringArr ksnet_stringArrFree (ksnet_stringArr * arr)
Free string array.
Parameters
arr
Referenced by connect_r_host_cb(), ksnetHotkeysDestroy(), open_local_port(), teoHotkeySetFilter(), and test_3_5().
ksnet_stringArrLength()
int ksnet_stringArrLength (ksnet_stringArr arr)
Get length of string array.
Parameters
arr
Returns
Referenced by connect_r_host_cb(), ksnet_stringArrAdd(), ksnet_stringArrMoveTo(), open_local_port(), teo::StringArray::size(), and test_3_5().
ksnet_stringArrMoveTo()
int ksnet_stringArrMoveTo (ksnet_stringArr arr, unsigned int fromIdx, unsigned toIdx)
Move array item from one position to another.
Parameters
arr
fromIdx
toIdx
Returns
True at success, null at error
References ksnet_stringArrLength().
Referenced by teo::StringArray::move().
ksnet_stringArrSplit()
ksnet_stringArr ksnet_stringArrSplit (const char * string, const char * separators, int with_empty, int max_parts)
Split string by separators into words.
Parameters
string
separators
with_empty
max_parts Number of parts. if max_parts == 0 then there isn't parts limit
Returns
String array. Should be free with free_string_array after using
References arr_realloc, and MAX_STRING_LEN.
Referenced by teoHotkeySetFilter().