Teonet library: teo::Teonet::TeoDB::teoDbCQueData Struct Reference
teo::Teonet::TeoDB::teoDbCQueData Struct Reference
#include <teonet.hpp>
Public Member Functions
teoDbCQueData (TeoDB *teoDb, teoDbData **tdd, teoL0Client *l0client=NULL, uint8_t cb_type=0)
virtual ~teoDbCQueData ()
auto getId () const -> decltype((*tdd) ->id)
auto getCbType () const -> decltype(cb_type)
auto getL0Client () const -> decltype(l0client)
void * getKey () const
char * getKeyStr () const
void * getValue () const
char * getValueStr () const
Static Public Member Functions
static teoL0Client * setl0Cli (const char *name, uint8_t name_len, const char *addr, int port)
static teoL0Client * setl0Cli (teo::teoPacket *rd)
Data Fields
TeoDB * teodb
teoDbData ** tdd
teoL0Client * l0client
uint8_t cb_type
void * user_data
Constructor & Destructor Documentation
teoDbCQueData()
teo::Teonet::TeoDB::teoDbCQueData::teoDbCQueData (TeoDB * teoDb, teoDbData ** tdd, teoL0Client * l0client = NULL, uint8_t cb_type = 0) inline
~teoDbCQueData()
virtual teo::Teonet::TeoDB::teoDbCQueData::~teoDbCQueData () inline virtual
References l0client.
Member Function Documentation
getCbType()
auto teo::Teonet::TeoDB::teoDbCQueData::getCbType () const -> decltype(cb_type) inline
References cb_type.
getId()
auto teo::Teonet::TeoDB::teoDbCQueData::getId () const -> decltype((*tdd)->id) inline
getKey()
void* teo::Teonet::TeoDB::teoDbCQueData::getKey () const inline
Referenced by getKeyStr().
getKeyStr()
char* teo::Teonet::TeoDB::teoDbCQueData::getKeyStr () const inline
References getKey().
getL0Client()
auto teo::Teonet::TeoDB::teoDbCQueData::getL0Client () const -> decltype(l0client) inline
References l0client.
getValue()
void* teo::Teonet::TeoDB::teoDbCQueData::getValue () const inline
Referenced by getValueStr().
getValueStr()
char* teo::Teonet::TeoDB::teoDbCQueData::getValueStr () const inline
References getValue().
setl0Cli() [1/2]
static teoL0Client* teo::Teonet::TeoDB::teoDbCQueData::setl0Cli (const char * name, uint8_t name_len, const char * addr, int port) inline static
Referenced by teo::Teonet::TeoDB::send(), and setl0Cli().
setl0Cli() [2/2]
static teoL0Client* teo::Teonet::TeoDB::teoDbCQueData::setl0Cli (teo::teoPacket * rd) inline static
References rd, and setl0Cli().
Field Documentation
cb_type
uint8_t teo::Teonet::TeoDB::teoDbCQueData::cb_type
Referenced by getCbType().
l0client
teoL0Client* teo::Teonet::TeoDB::teoDbCQueData::l0client
Referenced by getL0Client(), and ~teoDbCQueData().
tdd
teoDbData** teo::Teonet::TeoDB::teoDbCQueData::tdd
teodb
TeoDB* teo::Teonet::TeoDB::teoDbCQueData::teodb
user_data
void* teo::Teonet::TeoDB::teoDbCQueData::user_data
The documentation for this struct was generated from the following file:
teonet.hpp