Teonet library: subscribe.h File Reference
subscribe.h File Reference
#include <stdint.h>
#include <pbl.h>
#include "teonet_l0_client.h"
Data Structures
struct teoSScrClass
File: subscribe.h Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
struct teoSScrListData
teoSScr class list or CMD_SUBSCRIBE_ANSWER data
Typedefs
typedef struct teoSScrClass teoSScrClass
File: subscribe.h Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
typedef struct teoSScrListData teoSScrListData
teoSScr class list or CMD_SUBSCRIBE_ANSWER data
Functions
teoSScrClass * teoSScrInit (void *ke)
Initialize teoSScr module.
void teoSScrDestroy (teoSScrClass *sscr)
Destroy teoSScr module.
void teoSScrSubscription (teoSScrClass *sscr, char *peer_name, uint16_t ev, ksnet_arp_data *arp)
Remote peer subscribed to event at this host.
int teoSScrUnSubscription (teoSScrClass *sscr, char *peer_name, uint16_t ev)
Remote peer unsubscribed from event at this host.
int teoSScrUnSubscriptionAll (teoSScrClass *sscr, char *peer_name)
Unsubscribe peer_name from all events.
const char * teoSScrSubscriptionList (teoSScrClass *sscr)
Show peers subscribed to this host.
void teoSScrSubscribe (teoSScrClass *sscr, char *peer_name, uint16_t ev)
Send command to subscribe this host to event at remote peer.
void teoSScrUnSubscribe (teoSScrClass *sscr, char *peer_name, uint16_t ev)
Send command to unsubscribe this host from event at remote peer.
void teoSScrSend (teoSScrClass *sscr, uint16_t ev, void *data, size_t data_length, uint8_t cmd)
Send event and it data to all subscribers.
int teoSScrNumberOfSubscribers (teoSScrClass *sscr)
Calculate number of subscriptions.
Typedef Documentation
typedef struct teoSScrClass teoSScrClass
File: subscribe.h Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
Created on December 28, 2015, 1:31 PM teoSScr Class structure definition
typedef struct teoSScrListData teoSScrListData
teoSScr class list or CMD_SUBSCRIBE_ANSWER data
Function Documentation
void teoSScrDestroy (teoSScrClass * sscr)
Destroy teoSScr module.
Parameters
sscr Pointer to ksnCQueClass
References teoSScrClass::map.
Referenced by ksnCommandDestroy(), test_6_1(), and test_6_2().
teoSScrClass* teoSScrInit (void * ke)
Initialize teoSScr module.
Parameters
ke Pointer to ksnetEvMgrClass
Returns
Pointer to created teoSScrClass or NULL if error occurred
References teoSScrClass::ke, ke, and teoSScrClass::map.
Referenced by ksnCommandInit(), test_6_1(), and test_6_2().
int teoSScrNumberOfSubscribers (teoSScrClass * sscr)
Calculate number of subscriptions.
Parameters
sscr
Returns
void teoSScrSend (teoSScrClass * sscr, uint16_t ev, void * data, size_t data_length, uint8_t cmd)
Send event and it data to all subscribers.
Parameters
sscr Pointer to teoSScrClass
ev Event
data Event data
data_length Event data length
cmd Command, used for EV_K_RECEIVED event to show received command
References teoSScrListData::addr, CMD_SUBSCRIBE_ANSWER, teoSScrListData::data, DEBUG, teoSScrClass::ke, ksn_printf, ksnCoreSendCmdto(), ksnLNullSendToL0(), teoSScrListData::l0_f, teoSScrClass::map, MODULE, and teoSScrListData::port.
Referenced by _send_subscribe_event_connected(), _send_subscribe_event_newvisit(), cmd_disconnected_cb(), event_cb(), event_cb_server(), ksnCommandSendCmdConnectA(), ksnLNullClientDisconnect(), teo::Teonet::sendToSscr(), and teoSScrSendA().
void teoSScrSubscribe (teoSScrClass * sscr, char * peer_name, uint16_t ev)
Send command to subscribe this host to event at remote peer.
Parameters
sscr Pointer to teoSScrClass
peer_name Remote host name
ev Event
References CMD_SUBSCRIBE, teoSScrClass::ke, and ksnCoreSendCmdto().
Referenced by event_cb_client(), teo::Teonet::subscribe(), and teoSScrSubscribeA().
void teoSScrSubscription (teoSScrClass * sscr, char * peer_name, uint16_t ev, ksnet_arp_data * arp_data)
Remote peer subscribed to event at this host.
Remote peer 'peer_name' has subscribed to the event 'ev' at this host
Parameters
sscr Pointer to teoSScrClass
peer_name Remote peer name
ev Event
arp_data Pointer to arp data if peer_name is L0 client, or NULL if it's a peer
References add_data_to_list, DEBUG, teoSScrClass::ke, ksn_printf, teoSScrClass::map, MODULE, teoSScrNumberOfSubscribers(), and teoSScrSubscriptionList().
Referenced by cmd_subscribe_cb(), and test_6_2().
const char* teoSScrSubscriptionList (teoSScrClass * sscr)
Show peers subscribed to this host.
Parameters
sscr
Returns
References teoSScrListData::addr, teoSScrListData::cmd, teoSScrListData::data, teoSScrListData::ev, teoSScrListData::l0_f, teoSScrClass::map, and teoSScrListData::port.
Referenced by hotkeys_cb(), and teoSScrSubscription().
void teoSScrUnSubscribe (teoSScrClass * sscr, char * peer_name, uint16_t ev)
Send command to unsubscribe this host from event at remote peer.
Parameters
sscr Pointer to teoSScrClass
peer_name Remote host name
ev Event
References CMD_UNSUBSCRIBE, teoSScrClass::ke, and ksnCoreSendCmdto().
int teoSScrUnSubscription (teoSScrClass * sscr, char * peer_name, uint16_t ev)
Remote peer unsubscribed from event at this host.
Parameters
sscr Pointer to teoSScrClass
peer_name Remote peer name
ev Event
Returns
True if this peer_name and event was present and successfully removed
References teoSScrListData::data, DEBUG, teoSScrListData::ev, teoSScrClass::ke, ksn_printf, teoSScrClass::map, MODULE, and teoSScrNumberOfSubscribers().
Referenced by cmd_subscribe_cb(), event_cb_server(), teoSScrUnSubscriptionAll(), and test_6_2().
int teoSScrUnSubscriptionAll (teoSScrClass * sscr, char * peer_name)
Unsubscribe peer_name from all events.
Parameters
sscr
peer_name
Returns
References teoSScrClass::map, and teoSScrUnSubscription().
Referenced by test_6_2().