Teonet library: tcp_proxy.h File Reference
tcp_proxy.h File Reference
#include <stdint.h>
#include <stdio.h>
#include <pbl.h>
#include <ev.h>
#include "config/conf.h"
Data Structures
struct ksnTCPProxyHeader
TCP Proxy packet(message) header structure.
struct ksnTCPProxyPacketData
TCP Proxy packet data structure.
struct ksnTCPProxyData
ksnTCPProxyClass map data
struct ksnTCPProxyClass
TCP Proxy class data.
Typedefs
typedef struct ksnTCPProxyHeader ksnTCPProxyHeader
TCP Proxy packet(message) header structure.
typedef struct ksnTCPProxyPacketData ksnTCPProxyPacketData
TCP Proxy packet data structure.
typedef struct ksnTCPProxyData ksnTCPProxyData
ksnTCPProxyClass map data
typedef struct ksnTCPProxyClass ksnTCPProxyClass
TCP Proxy class data.
Enumerations
enum ksnTCPProxyBufferStage { WAIT_FOR_START, WAIT_FOR_END, PROCESS_PACKET }
TCP Proxy buffer stage.
enum ksnTCPProxyCommand { CMD_TCPP_PROXY }
TCP Proxy protocol command.
Functions
ksnTCPProxyClass * ksnTCPProxyInit (void *ke)
Initialize TCP Proxy module.
void ksnTCPProxyDestroy (ksnTCPProxyClass *tp)
Destroy TCP Proxy module.
int ksnTCPProxyClientConnect (ksnTCPProxyClass *tp)
Connect to TCP Proxy server.
Detailed Description
Author
Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
Teonet TCP Proxy module
Created on September 8, 2015, 2:00 AM
Typedef Documentation
ksnTCPProxyClass
typedef struct ksnTCPProxyClass ksnTCPProxyClass
TCP Proxy class data.
ksnTCPProxyData
typedef struct ksnTCPProxyData ksnTCPProxyData
ksnTCPProxyClass map data
ksnTCPProxyHeader
typedef struct ksnTCPProxyHeader ksnTCPProxyHeader
TCP Proxy packet(message) header structure.
ksnTCPProxyPacketData
typedef struct ksnTCPProxyPacketData ksnTCPProxyPacketData
TCP Proxy packet data structure.
Enumeration Type Documentation
ksnTCPProxyBufferStage
enum ksnTCPProxyBufferStage
TCP Proxy buffer stage.
Enumerator
WAIT_FOR_START
Wait for begibbibg of the packet.
WAIT_FOR_END
Wait for end of the packet.
PROCESS_PACKET
Process the packet in buffer.
ksnTCPProxyCommand
enum ksnTCPProxyCommand
TCP Proxy protocol command.
Enumerator
CMD_TCPP_PROXY
Resend packet to UDP Proxy client/server.
Function Documentation
ksnTCPProxyClientConnect()
int ksnTCPProxyClientConnect (ksnTCPProxyClass * tp)
Connect to TCP Proxy server.
Get address and port from teonet configuration and connect to R-Host TCP Server
Parameters
tp Pointer to ksnTCPProxyClass
Returns
0 - Successfully connected
References ksnTCPProxyPacketData::buffer, cmd_tcppc_read_cb(), DEBUG, ksnTCPProxyClass::fd_client, ksnTCPProxyPacketData::header, kev, ksn_printf, ksnTcpClientCreate(), ksnTCPProxyPacketData::length, MODULE, ksnTCPProxyClass::packet, ksnTCPProxyPacketData::ptr, ksnTCPProxyPacketData::stage, ksnTCPProxyClass::w_client, and WAIT_FOR_START.
Referenced by connect_r_host_cb(), and ksnTCPProxyInit().
ksnTCPProxyDestroy()
void ksnTCPProxyDestroy (ksnTCPProxyClass * tp)
Destroy TCP Proxy module.
Parameters
tp Pointer to ksnTCPProxyClass
References ksnTCPProxyClientStop(), ksnTCPProxyServerStop(), and ksnTCPProxyClass::map.
Referenced by modules_destroy(), test_5_1(), and test_5_2().
ksnTCPProxyInit()
ksnTCPProxyClass* ksnTCPProxyInit (void * ke)
Initialize TCP Proxy module.
Parameters
ke Pointer to the ksnTCPProxyClass
Returns
Pointer to ksnTCPProxyClass
References ksnTCPProxyClass::fd, ksnTCPProxyClass::fd_client, ke, ksnTCPProxyClass::ke, ksnTCPProxyClientConnect(), ksnTCPProxyServerStart(), and ksnTCPProxyClass::map.
Referenced by modules_init(), test_5_1(), and test_5_2().