Teonet library: tcp_proxy.c File Reference
tcp_proxy.c File Reference
#include <stdlib.h>
#include <string.h>
#include "tcp_proxy.h"
#include "ev_mgr.h"
#include "net_core.h"
#include "utils/rlutil.h"
Macros
#define MODULE _ANSI_YELLOW "tcp_proxy" _ANSI_NONE
#define kev ((ksnetEvMgrClass*)tp->ke)
Pointer to ksnetEvMgrClass.
#define TCP_PROXY_VERSION 0
TCP Proxy version.
Enumerations
enum ksnTCPProxyCliSer { CLIENT, SERVER }
Functions
void host_cb (EV_P_ ev_io *w, int revents)
Teonet host fd read event callback.
int send_cmd_disconnect_cb (ksnetArpClass *ka, char *name, ksnet_arp_data *arp_data, void *data)
void _cmd_tcpp_read_cb (struct ev_loop *loop, struct ev_io *w, int revents, int cli_ser)
TCP Proxy client or server client callback.
void ksnTCPProxyClientStop (ksnTCPProxyClass *tp)
Stop TCP Proxy client.
size_t ksnTCPProxyPackageCreate (void *buffer, size_t buffer_length, const char *addr, int port, int cmd, const void *data, size_t data_length)
Create TCP Proxy package.
int ksnTCPProxyServerStart (ksnTCPProxyClass *tp)
Start TCP Proxy server.
void ksnTCPProxyServerStop (ksnTCPProxyClass *tp)
Stop TCP Proxy server.
void ksnTCPProxyServerClientConnect (ksnTCPProxyClass *tp, int fd)
Connect TCP Proxy Server client.
void ksnTCPProxyServerClientDisconnect (ksnTCPProxyClass *tp, int fd, int remove_f)
Disconnect TCP Proxy Server client.
ssize_t ksnTCPProxySendTo (ksnetEvMgrClass *ke, int cmd, const void *buffer, size_t buffer_len, __CONST_SOCKADDR_ARG addr)
Send command to TCP Proxy.
ksnTCPProxyClass * ksnTCPProxyInit (void *ke)
Initialize TCP Proxy module.
void ksnTCPProxyDestroy (ksnTCPProxyClass *tp)
Destroy TCP Proxy module.
ssize_t teo_recvfrom (ksnetEvMgrClass *ke, int fd, void *buffer, size_t buffer_len, int flags, __SOCKADDR_ARG addr, socklen_t *__restrict addr_len)
Receive packet from UDP or TCP Proxy buffer.
ssize_t teo_sendto (ksnetEvMgrClass *ke, int fd, const void *buffer, size_t buffer_len, int flags, __CONST_SOCKADDR_ARG addr, socklen_t addr_len)
Send UDP packet by UDP or TCP Proxy.
int ksnTCPProxyPackageProcess (ksnTCPProxyPacketData *packet, void *data, size_t data_length)
Process TCP proxy package.
void cmd_tcppc_read_cb (struct ev_loop *loop, struct ev_io *w, int revents)
TCP Proxy client callback.
int ksnTCPProxyClientConnect (ksnTCPProxyClass *tp)
Connect to TCP Proxy server.
void cmd_udpp_read_cb (struct ev_loop *loop, struct ev_io *w, int revents)
UDP client/server Proxy callback.
void cmd_tcpp_read_cb (struct ev_loop *loop, struct ev_io *w, int revents)
TCP Proxy server client callback.
void cmd_tcpp_accept_cb (struct ev_loop *loop, struct ev_ksnet_io *w, int revents, int fd)
TCP Proxy server accept callback.
Detailed Description
Author
Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
Teonet TCP Proxy module
See example:
See test: test_tcp_proxy.c
Created on September 8, 2015, 1:59 AM
Description:
Client functions:
Connect to TCP Proxy server: ksnTCPProxyConnetc()
Server functions:
Start TCP Proxy server: ksnTCPProxyServerStart()
Stop TCP Proxy server: ksnTCPProxyServerStop()
Connect client to TCP Proxy server: ksnTCPProxyServerClientConnect()
Register connection
Start UDP port Proxy
Start resending datagrams between TCP Server and UDP port Proxy
Disconnect client from TCP Proxy server: ksnTCPProxyServerClientDisconnect()
Macro Definition Documentation
kev
#define kev ((ksnetEvMgrClass*)tp->ke)
Pointer to ksnetEvMgrClass.
MODULE
#define MODULE _ANSI_YELLOW "tcp_proxy" _ANSI_NONE
TCP_PROXY_VERSION
#define TCP_PROXY_VERSION 0
TCP Proxy version.
Enumeration Type Documentation
ksnTCPProxyCliSer
enum ksnTCPProxyCliSer
Enumerator
CLIENT
SERVER
Function Documentation
_cmd_tcpp_read_cb()
void _cmd_tcpp_read_cb (struct ev_loop * loop, struct ev_io * w, int revents, int cli_ser)
TCP Proxy client or server client callback.
Get packet from TCP Proxy server client connection and resend it to UDP Proxy
Parameters
loop Event manager loop
w Pointer to watcher
revents Events
cli_ser
References data, DEBUG, DEBUG_VV, kev, KSN_BUFFER_SIZE, ksn_printf, ksnTCPProxyClientStop(), ksnTCPProxyServerClientDisconnect(), MODULE, SERVER, and w.
Referenced by cmd_tcpp_read_cb(), and cmd_tcppc_read_cb().
cmd_tcpp_accept_cb()
void cmd_tcpp_accept_cb (struct ev_loop * loop, struct ev_ksnet_io * w, int revents, int fd)
TCP Proxy server accept callback.
Register client, create UDP Proxy client/server, create event watchers with clients callback
Parameters
loop Event manager loop
w Pointer to watcher
revents Events
fd File description of created client connection
References fd, ksnTCPProxyServerClientConnect(), and w.
Referenced by ksnTCPProxyServerStart().
cmd_tcpp_read_cb()
void cmd_tcpp_read_cb (struct ev_loop * loop, struct ev_io * w, int revents)
TCP Proxy server client callback.
Get packet from TCP Proxy server client connection and resend it to UDP Proxy
Parameters
loop Event manager loop
w Pointer to watcher
revents Events
References _cmd_tcpp_read_cb(), SERVER, and w.
Referenced by ksnTCPProxyServerClientConnect().
cmd_tcppc_read_cb()
void cmd_tcppc_read_cb (struct ev_loop * loop, struct ev_io * w, int revents)
TCP Proxy client callback.
Get packet from TCP Proxy server connection and resend it to read host callback
Parameters
loop Event manager loop
w Pointer to watcher
revents Events
References _cmd_tcpp_read_cb(), CLIENT, and w.
Referenced by ksnTCPProxyClientConnect().
cmd_udpp_read_cb()
void cmd_udpp_read_cb (struct ev_loop * loop, struct ev_io * w, int revents)
UDP client/server Proxy callback.
Get packet from UDP Proxy client connection and resend it to TCP Proxy
Parameters
loop Event manager loop
w Pointer to watcher
revents Events
References CMD_TCPP_PROXY, data, DEBUG, DEBUG_VV, kev, KSN_BUFFER_DB_SIZE, ksn_printf, ksnTCPProxyPackageCreate(), ksnTCPProxyClass::map, MODULE, ksnTCPProxyData::tcp_proxy_fd, and w.
Referenced by ksnTCPProxyServerClientConnect().
host_cb()
void host_cb (EV_P_ ev_io * w, int revents)
Teonet host fd read event callback.
param loop
Parameters
w
revents
References kc, ke, KSN_BUFFER_DB_SIZE, ksn_recvfrom, ksnCoreProcessPacket(), ksnCoreSetEventTime, and w.
Referenced by ksnCoreInit().
ksnTCPProxyClientConnect()
int ksnTCPProxyClientConnect (ksnTCPProxyClass * tp)
Connect to TCP Proxy server.
Get address and port from teonet configuration and connect to R-Host TCP Server
Parameters
tp Pointer to ksnTCPProxyClass
Returns
0 - Successfully connected
References ksnTCPProxyPacketData::buffer, cmd_tcppc_read_cb(), DEBUG, ksnTCPProxyClass::fd_client, ksnTCPProxyPacketData::header, kev, ksn_printf, ksnTcpClientCreate(), ksnTCPProxyPacketData::length, MODULE, ksnTCPProxyClass::packet, ksnTCPProxyPacketData::ptr, ksnTCPProxyPacketData::stage, ksnTCPProxyClass::w_client, and WAIT_FOR_START.
Referenced by connect_r_host_cb(), and ksnTCPProxyInit().
ksnTCPProxyClientStop()
void ksnTCPProxyClientStop (ksnTCPProxyClass * tp)
Stop TCP Proxy client.
Stop TCP Proxy client watcher and close fd connection
Parameters
tp Pointer to ksnTCPProxyClass
References ksnTCPProxyClass::fd_client, kev, ksnetArpRemoveAll(), and ksnTCPProxyClass::w_client.
Referenced by _cmd_tcpp_read_cb(), and ksnTCPProxyDestroy().
ksnTCPProxyDestroy()
void ksnTCPProxyDestroy (ksnTCPProxyClass * tp)
Destroy TCP Proxy module.
Parameters
tp Pointer to ksnTCPProxyClass
References ksnTCPProxyClientStop(), ksnTCPProxyServerStop(), and ksnTCPProxyClass::map.
Referenced by modules_destroy(), test_5_1(), and test_5_2().
ksnTCPProxyInit()
ksnTCPProxyClass* ksnTCPProxyInit (void * ke)
Initialize TCP Proxy module.
Parameters
ke Pointer to the ksnTCPProxyClass
Returns
Pointer to ksnTCPProxyClass
References ksnTCPProxyClass::fd, ksnTCPProxyClass::fd_client, ke, ksnTCPProxyClass::ke, ksnTCPProxyClientConnect(), ksnTCPProxyServerStart(), and ksnTCPProxyClass::map.
Referenced by modules_init(), test_5_1(), and test_5_2().
ksnTCPProxyPackageCreate()
size_t ksnTCPProxyPackageCreate (void * buffer, size_t buffer_length, const char * addr, int port, int cmd, const void * data, size_t data_length)
Create TCP Proxy package.
Create TCP Proxy package from peers UDP address and port, data buffer and its length
Parameters
buffer The buffer to create package in
buffer_length Package data length
addr String with peer UDP address
port UDP port number
cmd TCP Proxy protocol command
data Package data
data_length Package data length
Returns
Return size of created package or error
Return values
> 0 - size of created package
-1 - error: The output buffer less than packet header
-2 - error: The output buffer less than packet header + data
References ksnTCPProxyHeader::addr_length, ksnTCPProxyHeader::checksum, ksnTCPProxyHeader::command, data, get_byte_checksum(), ksnTCPProxyHeader::packet_checksum, ksnTCPProxyHeader::packet_length, ksnTCPProxyHeader::port, TCP_PROXY_VERSION, and ksnTCPProxyHeader::version.
Referenced by cmd_udpp_read_cb(), ksnTCPProxySendTo(), and test_5_2().
ksnTCPProxyPackageProcess()
int ksnTCPProxyPackageProcess (ksnTCPProxyPacketData * packet, void * data, size_t data_length)
Process TCP proxy package.
Read tcp data from input buffer to tp->buffer until end of tcp proxy package, check checksum, take UDP address, port number and UDP package data.
Parameters
packet Pointer to ksnTCPProxyPacketData
data Pointer to received TCP data
data_length TCP data length
Returns
Length of received packet, zero or error code. The TCP packets may be received combined to one big buffer. If packet processed and this function return value grate than 0 and less than input buffer size we need run this function again with data_length = 0 to process next part of input buffer.
(see the "5) Check receiving" code of the test_5_2() function of the test_tcp_proxy.c test)
Return values
>0 - receiving done, the return value contain length of packet, the packet saved to ksnTCPProxyClass::buffer
0 - continue reading current packet
-1 - wrong process package stage
-2 - wrong packet header checksum
-3 - wrong packet checksum
References ksnTCPProxyHeader::addr_length, ksnTCPProxyPacketData::buffer, ksnTCPProxyHeader::checksum, data, get_byte_checksum(), ksnTCPProxyPacketData::header, ksnTCPProxyPackageProcess(), ksnTCPProxyPacketData::length, ksnTCPProxyHeader::packet_checksum, ksnTCPProxyHeader::packet_length, ksnTCPProxyHeader::port, PROCESS_PACKET, ksnTCPProxyPacketData::ptr, ksnTCPProxyPacketData::stage, WAIT_FOR_END, and WAIT_FOR_START.
Referenced by ksnTCPProxyPackageProcess(), and test_5_2().
ksnTCPProxySendTo()
ssize_t ksnTCPProxySendTo (ksnetEvMgrClass * ke, int cmd, const void * buffer, size_t buffer_len, __CONST_SOCKADDR_ARG addr)
Send command to TCP Proxy.
Parameters
ke Pointer to ksnetEvMgrClass
cmd TCP Proxy command
buffer
buffer_len
addr
Returns
References ke, KSN_BUFFER_DB_SIZE, and ksnTCPProxyPackageCreate().
Referenced by teo_sendto().
ksnTCPProxyServerClientConnect()
void ksnTCPProxyServerClientConnect (ksnTCPProxyClass * tp, int fd)
Connect TCP Proxy Server client.
Called when tcp client connected to TCP Proxy Server. Create UDP Proxy and register this client in TCP Proxy map
Parameters
tp Pointer to ksnTCPProxyClass
fd TCP client connection file descriptor
References ksnTCPProxyPacketData::buffer, cmd_tcpp_read_cb(), cmd_udpp_read_cb(), CONNECT, data, fd, ksnTCPProxyPacketData::header, kev, ksn_printf, ksnCoreBindRaw(), ksnTCPProxyPacketData::length, ksnTCPProxyClass::map, MODULE, ksnTCPProxyData::packet, ksnTCPProxyPacketData::ptr, ksnTCPProxyPacketData::stage, ksnTCPProxyData::w, ksnTCPProxyData::w_udp, and WAIT_FOR_START.
Referenced by cmd_tcpp_accept_cb().
ksnTCPProxyServerClientDisconnect()
void ksnTCPProxyServerClientDisconnect (ksnTCPProxyClass * tp, int fd, int remove_f)
Disconnect TCP Proxy Server client.
Called when client disconnected or when the TCP Proxy server closing. Close UDP and TCP connections, remove data from TCP Proxy clients map.
Parameters
tp Pointer to ksnTCPProxyClass
fd TCP client connection file descriptor
remove_f If true than remove disconnected record from map
References CONNECT, fd, kev, ksn_printf, ksnTCPProxyClass::map, MODULE, pblMapRemoveFree(), ksnTCPProxyData::udp_proxy_fd, ksnTCPProxyData::w, and ksnTCPProxyData::w_udp.
Referenced by _cmd_tcpp_read_cb(), and ksnTCPProxyServerStop().
ksnTCPProxyServerStart()
int ksnTCPProxyServerStart (ksnTCPProxyClass * tp)
Start TCP Proxy server.
Create and start TCP Proxy server
Parameters
tp Pointer to ksnTCPProxyClass
Returns
If return value > 0 than server was created successfully
References cmd_tcpp_accept_cb(), fd, ksnTCPProxyClass::fd, kev, ksn_printf, ksnTcpServerCreate(), MESSAGE, and MODULE.
Referenced by ksnTCPProxyInit().
ksnTCPProxyServerStop()
void ksnTCPProxyServerStop (ksnTCPProxyClass * tp)
Stop TCP Proxy server.
Disconnect all connected clients and and stop TCP Proxy server
Parameters
tp Pointer to ksnTCPProxyClass
References fd, ksnTCPProxyClass::fd, kev, ksnTCPProxyServerClientDisconnect(), ksnTcpServerStop(), and ksnTCPProxyClass::map.
Referenced by ksnTCPProxyDestroy().
send_cmd_disconnect_cb()
int send_cmd_disconnect_cb (ksnetArpClass * ka, char * name, ksnet_arp_data * arp_data, void * data)
teo_recvfrom()
ssize_t teo_recvfrom (ksnetEvMgrClass * ke, int fd, void * buffer, size_t buffer_len, int flags, __SOCKADDR_ARG addr, socklen_t *__restrict addr_len)
Receive packet from UDP or TCP Proxy buffer.
Parameters
ke Pointer to ksnetEvMgrClass
fd
buffer
buffer_len
flags
addr
addr_len
Returns
Return values
>0 - Success
-2 - Buffer too small error
-3 - Wrong address error
References addr_port::addr, addr_port_free(), DEBUG_VV, fd, ke, kEventMgrStopped, ksn_printf, ksnetEvMgrStatus(), make_addr, MODULE, addr_port::port, and wrap_inet_ntop().
Referenced by trudp_process_receive().
teo_sendto()
ssize_t teo_sendto (ksnetEvMgrClass * ke, int fd, const void * buffer, size_t buffer_len, int flags, __CONST_SOCKADDR_ARG addr, socklen_t addr_len)
Send UDP packet by UDP or TCP Proxy.
Parameters
ke Pointer to ksnetEvMgrClass
fd
buffer
buffer_len
flags
addr
addr_len
Returns
References addr_port::addr, addr_port_free(), CMD_TCPP_PROXY, DEBUG_VV, fd, ke, ksn_printf, ksnTCPProxySendTo(), MODULE, addr_port::port, and wrap_inet_ntop().