Teonet library: teo_memory.h File Reference
teo_memory.h File Reference
#include <sys/types.h>
Functions
void * teo_malloc (size_t)
void * teo_calloc (size_t)
char * teo_strdup (const char *)
char * teo_strndup (char *, size_t)
void * teo_realloc (void *, size_t)
Function Documentation
void* teo_calloc (size_t)
References teo_malloc().
Referenced by ksnSplitCombine().
void* teo_malloc (size_t)
Referenced by ksnCommandInit(), ksnCoreInit(), ksnet_stringArrAdd(), ksnetArpInit(), ksnetArpShowData(), ksnMultiInit(), ksnReconnectInit(), ksnSplitInit(), monitor_timer_init(), peer_timer_init(), ping_timer_init(), stdin_cb(), teo_calloc(), teoArpGetExtendedArpTable(), and tr_udp_timer_init().
void* teo_realloc (void * , size_t)
Referenced by ksnet_stringArrAdd(), and ksnSplitCombine().
char* teo_strdup (const char *)
Referenced by ksnCoreInit().
char* teo_strndup (char * , size_t)