Teonet library: teo_memory.c File Reference
teo_memory.c File Reference
#include <sys/types.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
Macros
#define _POSIX_C_SOURCE 200809L
Functions
void * teo_malloc (size_t size)
void * teo_calloc (size_t size)
char * teo_strdup (const char *str)
char * teo_strndup (char *str, size_t len)
void * teo_realloc (void *ptr, size_t size)
Macro Definition Documentation
#define _POSIX_C_SOURCE 200809L
Function Documentation
void* teo_calloc (size_t size)
References teo_malloc().
Referenced by ksnSplitCombine().
void* teo_malloc (size_t size)
Referenced by ksnCommandInit(), ksnCoreInit(), ksnet_stringArrAdd(), ksnetArpInit(), ksnetArpShowData(), ksnMultiInit(), ksnReconnectInit(), ksnSplitInit(), monitor_timer_init(), peer_timer_init(), ping_timer_init(), stdin_cb(), teo_calloc(), and tr_udp_timer_init().
void* teo_realloc (void * ptr, size_t size)
Referenced by ksnet_stringArrAdd(), and ksnSplitCombine().
char* teo_strdup (const char * str)
Referenced by ksnCoreInit().
char* teo_strndup (char * str, size_t len)