Teonet library: teo_web_conf.h File Reference
teo_web_conf.h File Reference
Data Structures
struct teoweb_config
File: conf.h Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
Typedefs
typedef struct teoweb_config teoweb_config
File: conf.h Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
Functions
teoweb_config * teowebConfigInit ()
Read teoweb configuration file.
void teowebConfigRead (teoweb_config *conf, const char *network, int port_param)
Read configuration fcfg_freeile.
void teowebConfigFree ()
Typedef Documentation
typedef struct teoweb_config teoweb_config
File: conf.h Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
Teonet web application configuration module
Created on November 29, 2015, 6:04 AM Teoweb configuration structure
Function Documentation
void teowebConfigFree ()
teoweb_config* teowebConfigInit ()
Read teoweb configuration file.
Returns
Pointer to teoweb_config
References malloc().
Referenced by main().
void teowebConfigRead (teoweb_config * conf, const char * network, int port_param)
Read configuration fcfg_freeile.
Parameters
conf Pointer to teoweb_config
network Network name or NULL
port_param Teonet basic port
References teoweb_config::auth_server_url, CONF_NAME, teoweb_config::document_root, free(), getDataPath(), teoweb_config::http_port, KSN_BUFFER_SIZE, ksnet_formatMessage(), ksnet_getSysConfigDir(), teoweb_config::l0_server_name, teoweb_config::l0_server_port, and save_conf_back.
Referenced by main().