Teonet library: teo_web_conf.c File Reference
teo_web_conf.c File Reference
#include <string.h>
#include <stdlib.h>
#include <unistd.h>
#include <libgen.h>
#include <sys/stat.h>
#include <confuse.h>
#include "conf.h"
#include "utils/utils.h"
#include "modules/teo_web/teo_web_conf.h"
Macros
#define CONF_NAME "/teoweb.conf"
#define save_conf_back()
Functions
void teowebConfigRead (teoweb_config *conf, const char *network, int port_param)
Read configuration fcfg_freeile.
teoweb_config * teowebConfigInit ()
Read teoweb configuration file.
void teowebConfigFree (teoweb_config *tw_cfg)
Free teoweb configuration.
Macro Definition Documentation
CONF_NAME
#define CONF_NAME "/teoweb.conf"
save_conf_back
#define save_conf_back ()
Value:
        strncpy(conf->document_root, document_root, KSN_BUFFER_SM_SIZE), \
        strncpy(conf->l0_server_name, l0_server_name, KSN_BUFFER_SM_SIZE), \
        strncpy(conf->auth_server_url, auth_server_url, KSN_BUFFER_SM_SIZE)
Function Documentation
teowebConfigFree()
void teowebConfigFree (teoweb_config * tw_cfg)
Free teoweb configuration.
Referenced by main().
teowebConfigInit()
teoweb_config* teowebConfigInit ()
Read teoweb configuration file.
Returns
Pointer to teoweb_config
Referenced by main().
teowebConfigRead()
void teowebConfigRead (teoweb_config * conf, const char * network, int port_param)
Read configuration fcfg_freeile.
Parameters
conf Pointer to teoweb_config
network Network name or NULL
port_param Teonet basic port
References teoweb_config::auth_server_url, CONF_NAME, teoweb_config::document_root, getDataPath(), teoweb_config::http_port, KSN_BUFFER_SIZE, ksnet_formatMessage(), ksnet_getSysConfigDir(), teoweb_config::l0_server_name, teoweb_config::l0_server_port, and save_conf_back.
Referenced by main().