Teonet library: teo_auth.c File Reference
teo_auth.c File Reference
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <curl/curl.h>
#include "teo_auth.h"
#include "conf.h"
Functions
teoAuthClass * teoAuthInit (ksnHTTPClass *kh)
Initialize Teonet authenticate module.
int teoAuthProcessCommand (teoAuthClass *ta, const char *method, const char *url, const char *data, const char *headers, void *nc_p, command_callback callback)
Store authentication command in list.
void teoAuthDestroy (teoAuthClass *ta)
Destroy Teonet authenticate module.
Function Documentation
void teoAuthDestroy (teoAuthClass * ta)
Destroy Teonet authenticate module.
Parameters
ta
References teoAuthClass::async_mutex, teoAuthClass::cv_mutex, teoAuthClass::cv_threshold, free(), teoAuthClass::list, teoAuthClass::stop, teoAuthClass::stopped, and usleep().
Referenced by ksnHTTPDestroy().
teoAuthClass* teoAuthInit (ksnHTTPClass * kh)
Initialize Teonet authenticate module.
Returns
References teoAuthClass::async_mutex, teoAuthClass::cv_mutex, teoAuthClass::cv_threshold, err, teoAuthClass::kh, teoAuthClass::list, malloc(), and teoAuthClass::tid.
Referenced by ksnHTTPInit().
int teoAuthProcessCommand (teoAuthClass * ta, const char * method, const char * url, const char * data, const char * headers, void * nc_p, command_callback callback)
Store authentication command in list.
Parameters
ta Pointer to teoAuthClass
method
url
data
headers
nc_p
callback
Returns
References teoAuthClass::async_mutex, teoAuthData::callback, teoAuthData::data, teoAuthData::headers, teoAuthClass::list, malloc(), teoAuthData::method, teoAuthData::nc_p, and teoAuthData::url.