Teonet library: teo_web.h File Reference
teo_web.h File Reference
#include "ev_mgr.h"
#include "teo_web_conf.h"
#include "embedded/mongoose/mongoose.h"
Data Structures
struct ksnHTTPClass
File: teo_web.h Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
struct teoweb_data
Teonet HTTP module async data structure.
Typedefs
typedef struct ksnHTTPClass ksnHTTPClass
File: teo_web.h Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
Enumerations
enum WS_CMD { WS_CONNECTED, WS_MESSAGE, WS_DISCONNECTED }
Teonet HTTP module async event commands.
Functions
ksnHTTPClass * ksnHTTPInit (ksnetEvMgrClass *ke, teoweb_config *tw_cfg)
Initialize teonet HTTP module.
void ksnHTTPDestroy (ksnHTTPClass *kh)
Destroy teonet HTTP module.
Typedef Documentation
ksnHTTPClass
typedef struct ksnHTTPClass ksnHTTPClass
File: teo_web.h Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
Teonet HTTP/WS Server module
Created on October 2, 2015, 12:04 AM HTTP module class data
Enumeration Type Documentation
WS_CMD
enum WS_CMD
Teonet HTTP module async event commands.
Enumerator
WS_CONNECTED
Websocket connected.
WS_MESSAGE
Websocket send message.
WS_DISCONNECTED
Websocket disconnected.
Function Documentation
ksnHTTPDestroy()
void ksnHTTPDestroy (ksnHTTPClass * kh)
Destroy teonet HTTP module.
Parameters
kh Pointer to ksnHTTPClass
References ksnHTTPClass::s_http_port, ksnHTTPClass::stop, ksnHTTPClass::stopped, ksnHTTPClass::ta, teoAuthDestroy(), tws, and usleep().
Referenced by event_cb().
ksnHTTPInit()
ksnHTTPClass* ksnHTTPInit (ksnetEvMgrClass * ke, teoweb_config * tw_cfg)
Initialize teonet HTTP module.
Parameters
ke Pointer to ksnetEvMgrClass
tw_cfg Pointer to teoweb_config
Returns
References ksnHTTPClass::conf, teoweb_config::document_root, mg_serve_http_opts::document_root, mg_serve_http_opts::enable_directory_listing, mg_connection::err, teoweb_config::http_port, mg_serve_http_opts::index_files, ksnHTTPClass::ke, ke, KSN_BUFFER_SIZE, ksnHTTPClass::kws, ksnHTTPClass::s_http_port, ksnHTTPClass::s_http_server_opts, ksnHTTPClass::stop, ksnHTTPClass::stopped, ksnHTTPClass::ta, teoAuthInit(), teoWSInit(), and ksnHTTPClass::tid.
Referenced by event_cb().