Teonet library: teoackm.c File Reference
teoackm.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ev_mgr.h"
#include "tr-udp_stat.h"
Macros
#define TACKM_VERSION "0.0.2"
#define CMD_U_STAT "stat"
#define CMD_U_RESET "reset"
#define CMD_U_DATA_OR_STAT "data_or_stat"
#define SERVER_NAME "none"
Enumerations
enum { STATE_NONE, STATE_WAIT_KEY, STATE_WAIT_STRING }
Application states.
Functions
void event_cb (ksnetEvMgrClass *ke, ksnetEvMgrEvents event, void *data, size_t data_len, void *user_data)
Teonet Events callback.
int main (int argc, char **argv)
Main Teoackm application function.
Variables
const char * PRESS_A = "(Press A to return to main application menu)"
int show_data_or_statistic_at_server = 1
enum { ... } state
Application states.
int app_state = STATE_NONE
Application state.
Detailed Description
Author
Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
Macro Definition Documentation
#define CMD_U_DATA_OR_STAT "data_or_stat"
Examples:
teoackm.c.
Referenced by event_cb().
#define CMD_U_RESET "reset"
#define CMD_U_STAT "stat"
Examples:
teoackm.c.
Referenced by event_cb().
#define SERVER_NAME "none"
Examples:
teoackm.c.
Referenced by event_cb().
#define TACKM_VERSION "0.0.2"
Examples:
teoackm.c.
Referenced by main().
Enumeration Type Documentation
anonymous enum
Application states.
Enumerator
STATE_NONE
STATE_WAIT_KEY
STATE_WAIT_STRING
Function Documentation
void event_cb (ksnetEvMgrClass * ke, ksnetEvMgrEvents event, void * data, size_t data_len, void * user_data)
Teonet Events callback.
Parameters
ke
event
data
data_len
user_data
Examples:
teoackm.c.
References _keys_non_blocking_start(), _keys_non_blocking_stop, ksnCorePacketData::addr, teonet_cfg::app_argv, app_state, ksnCorePacketData::cmd, CMD_U_DATA_OR_STAT, CMD_U_STAT, CMD_USER, data, ksnCorePacketData::data, EV_K_CONNECTED, EV_K_DISCONNECTED, EV_K_HOTKEY, EV_K_RECEIVED, EV_K_RECEIVED_ACK, EV_K_STARTED, EV_K_TIMER, EV_K_USER, ksnetEvMgrClass::ev_loop, ksnetEvMgrClass::event_cb, free(), ksnCorePacketData::from, ksnCoreClass::ka, ksnetEvMgrClass::kc, ksnetEvMgrClass::kh, KSN_BUFFER_DB_SIZE, ksnCoreSendCmdto(), ksnet_formatMessage(), ksnetArpGet(), ksnetEvMgrGetHostName(), ksnetEvMgrSetCustomTimer(), ksnTRUDPstatShow(), ksnCoreClass::ku, make_addr, ksnCorePacketData::port, PRESS_A, rd, SERVER_NAME, show_data_or_statistic_at_server, teonet_cfg::show_tr_udp_f, STATE_NONE, STATE_WAIT_KEY, and ksnetEvMgrClass::teo_cfg.
Referenced by main().
int main (int argc, char ** argv)
Main Teoackm application function.
Parameters
argc Number of parameters
argv Parameters array
Returns
EXIT_SUCCESS
Examples:
teoackm.c.
References ksnetEvMgrAppParam::app_argc, ksnetEvMgrAppParam::app_argv, ksnetEvMgrAppParam::app_descr, APP_PARAM, event_cb(), ke, ksnetAllowAckEvent(), ksnetEvMgrInitPort(), ksnetEvMgrRun(), ksnetEvMgrSetCustomTimer(), READ_CONFIGURATION, READ_OPTIONS, TACKM_VERSION, and VERSION.
Variable Documentation
int app_state = STATE_NONE
Application state.
Examples:
teoackm.c.
Referenced by event_cb().
const char* PRESS_A = "(Press A to return to main application menu)"
Examples:
teoackm.c.
Referenced by event_cb().
int show_data_or_statistic_at_server = 1
Examples:
teoackm.c.
Referenced by event_cb().
enum { ... } state
Application states.
Examples:
teoackm.c.
Referenced by cli_match_filter(), cli_match_filter_init(), cli_range_filter(), and cli_range_filter_init().