Teonet library: teocque.c File Reference
teocque.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ev_mgr.h"
Macros
#define TCQUE_VERSION "0.0.1"
Functions
void kq_cb (uint32_t id, int type, void *data)
Callback Queue callback (the same as callback queue event).
void event_cb (ksnetEvMgrClass *ke, ksnetEvMgrEvents event, void *data, size_t data_len, void *user_data)
Teonet Events callback.
int main (int argc, char **argv)
Main QUEUE callback example function.
Detailed Description
Author
Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
Macro Definition Documentation
#define TCQUE_VERSION "0.0.1"
Examples:
teocque.c.
Referenced by main().
Function Documentation
void event_cb (ksnetEvMgrClass * ke, ksnetEvMgrEvents event, void * data, size_t data_len, void * user_data)
Teonet Events callback.
Parameters
ke Pointer to ksnetEvMgrClass
event Teonet Event (ksnetEvMgrEvents)
data Events data
data_len Data length
user_data Some user data (may be set in ksnetEvMgrInitPort())
Examples:
teocque.c.
References cq, data, EV_K_CQUE_CALLBACK, EV_K_TIMER, ksnCQueData::id, ksnetEvMgrClass::kq, kq_cb(), ksnCQueAdd(), ksnCQueExec(), and ksnetEvMgrStop().
Referenced by main().
void kq_cb (uint32_t id, int type, void * data)
Callback Queue callback (the same as callback queue event).
This function calls at timeout or after ksnCQueExec calls
Parameters
id Calls ID
type Type: 0 - timeout callback; 1 - successful callback
data User data
Examples:
teocque.c.
Referenced by event_cb().
int main (int argc, char ** argv)
Main QUEUE callback example function.
Parameters
argc Number of arguments
argv Arguments array
Returns
Examples:
teocque.c.
References event_cb(), ke, ksnet_printf(), ksnetEvMgrInit(), ksnetEvMgrRun(), ksnetEvMgrSetCustomTimer(), MESSAGE, READ_CONFIGURATION, READ_OPTIONS, TCQUE_VERSION, ksnetEvMgrClass::teo_cfg, and VERSION.