Teonet library: teocquecpp.cpp File Reference
teocquecpp.cpp File Reference
#include "teonet.hpp"
Macros
#define TCQUE_VERSION "0.0.2"
Functions
void kq_cb (uint32_t id, int type, void *data)
Callback Queue callback (the same as callback queue event).
void event_cb (teo::Teonet &teo, teo::teoEvents event, void *data, size_t data_len, void *user_data)
Teonet Events callback.
int main (int argc, char **argv)
Main QUEUE callback example function.
Detailed Description
Author
Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
Macro Definition Documentation
TCQUE_VERSION
#define TCQUE_VERSION "0.0.2"
Examples
teocquecpp.cpp.
Function Documentation
event_cb()
void event_cb (teo::Teonet & teo, teo::teoEvents event, void * data, size_t data_len, void * user_data)
Teonet Events callback.
Parameters
ke Pointer to ksnetEvMgrClass
event Teonet Event (ksnetEvMgrEvents)
data Events data
data_len Data length
user_data Some user data (may be set in ksnetEvMgrInitPort())
Examples
teocquecpp.cpp.
References cq, data, EV_K_CQUE_CALLBACK, EV_K_STARTED, EV_K_STOPPED, EV_K_TIMER, and kq_cb().
Referenced by main().
kq_cb()
void kq_cb (uint32_t id, int type, void * data)
Callback Queue callback (the same as callback queue event).
This function calls at timeout or after ksnCQueExec calls
Parameters
id Calls ID
type Type: 0 - timeout callback; 1 - successful callback
data User data inserted in teo::CQue::add
Examples
teocquecpp.cpp.
References data.
Referenced by event_cb().
main()
int main (int argc, char ** argv)
Main QUEUE callback example function.
Parameters
argc Number of arguments
argv Arguments array
Returns
Examples
teocquecpp.cpp.
References event_cb(), TCQUE_VERSION, and VERSION.