Teonet library: teodb_com.c File Reference
teodb_com.c File Reference
#include <stdlib.h>
#include <string.h>
#include "teodb_com.h"
Functions
teo_db_data * prepare_request_data (const void *key, size_t key_len, const void *data, size_t data_len, uint32_t id, size_t *tdd_len)
Prepare teonet db data.
Function Documentation
prepare_request_data()
teo_db_data* prepare_request_data (const void * key, size_t key_len, const void * data, size_t data_len, uint32_t id, size_t * tdd_len)
Prepare teonet db data.
Parameters
key Key
key_len Key length
data Pointer to value
data_len Value length
id Request ID
tdd_len Pointer to variable to hold result packet length
Returns
Result packet, should be free after use
Examples
teodb_ex.c.
References data, teo_db_data::data_length, teo_db_data::id, teo_db_data::key_data, and teo_db_data::key_length.
Referenced by event_cb(), get_cb(), and teo::Teonet::TeoDB::prepareRequest().