Teonet library: teodb_ex.c File Reference
teodb_ex.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ev_mgr.h"
#include "modules/teodb_com.h"
Macros
#define TDB_VERSION "0.0.1"
#define APPNAME _ANSI_MAGENTA "teodb_ex" _ANSI_NONE
#define TEODB_PEER ke->ksn_cfg.app_argv[1]
#define TEODB_EX_KEY "teo_db_ex"
#define TEST_KEY "test"
#define TEST_VALUE "{ \"name\": \"1\" }"
#define ke cqd->ke
#define NUM_RECORDS_TO_SHOW "25"
#define ke cqd->ke
#define KEY "teo_db_ex."
Typedefs
typedef struct get_cq_data get_cq_data
Functions
void list_cb (uint32_t id, int type, void *data)
Callback Queue callback (the same as callback queue event).
void get_cb (uint32_t id, int type, void *data)
Callback Queue callback (the same as callback queue event).
void event_cb (ksnetEvMgrClass *ke, ksnetEvMgrEvents event, void *data, size_t data_len, void *user_data)
Teonet Events callback.
int main (int argc, char **argv)
Main Teonet Database example function.
Detailed Description
Author
Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
Macro Definition Documentation
APPNAME
#define APPNAME _ANSI_MAGENTA "teodb_ex" _ANSI_NONE
Examples
teodb_ex.c.
ke [1/2]
#define ke cqd->ke
Examples
teoack.c, teoackm.c, teocque.c, teodb_ex.c, teofossa.c, teol0cli.c, teolarge.c, teomulti_t.c, teosend.c, teosscr.c, teostream.c, teotcp.c, teoterm.c, and teotun.c.
ke [2/2]
#define ke cqd->ke
KEY
#define KEY "teo_db_ex."
Examples
teodb_ex.c.
NUM_RECORDS_TO_SHOW
#define NUM_RECORDS_TO_SHOW "25"
Examples
teodb_ex.c.
TDB_VERSION
#define TDB_VERSION "0.0.1"
Examples
teodb_ex.c.
TEODB_EX_KEY
#define TEODB_EX_KEY "teo_db_ex"
Examples
teodb_ex.c.
TEODB_PEER
#define TEODB_PEER ke->ksn_cfg.app_argv[1]
Examples
teodb_ex.c.
TEST_KEY
#define TEST_KEY "test"
Examples
teodb_ex.c.
TEST_VALUE
#define TEST_VALUE "{ \"name\": \"1\" }"
Examples
teodb_ex.c.
Typedef Documentation
get_cq_data
typedef struct get_cq_data get_cq_data
Examples
teodb_ex.c.
Function Documentation
event_cb()
void event_cb (ksnetEvMgrClass * ke, ksnetEvMgrEvents event, void * data, size_t data_len, void * user_data)
Teonet Events callback.
Parameters
ke Pointer to ksnetEvMgrClass
event Teonet Event (ksnetEvMgrEvents)
data Events data
data_len Data length
user_data Some user data (may be set in ksnetEvMgrInitPort())
Examples
teodb_ex.c.
References CMD_D_GET, CMD_D_GET_ANSWER, CMD_D_LIST_ANSWER, CMD_D_SET, cq, data, EV_K_CONNECTED, EV_K_RECEIVED, get_cb(), teo_db_data::id, ke, teo_db_data::key_data, teo_db_data::key_length, ksnCoreSendCmdto(), ksnCQueAdd(), ksnCQueExec(), prepare_request_data(), rd, TEODB_EX_KEY, TEODB_PEER, TEST_KEY, and TEST_VALUE.
Referenced by main().
get_cb()
void get_cb (uint32_t id, int type, void * data)
Callback Queue callback (the same as callback queue event).
This function calls at timeout or after ksnCQueExec calls
Parameters
id Calls ID
type Type: 0 - timeout callback; 1 - successful callback
data User data
Examples
teodb_ex.c.
References CMD_D_LIST, cq, data, ke, KEY, ksnCoreSendCmdto(), ksnCQueAdd(), list_cb(), memdup(), prepare_request_data(), and TEODB_PEER.
Referenced by event_cb().
list_cb()
void list_cb (uint32_t id, int type, void * data)
Callback Queue callback (the same as callback queue event).
This function calls at timeout or after ksnCQueExec calls
Parameters
id Calls ID
type Type: 0 - timeout callback; 1 - successful callback
data User data
Examples
teodb_ex.c.
References data, and NUM_RECORDS_TO_SHOW.
Referenced by get_cb().
main()
int main (int argc, char ** argv)
Main Teonet Database example function.
Parameters
argc Number of arguments
argv Arguments array
Returns
Examples
teodb_ex.c.
References ksnetEvMgrAppParam::app_argc, ksnetEvMgrAppParam::app_argv, ksnetEvMgrAppParam::app_descr, APP_PARAM, APPNAME, event_cb(), ke, ksn_puts, ksnetEvMgrInitPort(), ksnetEvMgrRun(), MESSAGE, READ_CONFIGURATION, READ_OPTIONS, TDB_VERSION, teoSetAppType(), and VERSION.