Teonet library: teol0cli.c File Reference
teol0cli.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <ev.h>
#include "ev_mgr.h"
Macros
#define TL0C_VERSION "0.0.1"
Functions
void tcp_read_cb (struct ev_loop *loop, struct ev_io *w, int revents)
TCP client callback.
void event_cb (ksnetEvMgrClass *ke, ksnetEvMgrEvents event, void *data, size_t data_len, void *user_data)
Teonet Events callback.
int main (int argc, char **argv)
Main L0 Client example function.
Variables
int fd
ev_io w
Detailed Description
Author
Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
Macro Definition Documentation
#define TL0C_VERSION "0.0.1"
Examples:
teol0cli.c.
Referenced by main().
Function Documentation
void event_cb (ksnetEvMgrClass * ke, ksnetEvMgrEvents event, void * data, size_t data_len, void * user_data)
Teonet Events callback.
Parameters
ke Pointer to ksnetEvMgrClass
event Teonet Event (ksnetEvMgrEvents)
data Events data
data_len Data length
user_data Some user data (may be set in ksnetEvMgrInitPort())
Examples:
teol0cli.c.
References ksnet_cfg::app_argv, CMD_ECHO, CMD_PEERS, DEBUG, EV_K_STARTED, ksnetEvMgrClass::ev_loop, fd, ke, KSN_BUFFER_SIZE, ksnetEvMgrClass::ksn_cfg, ksnet_printf(), ksnetEvMgrGetHostName(), ksnTcpClientCreate(), ksnetEvMgrClass::kt, tcp_read_cb(), and w.
Referenced by main().
int main (int argc, char ** argv)
Main L0 Client example function.
Parameters
argc Number of arguments
argv Arguments array
Returns
Examples:
teol0cli.c.
References ksnetEvMgrAppParam::app_argc, ksnetEvMgrAppParam::app_argv, ksnetEvMgrAppParam::app_descr, APP_PARAM, event_cb(), ke, ksnetEvMgrInitPort(), ksnetEvMgrRun(), READ_CONFIGURATION, READ_OPTIONS, TL0C_VERSION, and VERSION.
void tcp_read_cb (struct ev_loop * loop, struct ev_io * w, int revents)
TCP client callback.
Get packet from L0 Server
Parameters
loop Event manager loop
w Pointer to watcher
revents Events
Examples:
teol0cli.c.
References CMD_ECHO_ANSWER, CMD_PEERS_ANSWER, data, DEBUG, ke, KSN_BUFFER_DB_SIZE, ksnetEvMgrClass::ksn_cfg, ksnet_printf(), ksnetArpShowHeader(), and ksnetArpShowLine().
Referenced by event_cb().
Variable Documentation
int fd
Examples:
teol0cli.c, and teotcp.c.
Referenced by event_cb(), ksnCoreBind(), ksnCoreSendCmdto(), ksnTCPProxyServerClientConnect(), ksnTCPProxyServerStart(), ksnTCPProxyServerStop(), main(), tcp_server_receive_cb(), teoLogReaderOpenCbPP(), tuntap_start(), and tuntap_sys_start().
ev_io w
Examples:
teol0cli.c, and teotcp.c.
Referenced by event_cb(), stdin_cb(), and teoLogReaderOpenCbPP().