Teonet library: teolarge.c File Reference
teolarge.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ev_mgr.h"
Macros
#define TLARGE_VERSION VERSION
Functions
void event_cb (ksnetEvMgrClass *ke, ksnetEvMgrEvents event, void *data, size_t data_len, void *user_data)
Teonet Events callback.
int main (int argc, char **argv)
Main Teolarge application function.
Detailed Description
Author
Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
Macro Definition Documentation
#define TLARGE_VERSION VERSION
Examples:
teolarge.c.
Referenced by main().
Function Documentation
void event_cb (ksnetEvMgrClass * ke, ksnetEvMgrEvents event, void * data, size_t data_len, void * user_data)
Teonet Events callback.
Parameters
ke
event
data
data_len
user_data
Examples:
teolarge.c.
References ksnCorePacketData::cmd, CMD_USER, data, ksnCorePacketData::data, ksnCorePacketData::data_len, EV_K_RECEIVED, EV_K_TIMER, ksnCorePacketData::from, ksnetEvMgrClass::kc, KSN_BUFFER_DB_SIZE, ksnCoreSendCmdto(), ksnetEvMgrGetHostName(), and rd.
Referenced by main().
int main (int argc, char ** argv)
Main Teolarge application function.
Parameters
argc Number of parameters
argv Parameters array
Returns
Examples:
teolarge.c.
References event_cb(), ke, ksnetEvMgrClass::ksn_cfg, ksnet_printf(), ksnetEvMgrInit(), ksnetEvMgrRun(), ksnetEvMgrSetCustomTimer(), MESSAGE, READ_CONFIGURATION, READ_OPTIONS, and TLARGE_VERSION.