Teonet library: teomulti.c File Reference
teomulti.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "net_multi.h"
Macros
#define TMULTI_VERSION VERSION
#define TEONET_NUM 3
Functions
int main (int argc, char **argv)
Main application function.
Variables
const int TEONET_PORTS [] = { 9301, 9302, 9303 }
const char * TEONET_NAMES [] = { "TEO-A", "TEO-B", "TEO-C" }
Detailed Description
Author
Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
Macro Definition Documentation
#define TEONET_NUM 3
Examples:
teomulti.c.
Referenced by main().
#define TMULTI_VERSION VERSION
Examples:
teomulti.c.
Referenced by main().
Function Documentation
int main (int argc, char ** argv)
Main application function.
Parameters
argc Number of parameters
argv Parameters array
Returns
EXIT_SUCCESS
Examples:
teomulti.c.
References ksnMultiData::argc, ksnMultiData::argv, ksnMultiData::event_cb, ksnMultiDestroy(), ksnMultiInit(), ksnMultiData::names, ksnMultiData::networks, ksnMultiData::num, ksnMultiData::ports, ksnMultiData::run, teoMultiRun(), TEONET_NAMES, TEONET_NUM, TEONET_PORTS, and TMULTI_VERSION.
Variable Documentation
const char* TEONET_NAMES[] = { "TEO-A", "TEO-B", "TEO-C" }
Examples:
teomulti.c.
Referenced by main().
const int TEONET_PORTS[] = { 9301, 9302, 9303 }
Examples:
teomulti.c.
Referenced by main().