Teonet library: teomulti_t.c File Reference
teomulti_t.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <pthread.h>
#include "ev_mgr.h"
Macros
#define TMULTI_T_VERSION VERSION
#define TEONET_NUM 3
#define teonet ((teonet_multi *)teo)
Typedefs
typedef struct teonet_multi teonet_multi
Functions
void * teonet_t (void *teo)
Fossa main thread function.
int main (int argc, char **argv)
Main Teomulti application function.
Variables
const int TEONET_PORTS [TEONET_NUM] = { 9301, 9302, 9303 }
const char * TEONET_NAMES [TEONET_NUM] = { "TEO-A", "TEO-B", "TEO-C" }
Detailed Description
Author
Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
Macro Definition Documentation
#define teonet ((teonet_multi *)teo)
Examples:
teocquecpp.cpp, and teomulti_t.c.
Referenced by main(), and teonet_t().
#define TEONET_NUM 3
Examples:
teomulti_t.c.
Referenced by main().
#define TMULTI_T_VERSION VERSION
Examples:
teomulti_t.c.
Referenced by main().
Typedef Documentation
typedef struct teonet_multi teonet_multi
Examples:
teomulti_t.c.
Function Documentation
int main (int argc, char ** argv)
Main Teomulti application function.
Parameters
argc Number of parameters
argv Parameters array
Returns
EXIT_SUCCESS
Examples:
teomulti_t.c.
References err, ke, KSNET_EVENT_MGR_TIMER, ksnetEvMgrStop(), READ_CONFIGURATION, READ_OPTIONS, teonet, TEONET_NAMES, TEONET_NUM, TEONET_PORTS, teonet_t(), tid, TMULTI_T_VERSION, and usleep().
void* teonet_t (void * teo)
Fossa main thread function.
Parameters
teo
Returns
Examples:
teomulti_t.c.
References teonet_cfg::host_name, ke, ksnetEvMgrInitPort(), ksnetEvMgrRun(), ksnetEvMgrClass::n_next, ksnetEvMgrClass::n_prev, ksnetEvMgrClass::net_count, ksnetEvMgrClass::net_idx, ksnetEvMgrClass::teo_cfg, and teonet.
Referenced by main().
Variable Documentation
const char* TEONET_NAMES[TEONET_NUM] = { "TEO-A", "TEO-B", "TEO-C" }
Examples:
teomulti_t.c.
Referenced by main().
const int TEONET_PORTS[TEONET_NUM] = { 9301, 9302, 9303 }
Examples:
teomulti_t.c.
Referenced by main().