Teonet library: teosscr.c File Reference
teosscr.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ev_mgr.h"
Macros
#define TSSCR_VERSION "0.0.1"
Functions
void event_cb_client (ksnetEvMgrClass *ke, ksnetEvMgrEvents event, void *data, size_t data_len, void *user_data)
Clients Teonet Events callback.
void event_cb_server (ksnetEvMgrClass *ke, ksnetEvMgrEvents event, void *data, size_t data_len, void *user_data)
Servers Teonet Events callback.
void event_cb (ksnetEvMgrClass *ke, ksnetEvMgrEvents event, void *data, size_t data_len, void *user_data)
Common Teonet Events callback.
int main (int argc, char **argv)
Main Subscribe example function.
Detailed Description
Author
Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
Macro Definition Documentation
TSSCR_VERSION
#define TSSCR_VERSION "0.0.1"
Examples
teosscr.c.
Function Documentation
event_cb()
void event_cb (ksnetEvMgrClass * ke, ksnetEvMgrEvents event, void * data, size_t data_len, void * user_data)
Common Teonet Events callback.
Parameters
ke Pointer to ksnetEvMgrClass
event Teonet event selected in ksnetEvMgrEvents enum
data Events data
data_len Data length
user_data User data selected in ksnetEvMgrInitPort() function
Examples
teosscr.c.
References EV_K_STARTED, and ke.
Referenced by main().
event_cb_client()
void event_cb_client (ksnetEvMgrClass * ke, ksnetEvMgrEvents event, void * data, size_t data_len, void * user_data)
Clients Teonet Events callback.
Parameters
ke Pointer to ksnetEvMgrClass
event Teonet event selected in ksnetEvMgrEvents enum
data Events data
data_len Data length
user_data User data selected in ksnetEvMgrInitPort() function
Examples
teosscr.c.
References CMD_USER, data, EV_K_CONNECTED, EV_K_RECEIVED, EV_K_SUBSCRIBE, EV_K_TIMER, ke, ksnCoreSendCmdto(), rd, and teoSScrSubscribe().
event_cb_server()
void event_cb_server (ksnetEvMgrClass * ke, ksnetEvMgrEvents event, void * data, size_t data_len, void * user_data)
Servers Teonet Events callback.
Parameters
ke Pointer to ksnetEvMgrClass
event Teonet event selected in ksnetEvMgrEvents enum
data Events data
data_len Data length
user_data User data selected in ksnetEvMgrInitPort() function
Examples
teosscr.c.
References CMD_USER, data, EV_K_DISCONNECTED, EV_K_RECEIVED, ke, rd, teoSScrSend(), and teoSScrUnSubscription().
main()
int main (int argc, char ** argv)
Main Subscribe example function.
Parameters
argc Number of arguments
argv Arguments array
Returns
Examples
teosscr.c.
References ksnetEvMgrAppParam::app_argc, ksnetEvMgrAppParam::app_argv, ksnetEvMgrAppParam::app_descr, APP_PARAM, event_cb(), ke, ksnetEvMgrInitPort(), ksnetEvMgrRun(), ksnetEvMgrSetCustomTimer(), READ_CONFIGURATION, READ_OPTIONS, TSSCR_VERSION, and VERSION.