Teonet library: teostream.c File Reference
teostream.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include "ev_mgr.h"
Macros
#define TSTR_VERSION "0.0.1"
Functions
void event_cb (ksnetEvMgrClass *ke, ksnetEvMgrEvents event, void *data, size_t data_len, void *user_data)
Teonet Events callback.
int main (int argc, char **argv)
Main Teostream application function.
Detailed Description
Author
Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
Macro Definition Documentation
#define TSTR_VERSION "0.0.1"
Examples:
teostream.c.
Referenced by main().
Function Documentation
void event_cb (ksnetEvMgrClass * ke, ksnetEvMgrEvents event, void * data, size_t data_len, void * user_data)
Teonet Events callback.
Parameters
ke
event
data
data_len
user_data
Examples:
teostream.c.
References teonet_cfg::app_argv, CMD_ST_CREATE, EV_K_CONNECTED, EV_K_STARTED, EV_K_STREAM_CONNECT_TIMEOUT, EV_K_STREAM_CONNECTED, EV_K_STREAM_DATA, EV_K_STREAM_DISCONNECTED, ksnStreamData::fd_in, ksnStreamData::fd_out, ksnetEvMgrClass::ks, KSN_BUFFER_SM_SIZE, ksnStreamCreate(), ksnStreamGetDataFromMap(), ksnStreamGetMapData(), ksnStreamData::peer_name, ksnStreamData::stream_name, and ksnetEvMgrClass::teo_cfg.
Referenced by main().
int main (int argc, char ** argv)
Main Teostream application function.
Parameters
argc Number of parameters
argv Parameters array
Returns
Examples:
teostream.c.
References ksnetEvMgrAppParam::app_argc, ksnetEvMgrAppParam::app_argv, ksnetEvMgrAppParam::app_descr, APP_PARAM, event_cb(), ke, ksnetEvMgrInitPort(), ksnetEvMgrRun(), READ_CONFIGURATION, READ_OPTIONS, TSTR_VERSION, and VERSION.