Teonet library: teovpn.c File Reference
teovpn.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include "ev_mgr.h"
#include <malloc.h>
Macros
#define TVPN_VERSION "0.0.2"
File: teovpn.c Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
Functions
void event_cb (ksnetEvMgrClass *ke, ksnetEvMgrEvents event, void *data, size_t data_len, void *user_data)
Teonet event handler.
int main (int argc, char **argv)
Macro Definition Documentation
TVPN_VERSION
#define TVPN_VERSION "0.0.2"
File: teovpn.c Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
Teonet VPN application. CMD_USER Created on July 14, 2015, 9:52 AM
Function Documentation
event_cb()
void event_cb (ksnetEvMgrClass * ke, ksnetEvMgrEvents event, void * data, size_t data_len, void * user_data)
Teonet event handler.
Parameters
ke
event
data
data_len
user_data
References EV_K_STOPPED.
Referenced by main().
main()
int main (int argc, char ** argv)
References event_cb(), ke, ksnetEvMgrInit(), ksnetEvMgrRun(), READ_ALL, teoGetLibteonetVersion(), teoSetAppType(), teoSetAppVersion(), and TVPN_VERSION.