Teonet library: teoweb.c File Reference
teoweb.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>
#include "modules/teo_web/teo_web.h"
#include "modules/teo_web/teo_web_conf.h"
#include "modules/teo_auth/teo_auth.h"
Macros
#define TWEB_VERSION "0.0.1"
File: teoweb.c Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
#define APP_NAME "teoweb"
#define HELLO_MSG "Hello from WS server!"
Typedefs
typedef struct teowebModules teowebModules
Functions
void event_cb (ksnetEvMgrClass *ke, ksnetEvMgrEvents event, void *data, size_t data_len, void *user_data)
Teonet event handler.
int main (int argc, char **argv)
Main application function.
Macro Definition Documentation
APP_NAME
#define APP_NAME "teoweb"
HELLO_MSG
#define HELLO_MSG "Hello from WS server!"
TWEB_VERSION
#define TWEB_VERSION "0.0.1"
File: teoweb.c Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
Teonet HTTP/WS server based on Cesanta mongoose: https://github.com/cesanta/mongoose
Created on October 1, 2015, 1:17 PM
Typedef Documentation
teowebModules
typedef struct teowebModules teowebModules
Function Documentation
event_cb()
void event_cb (ksnetEvMgrClass * ke, ksnetEvMgrEvents event, void * data, size_t data_len, void * user_data)
Teonet event handler.
Parameters
ke
event
data
data_len
user_data
References APP_NAME, teoweb_data::cmd, data, teoweb_data::data, teoweb_data::data_len, DEBUG, EV_K_ASYNC, EV_K_STARTED, EV_K_STOPPED_BEFORE, HELLO_MSG, ke, ksn_printf, ksnHTTPDestroy(), ksnHTTPInit(), mg_send_websocket_frame(), nc, mg_connection::user_data, WEBSOCKET_OP_TEXT, WS_CONNECTED, WS_DISCONNECTED, and WS_MESSAGE.
Referenced by main().
main()
int main (int argc, char ** argv)
Main application function.
Parameters
argc
argv
Returns
References event_cb(), ke, ksnetEvMgrInitPort(), ksnetEvMgrRun(), READ_ALL, teoGetLibteonetVersion(), teoSetAppType(), teoSetAppVersion(), teowebConfigFree(), teowebConfigInit(), teowebConfigRead(), and TWEB_VERSION.