Teonet library: test_teodb.c File Reference
test_teodb.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <CUnit/Basic.h>
#include "ev_mgr.h"
#include "modules/teodb.h"
Macros
#define kc_emul()
Functions
void test_3_1 ()
Initialize/Destroy Teonet DB module.
void test_3_2 ()
Set default namespace.
void test_3_3 ()
Set and get data.
void test_3_4 ()
Set and get data without default namespace.
void test_3_5 ()
Get list of keys without default namespace.
void test_3_template ()
Test template.
int add_suite_3_tests (void)
Add Teonet DB module tests.
Variables
CU_pSuite pSuite
Macro Definition Documentation
#define kc_emul ()
Value:
ksnetEvMgrClass ke_obj; \
  ksnetEvMgrClass *ke = &ke_obj
Referenced by test_3_1(), test_3_2(), test_3_3(), test_3_4(), test_3_5(), and test_3_template().
Function Documentation
int add_suite_3_tests (void)
Add Teonet DB module tests.
Returns
References pSuite, test_3_1(), test_3_2(), test_3_3(), test_3_4(), and test_3_5().
Referenced by main().
void test_3_1 ()
Initialize/Destroy Teonet DB module.
References ksnTDBClass::defNameSpace, ksnTDBClass::k, kc_emul, ke, ksnTDBdestroy(), and ksnTDBinit().
Referenced by add_suite_3_tests().
void test_3_2 ()
Set default namespace.
References data, ksnTDBClass::defNameSpace, ksnTDBClass::k, kc_emul, ke, ksnTDBdestroy(), ksnTDBgetStr(), ksnTDBinit(), ksnTDBnamespaceRemove(), ksnTDBnamespaceSet(), and ksnTDBsetStr().
Referenced by add_suite_3_tests().
void test_3_3 ()
Set and get data.
References data, ksnTDBClass::defNameSpace, ksnTDBClass::k, kc_emul, ke, ksnTDBdeleteStr(), ksnTDBdestroy(), ksnTDBgetStr(), ksnTDBinit(), ksnTDBnamespaceRemove(), ksnTDBnamespaceSet(), and ksnTDBsetStr().
Referenced by add_suite_3_tests().
void test_3_4 ()
Set and get data without default namespace.
References data, ksnTDBClass::defNameSpace, ksnTDBClass::k, kc_emul, ke, ksnTDBdeleteNsStr(), ksnTDBdestroy(), ksnTDBgetNsStr(), ksnTDBinit(), ksnTDBnamespaceRemove(), and ksnTDBsetNsStr().
Referenced by add_suite_3_tests().
void test_3_5 ()
Get list of keys without default namespace.
References ksnTDBClass::defNameSpace, ksnTDBClass::k, kc_emul, ke, ksnet_stringArrCombine(), ksnet_stringArrCreate(), ksnet_stringArrFree(), ksnet_stringArrLength(), ksnTDBdestroy(), ksnTDBinit(), ksnTDBkeyList(), ksnTDBnamespaceRemove(), ksnTDBnamespaceSet(), and ksnTDBsetStr().
Referenced by add_suite_3_tests().
void test_3_template ()
Test template.
References kc_emul, ke, ksnTDBdestroy(), and ksnTDBinit().
Variable Documentation
CU_pSuite pSuite
Referenced by add_suite_3_tests(), and main().