Teonet library: test_teonet.c File Reference
test_teonet.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <CUnit/Basic.h>
#include "ev_mgr.h"
Functions
int add_suite_1_tests (void)
Add Crypt suite tests.
int add_suite_3_tests (void)
Add Teonet DB module tests.
int add_suite_4_tests (void)
Add Callback QUEUE module tests.
int add_suite_5_tests (void)
Add TCP Proxy suite tests.
int add_suite_6_tests (void)
Add Subscribe module tests.
int init_suite (void)
Initialize suite.
int clean_suite (void)
int main ()
cUnit test main function
Variables
CU_pSuite pSuite = NULL
Detailed Description
Author
Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
Teonet cUnit test (main test module)
cUnit test main module code:
#include <stdio.h>
#include <stdlib.h>
#include <CUnit/Basic.h>
#include "ev_mgr.h"
// Modules functions
int add_suite_1_tests(void);
int add_suite_3_tests(void);
int add_suite_4_tests(void);
int add_suite_5_tests(void);
int add_suite_6_tests(void);
// Global variables
CU_pSuite pSuite = NULL;
/*
 * CUnit Test
 */
int init_suite(void) {
    return 0;
}
int clean_suite(void) {
    return 0;
}
int main() {
    KSN_SET_TEST_MODE(1);
    // Initialize the CUnit test registry
    if (CUE_SUCCESS != CU_initialize_registry())
        return CU_get_error();
    // Add a suite to the registry
    pSuite = CU_add_suite("Teonet library Crypt module", init_suite, clean_suite);
    if (NULL == pSuite) {
        CU_cleanup_registry();
        return CU_get_error();
    }
    add_suite_1_tests();
    // Add a suite to the registry
    pSuite = CU_add_suite("Teonet library TR-UDP module", init_suite, clean_suite);
    if (NULL == pSuite) {
        CU_cleanup_registry();
        return CU_get_error();
    }
    // Add a suite to the registry
    pSuite = CU_add_suite("Teonet DB based at PBL KeyFile module functions", init_suite, clean_suite);
    if (NULL == pSuite) {
        CU_cleanup_registry();
        return CU_get_error();
    }
    add_suite_3_tests();
    // Add a suite to the registry
    pSuite = CU_add_suite("Callback QUEUE module functions", init_suite, clean_suite);
    if (NULL == pSuite) {
        CU_cleanup_registry();
        return CU_get_error();
    }
    add_suite_4_tests();
    // Add a suite to the registry
    pSuite = CU_add_suite("TCP Proxy module functions", init_suite, clean_suite);
    if (NULL == pSuite) {
        CU_cleanup_registry();
        return CU_get_error();
    }
    add_suite_5_tests();
    // Add a suite to the registry
    pSuite = CU_add_suite("Subscribe module functions", init_suite, clean_suite);
    if (NULL == pSuite) {
        CU_cleanup_registry();
        return CU_get_error();
    }
    add_suite_6_tests();
    /* Run all tests using the CUnit Basic interface */
    CU_basic_set_mode(CU_BRM_VERBOSE);
    //CU_list_tests_to_file();
    CU_basic_run_tests();
    //CU_console_run_tests();
    CU_cleanup_registry();
    return CU_get_error();
}
Created on Aug 7, 2015, 9:31:12 PM
Function Documentation
add_suite_1_tests()
int add_suite_1_tests (void)
Add Crypt suite tests.
Returns
References pSuite, test_1_1(), and test_1_2().
Referenced by main().
add_suite_3_tests()
int add_suite_3_tests (void)
Add Teonet DB module tests.
Returns
References pSuite, test_3_1(), test_3_2(), test_3_3(), test_3_4(), and test_3_5().
Referenced by main().
add_suite_4_tests()
int add_suite_4_tests (void)
Add Callback QUEUE module tests.
Returns
References pSuite, and test_4_1().
Referenced by main().
add_suite_5_tests()
int add_suite_5_tests (void)
Add TCP Proxy suite tests.
Returns
References pSuite, test_5_1(), and test_5_2().
Referenced by main().
add_suite_6_tests()
int add_suite_6_tests (void)
Add Subscribe module tests.
Returns
References pSuite, test_6_1(), and test_6_2().
Referenced by main().
clean_suite()
int clean_suite (void)
Referenced by main().
init_suite()
int init_suite (void)
Initialize suite.
Referenced by main().
main()
int main ()
cUnit test main function
References add_suite_1_tests(), add_suite_3_tests(), add_suite_4_tests(), add_suite_5_tests(), add_suite_6_tests(), clean_suite(), init_suite(), KSN_SET_TEST_MODE(), and pSuite.
Variable Documentation
pSuite
CU_pSuite pSuite = NULL
Referenced by add_suite_1_tests(), add_suite_3_tests(), add_suite_4_tests(), add_suite_5_tests(), add_suite_6_tests(), and main().