Teonet library: tests.c File Reference
tests.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include "test.h"
#include "testutil.h"
Functions
int test_empty (void)
int test_object (void)
int test_array (void)
int test_primitive (void)
int test_string (void)
int test_partial_string (void)
int test_partial_array (void)
int test_array_nomem (void)
int test_unquoted_keys (void)
int test_issue_22 (void)
int test_issue_27 (void)
int test_input_length (void)
int test_count (void)
int test_nonstrict (void)
int test_unmatched_brackets (void)
int main (void)
Function Documentation
int main (void)
References test_array(), test_array_nomem(), test_count(), test_empty(), test_input_length(), test_issue_22(), test_issue_27(), test_nonstrict(), test_object(), test_partial_array(), test_partial_string(), test_primitive(), test_string(), test_unmatched_brackets(), and test_unquoted_keys().
int test_array (void)
References check, JSMN_ARRAY, JSMN_ERROR_INVAL, and JSMN_PRIMITIVE.
Referenced by main().
int test_array_nomem (void)
References check, JSMN_ARRAY, JSMN_ERROR_NOMEM, jsmn_init(), jsmn_parse(), JSMN_PRIMITIVE, and JSMN_STRING.
Referenced by main().
int test_count (void)
References check, jsmn_init(), and jsmn_parse().
Referenced by main().
int test_empty (void)
References check, JSMN_ARRAY, and JSMN_OBJECT.
Referenced by main().
int test_input_length (void)
References check, jsmn_init(), JSMN_OBJECT, jsmn_parse(), JSMN_PRIMITIVE, and JSMN_STRING.
Referenced by main().
int test_issue_22 (void)
References check, jsmn_init(), and jsmn_parse().
Referenced by main().
int test_issue_27 (void)
References check, and JSMN_ERROR_PART.
Referenced by main().
int test_nonstrict (void)
References check, JSMN_PRIMITIVE, and JSMN_STRING.
Referenced by main().
int test_object (void)
References check, JSMN_ARRAY, JSMN_ERROR_INVAL, JSMN_OBJECT, JSMN_PRIMITIVE, and JSMN_STRING.
Referenced by main().
int test_partial_array (void)
References check, JSMN_ARRAY, JSMN_ERROR_PART, jsmn_init(), jsmn_parse(), JSMN_PRIMITIVE, and JSMN_STRING.
Referenced by main().
int test_partial_string (void)
References check, JSMN_ERROR_PART, jsmn_init(), JSMN_OBJECT, jsmn_parse(), and JSMN_STRING.
Referenced by main().
int test_primitive (void)
References check, JSMN_OBJECT, JSMN_PRIMITIVE, and JSMN_STRING.
Referenced by main().
int test_string (void)
References check, JSMN_ARRAY, JSMN_ERROR_INVAL, JSMN_OBJECT, and JSMN_STRING.
Referenced by main().
int test_unmatched_brackets (void)
References check, JSMN_ERROR_INVAL, JSMN_ERROR_PART, JSMN_OBJECT, JSMN_PRIMITIVE, and JSMN_STRING.
Referenced by main().
int test_unquoted_keys (void)
References check, jsmn_init(), jsmn_parse(), JSMN_PRIMITIVE, and JSMN_STRING.
Referenced by main().