Teonet library: test_subscribe.c File Reference
test_subscribe.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <CUnit/Basic.h>
#include "ev_mgr.h"
#include "modules/cque.h"
Macros
#define kc_emul()
Emulate ksnetEvMgrClass.
Functions
int teoSScrNumberOfSubscribers (teoSScrClass *sscr)
Calculate number of subscriptions.
void test_6_1 ()
Initialize/Destroy module class.
void test_6_2 ()
Test Subscribe/UnSubscribe.
int add_suite_6_tests (void)
Add Subscribe module tests.
Variables
CU_pSuite pSuite
Macro Definition Documentation
#define kc_emul ()
Value:
ksnetEvMgrClass ke_obj; \
  ksnetEvMgrClass *ke = &ke_obj; \
  ke->ev_loop = ev_loop_new (0); \
  memset(&ke_obj.teo_cfg, 0 , sizeof(ke_obj.teo_cfg))
Emulate ksnetEvMgrClass.
Referenced by test_6_1(), and test_6_2().
Function Documentation
int add_suite_6_tests (void)
Add Subscribe module tests.
Returns
References pSuite, test_6_1(), and test_6_2().
Referenced by main().
int teoSScrNumberOfSubscribers (teoSScrClass * sscr)
Calculate number of subscriptions.
Parameters
sscr
Returns
References teoSScrClass::map.
Referenced by teoSScrSubscription(), teoSScrUnSubscription(), and test_6_2().
void test_6_1 ()
Initialize/Destroy module class.
References kc_emul, ke, teoSScrClass::map, teoSScrDestroy(), and teoSScrInit().
Referenced by add_suite_6_tests().
void test_6_2 ()
Test Subscribe/UnSubscribe.
References kc_emul, ke, teoSScrDestroy(), teoSScrInit(), teoSScrNumberOfSubscribers(), teoSScrSubscription(), teoSScrUnSubscription(), and teoSScrUnSubscriptionAll().
Referenced by add_suite_6_tests().
Variable Documentation
CU_pSuite pSuite
Referenced by add_suite_6_tests().