Teonet library: tr-udp.c File Reference
tr-udp.c File Reference
#include <stdlib.h>
#include <string.h>
#include "ev_mgr.h"
#include "tr-udp.h"
#include "trudp_ev.h"
Macros
#define MODULE _ANSI_LIGHTGREEN "tr_udp" _ANSI_NONE
File: tr-udp.c Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
#define kev ((ksnetEvMgrClass*)(((trudpData *)td)->user_data))
Functions
ssize_t teo_recvfrom (ksnetEvMgrClass *ke, int fd, void *buffer, size_t buffer_len, int flags, __SOCKADDR_ARG addr, socklen_t *__restrict addr_len)
Receive packet from UDP or TCP Proxy buffer.
ssize_t teo_sendto (ksnetEvMgrClass *ke, int fd, const void *buffer, size_t buffer_len, int flags, __CONST_SOCKADDR_ARG addr, socklen_t addr_len)
Send UDP packet by UDP or TCP Proxy.
int ksnetAllowAckEvent (ksnetEvMgrClass *ke, int allow)
Allow or disallow send ACK event (EV_K_RECEIVED_ACK) to teonet event loop.
ssize_t ksnTRUDPsendto (trudpData *td, int resend_flg, uint32_t id, int attempt, int cmd, int fd, const void *buf, size_t buf_len, int flags, __CONST_SOCKADDR_ARG addr, socklen_t addr_len)
Send to peer through TR-UDP transport.
ssize_t ksnTRUDPrecvfrom (trudpData *td, int fd, void *buffer, size_t buffer_len, int flags, __SOCKADDR_ARG addr, socklen_t *addr_len)
Get data from peer through TR-UDP transport.
void trudp_send_event_ack_to_app (ksnetEvMgrClass *ke, uint32_t id, void *data, size_t data_length, __CONST_SOCKADDR_ARG addr)
Send ACK event to teonet event loop.
void trudp_process_receive (trudpData *td, void *data, size_t data_length)
Process read data from UDP.
void trudp_event_cb (void *tcd_pointer, int event, void *data, size_t data_length, void *user_data)
TR-UDP event callback.
Macro Definition Documentation
kev
#define kev ((ksnetEvMgrClass*)(((trudpData *)td)->user_data))
MODULE
#define MODULE _ANSI_LIGHTGREEN "tr_udp" _ANSI_NONE
File: tr-udp.c Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
Teonet Real time communications over UDP protocol (TR-UDP)
Created on August 4, 2015, 12:16 AM
Function Documentation
ksnetAllowAckEvent()
int ksnetAllowAckEvent (ksnetEvMgrClass * ke, int allow) inline
Allow or disallow send ACK event (EV_K_RECEIVED_ACK) to teonet event loop.
Parameters
ke Pointer to ksnetEvMgrClass
allow Allow if true or disallow (set by default)
Returns
Previous state
References ke.
Referenced by main().
ksnTRUDPrecvfrom()
ssize_t ksnTRUDPrecvfrom (trudpData * td, int fd, void * buffer, size_t buffer_len, int flags, __SOCKADDR_ARG addr, socklen_t * addr_len)
Get data from peer through TR-UDP transport.
Parameters
td
fd
buffer
buffer_len
flags
addr
addr_len
Returns
If return 0 than the packet is processed by tu->process_packet function. In other case there is value returned by UDP recvfrom function and the buffer contain received data
ksnTRUDPsendto()
ssize_t ksnTRUDPsendto (trudpData * td, int resend_flg, uint32_t id, int attempt, int cmd, int fd, const void * buf, size_t buf_len, int flags, __CONST_SOCKADDR_ARG addr, socklen_t addr_len)
Send to peer through TR-UDP transport.
Parameters
td Pointer to trudpData object
resend_flg New message or resend sent before (0 - new, 1 -resend)
id ID of resend message
cmd Command to allow TR-UDP
attempt Number of attempt of this message
fd File descriptor of UDP connection
buf Buffer with data
buf_len Data length
flags Flags (always 0, reserved)
addr Peer address
addr_len Peer address length
Returns
Number of bytes sent to UDP
References addr_port::addr, addr_port_free(), CMD_TRUDP_CHECK, DEBUG_VV, DEBUG_VVV, kev, ksn_printf, MODULE, addr_port::port, and wrap_inet_ntop().
teo_recvfrom()
ssize_t teo_recvfrom (ksnetEvMgrClass * ke, int fd, void * buffer, size_t buffer_len, int flags, __SOCKADDR_ARG addr, socklen_t *__restrict addr_len)
Receive packet from UDP or TCP Proxy buffer.
Parameters
ke Pointer to ksnetEvMgrClass
fd
buffer
buffer_len
flags
addr
addr_len
Returns
Return values
>0 - Success
-2 - Buffer too small error
-3 - Wrong address error
References addr_port::addr, addr_port_free(), DEBUG_VV, fd, ke, kEventMgrStopped, ksn_printf, ksnetEvMgrStatus(), make_addr, MODULE, addr_port::port, and wrap_inet_ntop().
Referenced by trudp_process_receive().
teo_sendto()
ssize_t teo_sendto (ksnetEvMgrClass * ke, int fd, const void * buffer, size_t buffer_len, int flags, __CONST_SOCKADDR_ARG addr, socklen_t addr_len)
Send UDP packet by UDP or TCP Proxy.
Parameters
ke Pointer to ksnetEvMgrClass
fd
buffer
buffer_len
flags
addr
addr_len
Returns
References addr_port::addr, addr_port_free(), CMD_TCPP_PROXY, DEBUG_VV, fd, ke, ksn_printf, ksnTCPProxySendTo(), MODULE, addr_port::port, and wrap_inet_ntop().
trudp_event_cb()
void trudp_event_cb (void * tcd_pointer, int event, void * data, size_t data_length, void * user_data)
TR-UDP event callback.
Parameters
tcd_pointer
event
data
data_length
user_data
Referenced by ksnCoreInit().
trudp_process_receive()
void trudp_process_receive (trudpData * td, void * data, size_t data_length)
Process read data from UDP.
Parameters
td
data
data_length
References data, kev, and teo_recvfrom().
trudp_send_event_ack_to_app()
void trudp_send_event_ack_to_app (ksnetEvMgrClass * ke, uint32_t id, void * data, size_t data_length, __CONST_SOCKADDR_ARG addr)
Send ACK event to teonet event loop.
Parameters
ke
id
data
data_len
addr
References addr_port::addr, addr_port_free(), data, EV_K_RECEIVED_ACK, ke, ksnCheckEncrypted(), ksnCoreParsePacket(), ksnDecryptPackage(), addr_port::port, rd, and wrap_inet_ntop().