Teonet library: tr-udp_stat.h File Reference
tr-udp_stat.h File Reference
#include "tr-udp.h"
#include "trudp_stat.h"
#include "ev_mgr.h"
Macros
#define MODULE _ANSI_LIGHTGREEN "tr_udp_stat" _ANSI_NONE
File: tr-udp_stat.h Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
#define KE(tu) (ksnetEvMgrClass *)tu->user_data
Functions
int ksnTRUDPstatShow (trudpData *tu)
File: tr-udp_stat.c Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
int ksnTRUDPqueuesShow (trudpData *td)
Show TR-UDP queues list on terminal.
Macro Definition Documentation
KE
#define KE (tu) (ksnetEvMgrClass *)tu->user_data
MODULE
#define MODULE _ANSI_LIGHTGREEN "tr_udp_stat" _ANSI_NONE
File: tr-udp_stat.h Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
TR-UDP statistic
Created on August 11, 2015, 2:34 PM
Function Documentation
ksnTRUDPqueuesShow()
int ksnTRUDPqueuesShow (trudpData * td) inline
Show TR-UDP queues list on terminal.
Print string with queues list on terminal.
Parameters
td Pointer to trudpData
Returns
Number if line in statistics text
Referenced by hotkeys_cb(), and tr_udp_idle_cb().
ksnTRUDPstatShow()
int ksnTRUDPstatShow (trudpData * tu) inline
File: tr-udp_stat.c Author: Kirill Scherba kiril.nosp@m.l@sc.nosp@m.herba.nosp@m..ru
TR-UDP statistic
Created on August 11, 2015, 2:34 PM Show TR-UDP statistics on terminal
Print string with statistics on terminal.
Parameters
tu
Returns
Number if line in statistics text
Referenced by event_cb(), hotkeys_cb(), and tr_udp_idle_cb().