Teonet library: tuntap_log.c File Reference
tuntap_log.c File Reference
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <stdint.h>
#include "tuntap.h"
Functions
void tuntap_log_set_cb (t_tuntap_log cb)
Copyright (c) 2012, PICHOT Fabien Paul Leonard <pichot.fabienATgmail.com> Copyright (c) 2012, Tristan Le Guern <leguern at="" medu="" dot="" se>="">
void tuntap_log_default (int level, const char *errmsg)
void tuntap_log_hexdump (void *data, size_t size)
void tuntap_log_chksum (void *addr, int count)
Function Documentation
void tuntap_log_chksum (void * addr, int count)
References tuntap_log, and TUNTAP_LOG_NONE.
void tuntap_log_default (int level, const char * errmsg)
References TUNTAP_LOG_DEBUG, TUNTAP_LOG_ERR, TUNTAP_LOG_INFO, TUNTAP_LOG_NONE, TUNTAP_LOG_NOTICE, and TUNTAP_LOG_WARN.
Referenced by tuntap_init(), and tuntap_log_set_cb().
void tuntap_log_hexdump (void * data, size_t size)
References tuntap_log, and TUNTAP_LOG_NONE.
void tuntap_log_set_cb (t_tuntap_log cb)
Copyright (c) 2012, PICHOT Fabien Paul Leonard <pichot.fabienATgmail.com> Copyright (c) 2012, Tristan Le Guern <leguern at="" medu="" dot="" se>="">
Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies.
THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
References tuntap_log, and tuntap_log_default().
Referenced by main().