Teonet library: vpn.h File Reference
vpn.h File Reference
#include <stdio.h>
#include <pbl.h>
#include "ev_mgr.h"
Data Structures
struct ksnVpnClass
File: vpn.h Author: Kirill Scherba.
Typedefs
typedef struct ksnVpnClass ksnVpnClass
File: vpn.h Author: Kirill Scherba.
Functions
void * ksnVpnInit (void *ke)
void ksnVpnDestroy (void *vpn)
int cmd_vpn_cb (ksnVpnClass *kvpn, char *from, void *data, size_t data_len)
void ksnVpnListShow (ksnVpnClass *kvpn)
Typedef Documentation
ksnVpnClass
typedef struct ksnVpnClass ksnVpnClass
File: vpn.h Author: Kirill Scherba.
Created on April 4, 2015, 1:19 AM Update to use with KSMesh on May 3, 2015, 0:19:40
KSNet VPN Module KSNet VPN Class data
Function Documentation
cmd_vpn_cb()
int cmd_vpn_cb (ksnVpnClass * kvpn, char * from, void * data, size_t data_len)
ksnVpnDestroy()
void ksnVpnDestroy (void * vpn)
Referenced by modules_destroy().
ksnVpnInit()
void* ksnVpnInit (void * ke)
Referenced by modules_init().
ksnVpnListShow()
void ksnVpnListShow (ksnVpnClass * kvpn)
Referenced by hotkeys_cb().