# Teonet Dockerfile

FROM gitlab.ksproject.org:5000/teonet/teonet
MAINTAINER Kirill Scherba <kirill@scherba.ru>

ADD filebeat_install.sh ~/
WORKDIR ~/
RUN ./filebeat_install.sh
RUN rm ./filebeat_install.sh

CMD ["/root/teonet_log"]
#CMD ["sh"]
