# Yandex cloud configuration for circle.ci
# The configuration is a test. Only ubuntu-build. 
version: 2
jobs:

  tagged-build-ubuntu:
    docker:
      #- image: gitlab.ksproject.org:5000/ci/ubuntu_teonet
      - image: cr.yandex/crp8ph86e05bgnsgjbb8/ci_ubuntu_build_docker
    steps:
      - checkout
      - run: git submodule update --init --recursive

      # Show variables
      - run: echo $CIRCLE_PROJECT_REPONAME
      - run: echo $CIRCLE_BRANCH
      - run: echo $CIRCLE_TAG

      # Install dependences
      - run: sh/build-ubuntu.sh
      
      # Make
      - run: ./autogen.sh --prefix=/usr
      - run: make
      
      # Test
      - run: app/teovpn -?
      - run: make test

      # Build .deb package and upload it to repository
      - run: sh/make_package deb

  tagged-build-docker:      
    machine:
      docker_layer_caching: true    # default - false
    steps:
      - checkout  
      - run: sudo sysctl -w net.ipv4.ip_forward=1
      - run: docker build --no-cache -t $CIRCLE_PROJECT_REPONAME -f sh/Dockerfile .
      
      # Login to Yandex container Registry (YCR)
      - run: docker login --username $YC_AUTH --password $YC_TOKEN cr.yandex
      
      # Push image to YCR
      - run: docker tag $CIRCLE_PROJECT_REPONAME cr.yandex/crp8ph86e05bgnsgjbb8/test/$CIRCLE_PROJECT_REPONAME:$CIRCLE_TAG
      - run: docker push cr.yandex/crp8ph86e05bgnsgjbb8/test/$CIRCLE_PROJECT_REPONAME:$CIRCLE_TAG
      - run: docker tag $CIRCLE_PROJECT_REPONAME cr.yandex/crp8ph86e05bgnsgjbb8/test/$CIRCLE_PROJECT_REPONAME:latest
      - run: docker push cr.yandex/crp8ph86e05bgnsgjbb8/test/$CIRCLE_PROJECT_REPONAME:latest

workflows:
  version: 2
  
  tagged:
    jobs:

      - tagged-build-ubuntu:
          requires:
            - testing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - tagged-build-docker:
          requires:
            - tagged-build-ubuntu
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
