version: 2
jobs:
  testing:
    machine:
      docker_layer_caching: true
    environment:
      AWS_REGION: eu-west-1
      AWS_ECR_REPONAME: 932815733038.dkr.ecr.eu-west-1.amazonaws.com/teonet
      YC_YCR_REPONAME: cr.yandex/crp8ph86e05bgnsgjbb8/teonet
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: docker build -t $CIRCLE_PROJECT_REPONAME -f sh/Dockerfile .
      - run: docker run $CIRCLE_PROJECT_REPONAME make test

  tagged-build:
    machine:
      docker_layer_caching: true
    environment:
      AWS_REGION: eu-west-1
      AWS_ECR_REPONAME: 932815733038.dkr.ecr.eu-west-1.amazonaws.com/teonet
      YC_YCR_REPONAME: cr.yandex/crp8ph86e05bgnsgjbb8/teonet
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: docker build -t $CIRCLE_PROJECT_REPONAME -f sh/Dockerfile .
      - run: docker run $CIRCLE_PROJECT_REPONAME make test

      # login to ECR
      - run: $(aws --region $AWS_REGION ecr get-login --no-include-email)

      # push image to ECR
      - run: docker tag $CIRCLE_PROJECT_REPONAME ${AWS_ECR_REPONAME}:$CIRCLE_TAG
      - run: docker push ${AWS_ECR_REPONAME}:$CIRCLE_TAG
      - run: docker tag $CIRCLE_PROJECT_REPONAME ${AWS_ECR_REPONAME}:latest
      - run: docker push ${AWS_ECR_REPONAME}:latest
      
      # Login to Yandex Container Registry (YCR)
      - run: docker login --username $YAC_AUTH --password $YAC_TOKEN cr.yandex
      
      # Push to Yandex Container Registry (YCR)
      - run: docker tag $CIRCLE_PROJECT_REPONAME ${YC_YCR_REPONAME}:$CIRCLE_TAG
      - run: docker push ${YC_YCR_REPONAME}:$CIRCLE_TAG
      - run: docker tag ${CIRCLE_PROJECT_REPONAME} ${YC_YCR_REPONAME}:latest
      - run: docker push ${YC_YCR_REPONAME}:latest

workflows:
  version: 2
  untagged:
    jobs: 
     - testing
  tagged:
    jobs:
      - tagged-build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          
